"""AurelExec execution kernel (P4-EXEC-A admission/lease + P4-EXEC-B bridge).

Deterministic admission and lease foundation with the first governed
runtime submit bridge:
P3-like candidate -> ExecAdmissionRequest -> ExecAdmissionDecision
-> ExecutionLease -> ExecJob -> ExecutionSession -> ExecutionAttempt
-> ExecRuntimeBridge -> CommandEnvelope -> AgenticRuntime.submit()
-> ExecutionOutcome -> ExecTraceBinding -> ExecProjection.

Hard boundary: P4-EXEC-A created the execution gate and key; P4-EXEC-B
turns the key once, only through the existing ``AgenticRuntime.submit()``
kernel, only for the safe read-only TOOL path (``read_file``), only under a
valid lease and active session. AurelExec supervises the kernel and is
never a second executor: no direct tool dispatch, subprocess, network, raw
filesystem, sandbox, model, or verifier invocation, no manual Trace/Ledger
write, no manual policy/Custos enforcement, no worker/queue/bus/checkpoint/
recovery system. Runtime submit success is not semantic success;
trace-bound is not trace-verified. P3 proposes; P4 admits, leases, and
submits; P5 proves; P9 authorizes; Shell projects; Operator decides.

Like ``aurel_flow``, this package is not re-exported from the
``agentic_runtime`` top level; import it explicitly as
``agentic_runtime.aurel_exec``.
"""

from .exec_admission import (
    EXEC_ADMISSION_DECISION_VERSION,
    EXEC_ADMISSION_GATE_RESULT_VERSION,
    EXEC_ADMISSION_REQUEST_VERSION,
    STANDARD_UNAVAILABLE_REASONS,
    ExecAdmissionDecision,
    ExecAdmissionGateResult,
    ExecAdmissionRequest,
    ExecMissingRequirement,
    ExecUnavailableReason,
    build_dev_fixture_admission_request,
    decide_admission,
)
from .exec_errors import (
    AurelExecError,
    AurelExecErrorCode,
    AurelExecValidationError,
    reject,
)
from .exec_algedonic import (
    ALGEDONIC_AUTHORITY_BOUNDARY_REASON,
    ALGEDONIC_SIGNAL_VERSION,
    RUNTIME_SUBSTRATE_BOUNDARY_REASON,
    AlgedonicEscalationKind,
    AlgedonicSeverity,
    AlgedonicSignal,
    NoFinalPythonKernelClaimProof,
    NoRustRewriteProof,
    build_no_final_python_kernel_claim_proof,
    build_no_rust_rewrite_proof,
    create_algedonic_signal_if_needed,
)
from .exec_checkpoint import (
    CHECKPOINT_PERSISTENCE_UNAVAILABLE_REASON,
    EXECUTION_CHECKPOINT_REF_VERSION,
    EXECUTION_ROLLBACK_REF_VERSION,
    RECOVERY_ENGINE_UNAVAILABLE_REASON,
    ROLLBACK_EXECUTION_UNAVAILABLE_REASON,
    ExecutionCheckpointKind,
    ExecutionCheckpointRef,
    ExecutionRollbackRef,
    NoRecoveryEngineProof,
    NoRollbackExecutionProof,
    build_no_recovery_engine_proof,
    build_no_rollback_execution_proof,
    create_post_attempt_checkpoint_ref,
    create_pre_attempt_checkpoint_ref,
    create_rollback_ref,
)
from .exec_failure import (
    FAILURE_CLASSIFICATION_VERSION,
    FAILURE_METADATA,
    FailureClass,
    FailureClassification,
    FailureSeverity,
    classify_execution_failure,
    classify_pre_submit_block,
)
from .exec_job import (
    EXEC_JOB_VERSION,
    EXECUTION_ATTEMPT_VERSION,
    ExecJob,
    ExecutionAttempt,
    bind_lease_to_job,
    create_exec_job,
    create_execution_attempt,
    transition_exec_job,
    transition_execution_attempt,
)
from .exec_messages import (
    EXECUTION_MESSAGE_VERSION,
    LOCAL_EXECUTION_MESSAGE_LOG_VERSION,
    TRANSPORT_BUS_UNAVAILABLE_REASON,
    ExecutionMessage,
    ExecutionMessageKind,
    LocalExecutionMessageLog,
    NoTransportBusProof,
    append_execution_message,
    build_execution_message,
    build_no_transport_bus_proof,
    filter_execution_messages_by_attempt,
    filter_execution_messages_by_job,
    filter_execution_messages_by_queue_entry,
    filter_execution_messages_by_session,
    list_execution_messages,
)
from .exec_mode_profiles import (
    CODE_EXECUTION_PROFILE_VERSION,
    CODE_EXECUTION_UNAVAILABLE_REASON,
    MODEL_EXECUTION_PROFILE_VERSION,
    MODEL_EXECUTION_UNAVAILABLE_REASON,
    MUTATING_TOOLS_UNAVAILABLE_REASON,
    TERMINAL_EXECUTION_PROFILE_VERSION,
    TERMINAL_EXECUTION_UNAVAILABLE_REASON,
    TOOL_EXECUTION_PROFILE_VERSION,
    CodeExecutionProfile,
    ModelExecutionProfile,
    NoCodeExecutionProof,
    NoModelCallProof,
    NoTerminalExecutionProof,
    TerminalExecutionProfile,
    ToolExecutionProfile,
    build_default_code_execution_profile,
    build_default_execution_mode_registry,
    build_default_model_execution_profile,
    build_default_terminal_execution_profile,
    build_default_tool_execution_profile,
    build_no_code_execution_proof,
    build_no_model_call_proof,
    build_no_terminal_execution_proof,
)
from .exec_modes import (
    EXECUTION_MODE_PROFILE_VERSION,
    EXECUTION_MODE_REGISTRY_VERSION,
    MODE_COMPATIBILITY_DECISION_VERSION,
    SILENT_FALLBACK_FORBIDDEN_REASON,
    UNKNOWN_MODE_BLOCKED_REASON,
    ExecutionModeAvailability,
    ExecutionModeProfile,
    ExecutionModeRegistry,
    ModeCompatibilityDecision,
    NoSilentFallbackProof,
    build_no_silent_fallback_proof,
    decide_mode_compatibility,
    enforce_mode_compatibility_before_claim,
    require_mode_compatibility,
)
from .exec_outcome import (
    EXECUTION_OUTCOME_VERSION,
    ExecutionOutcome,
    ExecutionOutcomeStatus,
    normalize_runtime_result,
)
from .exec_queue import (
    EXEC_QUEUE_ENTRY_VERSION,
    QUEUE_IS_NOT_SCHEDULER_REASON,
    QUEUE_STATE_TRANSITIONS,
    ExecQueueEntry,
    ExecQueueState,
    block_queue_entry,
    create_queue_entry,
    mark_queue_entry_claimed,
    mark_queue_entry_completed,
    mark_queue_entry_failed,
    mark_queue_entry_running,
)
from .exec_runtime_bridge import (
    DIRECT_DISPATCH_FORBIDDEN_REASON,
    NO_DIRECT_DISPATCH_PROOF_VERSION,
    RUNTIME_BRIDGE_SUBMIT_REQUEST_VERSION,
    RUNTIME_BRIDGE_SUBMIT_RESULT_VERSION,
    RUNTIME_SUBMIT_PROOF_VERSION,
    SUPPORTED_BRIDGE_EXECUTION_MODES,
    SUPPORTED_BRIDGE_TOOLS,
    UNSUPPORTED_EXECUTION_MODE_PROOF_VERSION,
    ExecRuntimeBridge,
    NoDirectDispatchProof,
    RuntimeBridgeExecution,
    RuntimeBridgeSubmitRequest,
    RuntimeBridgeSubmitResult,
    RuntimeBridgeUnavailableReason,
    RuntimeSubmitProof,
    RuntimeSubmitStatus,
    UnsupportedExecutionModeProof,
    build_no_direct_dispatch_proof,
    build_runtime_bridge_submit_request,
    build_runtime_submit_proof,
    build_unsupported_execution_mode_proofs,
    describe_unavailable_mode,
)
from .exec_recovery import (
    AUTOMATIC_RETRY_UNAVAILABLE_REASON,
    BOUNDED_RECOVERY_PLAN_VERSION,
    RECOVERY_RECOMMENDATIONS,
    SELF_HEALING_UNAVAILABLE_REASON,
    BoundedRecoveryActionKind,
    BoundedRecoveryPlan,
    NoAutomaticRetryProof,
    NoSelfHealingProof,
    build_no_automatic_retry_proof,
    build_no_self_healing_proof,
    create_bounded_recovery_plan,
)
from .exec_session import (
    ACTIVE_SESSION_STATUSES,
    EXECUTION_SESSION_VERSION,
    SESSION_STATUS_TRANSITIONS,
    ExecutionSession,
    ExecutionSessionStatus,
    bind_session_to_job,
    close_execution_session,
    mark_session_failed,
    mark_session_running,
    open_execution_session,
)
from .exec_trace_binding import (
    EXEC_TRACE_BINDING_VERSION,
    ExecTraceBinding,
    build_exec_trace_binding,
)
from .exec_verification import (
    EXECUTION_VERIFICATION_DECISION_VERSION,
    EXECUTION_VERIFICATION_REQUEST_VERSION,
    P5_PROOF_UNAVAILABLE_REASON,
    P9_AUTHORITY_UNAVAILABLE_REASON,
    VERIFIER_HOOK_VERSION,
    VERIFIER_UNAVAILABLE_REASON,
    ExecutionVerificationDecision,
    ExecutionVerificationRequest,
    NoModelVerifierCallProof,
    NoP5ProofProof,
    NoP9AuthorityProof,
    VerificationStatus,
    VerifierHook,
    VerifierHookAvailability,
    build_execution_verification_request,
    build_no_model_verifier_call_proof,
    build_no_p5_proof_proof,
    build_no_p9_authority_proof,
    build_profile_only_verifier_hook,
    decide_verification,
)
from .exec_worker import (
    MANAGED_RUNTIME_RESULT_VERSION,
    QUEUE_CLAIM_VERSION,
    REMOTE_WORKER_UNAVAILABLE_REASON,
    WORKER_POOL_UNAVAILABLE_REASON,
    WORKER_SLOT_VERSION,
    ManagedRuntimeExecution,
    ManagedRuntimeResult,
    NoRemoteWorkerProof,
    NoWorkerPoolProof,
    QueueClaim,
    QueueClaimStatus,
    WorkerKind,
    WorkerSlot,
    WorkerSlotStatus,
    build_no_remote_worker_proof,
    build_no_worker_pool_proof,
    claim_queue_entry,
    create_local_worker_slot,
    fail_worker_slot,
    release_worker_slot,
    run_claimed_queue_entry_once,
)
from .exec_lease import (
    EXECUTION_LEASE_VERSION,
    LEASE_SCOPE_VERSION,
    LEASE_VALIDATION_RESULT_VERSION,
    ExecLeaseDenied,
    ExecutionLease,
    LeaseDenialReason,
    LeaseRevocationState,
    LeaseScope,
    LeaseValidationResult,
    issue_execution_lease,
    revoke_execution_lease,
    validate_execution_lease,
)
from .exec_projection import (
    EXEC_PROJECTION_VERSION,
    FUTURE_RUNTIME_BRIDGE_STEPS,
    MANAGED_RUNTIME_PROJECTION_VERSION,
    NO_CUSTOS_ENFORCEMENT_PROOF_VERSION,
    NO_RAW_EXECUTION_PROOF_VERSION,
    NO_RUNTIME_SUBMIT_PROOF_VERSION,
    NO_TRACE_VERIFIED_PROOF_VERSION,
    P4_EXEC_A_HANDOFF_FRAME_VERSION,
    STANDARD_BRIDGE_REQUIREMENTS,
    ExecAttemptGuardState,
    ExecLeaseProjectionState,
    ExecProjection,
    FutureRuntimeBridgeRequirement,
    JudgmentProjection,
    ManagedRuntimeProjection,
    ModeProjection,
    NoCustosEnforcementProof,
    NoRawExecutionProof,
    NoRuntimeSubmitProof,
    NoTraceVerifiedProof,
    P4ExecAHandoffFrame,
    RuntimeSubmitUnavailableReason,
    build_exec_projection,
    build_judgment_projection,
    build_managed_runtime_projection,
    build_mode_projection,
    build_no_custos_enforcement_proof,
    build_no_raw_execution_proof,
    build_no_runtime_submit_proof,
    build_no_trace_verified_proof,
    build_p4_exec_a_handoff_frame,
)
from .exec_types import (
    ADMISSION_GATE_ORDER,
    ATTEMPT_LIFECYCLE_TRANSITIONS,
    AUREL_EXEC_CONTRACT_VERSION,
    AUREL_EXEC_PACK_ID,
    AUREL_EXEC_PACK_TITLE,
    AUREL_EXEC_REPORT_PATH,
    CUSTOS_ENFORCEMENT_UNAVAILABLE_REASON,
    FORBIDDEN_EXEC_TRUTH_LABELS,
    JOB_LIFECYCLE_TRANSITIONS,
    P3_READY_MARKER,
    PERSISTENCE_UNAVAILABLE_REASON,
    POLICY_SHADOW_ONLY_REASON,
    RAW_EXECUTION_UNAVAILABLE_REASON,
    RUNTIME_SUBMIT_UNAVAILABLE_REASON,
    SANDBOX_REQUIRED_MODES,
    SHELL_PROJECTION_UNAVAILABLE_REASON,
    SUBMIT_AWARE_ATTEMPT_STATES,
    TRACE_VERIFICATION_UNAVAILABLE_REASON,
    VERIFIER_REQUIRED_MODES,
    AlgedonicSignalKind,
    ExecAdmissionGateKind,
    ExecAdmissionState,
    ExecCustosStatus,
    ExecLifecycleState,
    ExecMissingRequirementKind,
    ExecPolicyStatus,
    ExecTraceStatus,
    ExecTruthLabel,
    ExecUnavailableSystem,
    ExecutionFailureClass,
    ExecutionMode,
    ExecutionPlasticityLevel,
    ExecutionTopologyKind,
    RecoveryActionKind,
    TraceBindingStatus,
)
