"""Delegation / Non-Repudiation / Agent Identity Mesh (P1.8).

Foundation layer (P1.8.0): typed delegation records, reference-only evidence hooks,
identity mesh references, deterministic serialization, and honest capability reporting.

Identity / reference layer (P1.8.1): stable DelegationRef, DelegationIdentity,
DelegationRefBinding, and status report with deterministic hashing.

Role-binding layer (P1.8.2): typed, deterministic, JSON-safe role contracts for
delegator/delegate/subject bound to DelegationRef/DelegationIdentity without
approving, executing, enforcing, verifying, activating, or granting authority.

Constraint model layer (P1.8.3): declared constraint contracts bound to
DelegationRef / DelegationIdentity / DelegationRoleBindingSet without enforcing,
approving, blocking, verifying, resolving, or mutating runtime behavior.

Authority-reference binding layer (P1.8.4): reference-only authority context
binding to DelegationRef / DelegationIdentity / DelegationRoleBindingSet /
DelegationConstraintSet without granting authority, verifying authority,
creating approval, calling policy/Custos, enforcing constraints, executing
runtime actions, writing trace, or writing Ledger.

Evidence / non-repudiation reference binding layer (P1.8.5): deterministic,
versioned, JSON-safe, side-effect-free evidence hook for delegation
accountability. Binds reference-only evidence, claim, attestation, signature,
and trace refs to DelegationRef / DelegationIdentity /
DelegationRoleBindingSet / DelegationConstraintSet /
DelegationAuthorityBindingSet without verifying evidence, proving claims,
verifying signatures, verifying trace, claiming legal finality,
writing Ledger, writing global trace, or creating Output Passport behavior.

P1.8 does not authorize, enforce, verify, execute, or write trace/Ledger.

Architectural law:
  - DelegationRecord is not permission.
  - AuthorityRef is not granted authority.
  - NonRepudiationRef is not verified proof.
  - AgentIdentityMeshRef is not live mesh activation.
  - DelegationRef is not approval.
  - DelegationIdentity is not verification.
  - DelegationRefBinding is not trace proof.
  - record_hash is not TRACE_VERIFIED.
  - identity_hash is not proof.
  - DelegationPartyRoleRef is not verified authority.
  - DelegatedSubjectRef is not subject execution.
  - DelegationRoleBinding is not approval or permission.
  - DelegationRoleBindingSet is not enforcement.
  - role_binding_hash is not TRACE_VERIFIED.
  - Role model exists ≠ resolver exists.
  - Constraint exists ≠ constraint enforced.
  - Required review exists ≠ approval created.
  - Risk bound exists ≠ policy/Custos decision.
  - Tool bound exists ≠ tool permission changed.
  - Data bound exists ≠ data access changed.
  - Time bound exists ≠ scheduler changed.
  - Constraint hash exists ≠ TRACE_VERIFIED.
  - Constraint set exists ≠ runtime blocking.
  - Constraint model exists ≠ resolver exists.
  - Constraint binding exists ≠ authority granted.
  - AuthorityRef exists ≠ authority granted.
  - Authority basis exists ≠ authority verified.
  - Policy context ref exists ≠ policy/Custos decision.
  - Path authority ref exists ≠ path authorized.
  - Operator declaration exists ≠ legal or operational authority proven.
  - Authority binding exists ≠ approval created.
  - Authority binding exists ≠ permission granted.
  - Authority hash exists ≠ TRACE_VERIFIED.
  - Authority binding set exists ≠ runtime execution.
  - NonRepudiationRef exists ≠ non-repudiation is proven.
  - EvidenceRef exists ≠ evidence is verified.
  - ClaimRef exists ≠ claim is proven.
  - AttestationRef exists ≠ attestation is verified.
  - SignatureRef exists ≠ signature is verified.
  - TraceRef exists ≠ TRACE_VERIFIED.
  - EvidenceEnvelope exists ≠ legal finality.
  - CompletenessProfile exists ≠ trust score.
  - Evidence hash exists ≠ proof.
  - evidence_envelope_hash exists ≠ legal finality.
  - non_repudiation_binding_set_hash exists ≠ proof of non-repudiation.
  - DelegationChainRef exists ≠ chain verified.
  - DelegationHandoffRef exists ≠ handoff executed.
  - DelegationPredecessorRef exists ≠ predecessor valid.
  - DelegationSuccessorRef exists ≠ successor activated.
  - DelegationHandoffClaimRef exists ≠ handoff occurred.
  - DelegationHandoffAcceptanceClaimRef exists ≠ acceptance verified.
  - DelegationResponsibilityTransferClaimRef exists ≠ responsibility transferred.
  - DelegationLineageMap exists ≠ graph engine.
  - DelegationChainContinuityReadinessProfile exists ≠ continuity proven.
  - chain_envelope_hash exists ≠ TRACE_VERIFIED.
  - chain_binding_set_hash exists ≠ proof of transfer, handoff, or chain validity.
  - ShadowResolverResult exists ≠ policy decision.
  - ConsistencySnapshot exists ≠ delegation verified.
  - ConsistencyMatrix exists ≠ approval matrix.
  - ConsistencyFinding exists ≠ enforcement action.
  - CONFLICT_REFERENCED exists ≠ runtime denial.
  - PRESENT exists ≠ verified.
  - MISSING exists ≠ failed.
  - ReadinessProfile exists ≠ approval readiness.
  - Resolver hash exists ≠ TRACE_VERIFIED.
  - Shadow pass does not mean allowed.
  - Shadow fail does not mean blocked.
  - OperatorReviewRef exists does not mean review completed.
  - ApprovalIntentRef exists does not mean approval granted.
  - RejectionIntentRef exists does not mean request denied.
  - EscalationIntentRef exists does not mean escalation executed.
  - MoreContextIntentRef exists does not mean runtime blocked.
  - ReviewRationaleRef exists does not mean rationale verified.
  - OperatorReviewEnvelope exists does not mean approval record.
  - OperatorReviewReadinessProfile exists does not mean approval readiness.
  - Review hash exists does not mean TRACE_VERIFIED.
  - Intent exists does not mean operator decision.
  - PolicyBridgeRef exists ≠ policy evaluated.
  - CustosBridgeRef exists ≠ Custos called.
  - PolicyContextRef exists ≠ policy compliance.
  - CustosContextRef exists ≠ Custos approval.
  - DecisionRequestIntentRef exists ≠ decision request.
  - DecisionResponsePlaceholderRef exists ≠ decision response.
  - CompatibilityMatrix exists ≠ policy evaluation.
  - BridgeReadinessProfile exists ≠ decision readiness.
  - BridgeEnvelope exists ≠ policy decision.
  - RuntimeReadinessRef exists does not mean runtime ready.
  - ExecutionPreconditionRef exists does not mean precondition satisfied.
  - ExecutionBlockerRef exists does not mean runtime blocked.
  - RuntimeAdmissionIntentRef exists does not mean runtime admitted.
  - RuntimeAdmissionPlaceholderRef exists does not mean admission result.
  - RuntimeContextRef exists does not mean runtime initialized.
  - ToolExecutionContextRef exists does not mean tool dispatched.
  - RuntimeSessionPlaceholderRef exists does not mean runtime session created.
  - ExecutionTargetRef exists does not mean dispatch target selected.
  - ReadinessMatrix exists does not mean execution readiness.
  - RuntimeExecutionReadinessProfile exists does not mean execution readiness proof.
  - Runtime readiness hash exists does not mean TRACE_VERIFIED.
  - TraceBridgeRef exists does not mean trace written.
  - AuditBridgeRef exists does not mean audit completed.
  - LedgerBridgeRef exists does not mean Ledger entry written.
  - TraceEventIntentRef exists does not mean trace event emitted.
  - AuditEventIntentRef exists does not mean audit event emitted.
  - LedgerEntryPlaceholderRef exists does not mean Ledger entry exists.
  - ReplayContextRef exists does not mean replay executed.
  - ForkContextRef exists does not mean fork created.
  - CausalChainContextRef exists does not mean causal chain verified.
  - TraceAuditReadinessMatrix exists does not mean TRACE_VERIFIED.
  - TraceAuditReadinessProfile exists does not mean audit readiness proof.
  - Trace/audit hash exists does not mean TRACE_VERIFIED.
  - TraceAuditBridgeEnvelope exists does not mean trace write, audit finality, or Ledger write.
  - trace_audit_bridge_binding_set_hash exists does not mean trace/audit/Ledger proof.
"""
from __future__ import annotations

from .foundation import (
    ACTOR_REF_KNOWN_FIELDS,
    AUTHORITY_REF_KNOWN_FIELDS,
    CONSTRAINT_KNOWN_FIELDS,
    DELEGATION_FOUNDATION_STATUS_VERSION,
    DELEGATION_MODULE_NAME,
    DELEGATION_SCHEMA_VERSION,
    DELEGATION_TASK_ID,
    DELEGATION_UNAVAILABLE_BINDINGS,
    FOUNDATION_STATUS_KNOWN_FIELDS,
    IDENTITY_MESH_REF_KNOWN_FIELDS,
    NON_REPUDIATION_REF_KNOWN_FIELDS,
    RECORD_KNOWN_FIELDS,
    SIDE_EFFECTS_KNOWN_FIELDS,
    SUBJECT_KNOWN_FIELDS,
    AgentIdentityMeshRef,
    DelegationActorKind,
    DelegationActorRef,
    DelegationAuthorityKind,
    DelegationAuthorityRef,
    DelegationConstraint,
    DelegationConstraintKind,
    DelegationError,
    DelegationErrorCode,
    DelegationFoundationCapability,
    DelegationFoundationStatus,
    DelegationRecord,
    DelegationSerializationError,
    DelegationSideEffects,
    DelegationSourceLabel,
    DelegationStructuredError,
    DelegationSubject,
    DelegationSubjectKind,
    DelegationUnknownFieldError,
    DelegationValidationError,
    NonRepudiationProofStatus,
    NonRepudiationRef,
    build_agent_identity_mesh_ref,
    build_delegation_actor_ref,
    build_delegation_authority_ref,
    build_delegation_constraint,
    build_delegation_foundation_status,
    build_delegation_record,
    build_delegation_subject,
    build_non_repudiation_ref,
    hash_delegation_record,
    serialize_delegation_record,
    stable_hash,
    to_canonical_dict,
    to_canonical_json,
    validate_known_fields,
)

from .identity import (
    DELEGATION_IDENTITY_SCHEMA_VERSION,
    DELEGATION_IDENTITY_SIDE_EFFECTS_VERSION,
    DELEGATION_IDENTITY_STATUS_REPORT_VERSION,
    DELEGATION_IDENTITY_TASK_ID,
    DELEGATION_IDENTITY_UNAVAILABLE_BINDINGS,
    DELEGATION_REF_BINDING_SCHEMA_VERSION,
    DELEGATION_REF_KNOWN_FIELDS,
    DELEGATION_REF_SCHEMA_VERSION,
    IDENTITY_KNOWN_FIELDS,
    IDENTITY_SIDE_EFFECTS_KNOWN_FIELDS,
    IDENTITY_STATUS_REPORT_KNOWN_FIELDS,
    REF_BINDING_KNOWN_FIELDS,
    DelegationIdentity,
    DelegationIdentityKind,
    DelegationIdentitySideEffects,
    DelegationIdentityStatus,
    DelegationIdentityStatusReport,
    DelegationRef,
    DelegationRefBinding,
    DelegationRefBindingKind,
    build_delegation_identity,
    build_delegation_identity_status_report,
    build_delegation_ref,
    build_delegation_ref_binding,
    hash_delegation_identity,
    hash_delegation_ref,
    serialize_delegation_identity,
    serialize_delegation_ref,
)

from .roles import (
    DELEGATED_SUBJECT_REF_VERSION,
    DELEGATION_PARTY_ROLE_REF_VERSION,
    DELEGATION_ROLE_BINDING_SET_VERSION,
    DELEGATION_ROLE_BINDING_VERSION,
    DELEGATION_ROLES_TASK_ID,
    DELEGATION_ROLES_UNAVAILABLE_BINDINGS,
    DELEGATION_ROLE_SIDE_EFFECTS_VERSION,
    DELEGATION_ROLE_STATUS_REPORT_VERSION,
    PARTY_ROLE_REF_KNOWN_FIELDS,
    ROLE_BINDING_KNOWN_FIELDS,
    ROLE_BINDING_SET_KNOWN_FIELDS,
    ROLE_SIDE_EFFECTS_KNOWN_FIELDS,
    ROLE_STATUS_REPORT_KNOWN_FIELDS,
    SUBJECT_ROLE_REF_KNOWN_FIELDS,
    DelegatedSubjectRef,
    DelegationPartyRoleRef,
    DelegationRoleBinding,
    DelegationRoleBindingSet,
    DelegationRoleBindingStatus,
    DelegationRoleKind,
    DelegationRoleSideEffects,
    DelegationRoleStatusReport,
    build_delegated_subject_ref,
    build_delegation_party_role_ref,
    build_delegation_role_binding,
    build_delegation_role_binding_set,
    build_delegation_role_status_report,
    compute_role_binding_hash,
    compute_role_binding_set_hash,
    compute_role_ref_hash,
    compute_role_status_report_hash,
    compute_subject_role_hash,
    hash_delegation_role_binding_set,
    serialize_delegation_role_binding_set,
)

from .constraints import (
    CONSTRAINT_BINDING_KNOWN_FIELDS,
    CONSTRAINT_REF_KNOWN_FIELDS,
    CONSTRAINT_SET_KNOWN_FIELDS,
    CONSTRAINT_SIDE_EFFECTS_KNOWN_FIELDS,
    CONSTRAINT_STATUS_REPORT_KNOWN_FIELDS,
    DELEGATION_CONSTRAINTS_TASK_ID,
    DELEGATION_CONSTRAINTS_UNAVAILABLE_BINDINGS,
    DELEGATION_CONSTRAINT_BINDING_VERSION,
    DELEGATION_CONSTRAINT_REF_VERSION,
    DELEGATION_CONSTRAINT_SET_VERSION,
    DELEGATION_CONSTRAINT_SIDE_EFFECTS_VERSION,
    DELEGATION_CONSTRAINT_STATUS_REPORT_VERSION,
    DelegationConstraintBinding,
    DelegationConstraintRef,
    DelegationConstraintSet,
    DelegationConstraintSeverity,
    DelegationConstraintSideEffects,
    DelegationConstraintStatus,
    DelegationConstraintStatusReport,
    build_delegation_constraint_binding,
    build_delegation_constraint_ref,
    build_delegation_constraint_set,
    build_delegation_constraint_status_report,
    hash_delegation_constraint_ref,
    hash_delegation_constraint_set,
    serialize_delegation_constraint_ref,
    serialize_delegation_constraint_set,
)

from .authority import (
    AUTHORITY_BINDING_KNOWN_FIELDS,
    AUTHORITY_BINDING_SET_KNOWN_FIELDS,
    AUTHORITY_REF_KNOWN_FIELDS,
    AUTHORITY_SIDE_EFFECTS_KNOWN_FIELDS,
    AUTHORITY_STATUS_REPORT_KNOWN_FIELDS,
    DELEGATION_AUTHORITY_BINDING_SET_VERSION,
    DELEGATION_AUTHORITY_BINDING_VERSION,
    DELEGATION_AUTHORITY_REF_VERSION,
    DELEGATION_AUTHORITY_SIDE_EFFECTS_VERSION,
    DELEGATION_AUTHORITY_STATUS_REPORT_VERSION,
    DELEGATION_AUTHORITY_TASK_ID,
    DELEGATION_AUTHORITY_UNAVAILABLE_BINDINGS,
    DelegationAuthorityBinding,
    DelegationAuthorityBindingSet,
    DelegationAuthorityRef,
    DelegationAuthorityRefKind,
    DelegationAuthorityRefStatus,
    DelegationAuthoritySideEffects,
    DelegationAuthorityStatusReport,
    build_delegation_authority_binding,
    build_delegation_authority_binding_set,
    build_delegation_authority_ref,
    build_delegation_authority_status_report,
    hash_delegation_authority_binding_set,
    hash_delegation_authority_ref,
    serialize_delegation_authority_binding_set,
    serialize_delegation_authority_ref,
)

from .non_repudiation import (
    CLAIM_REF_KNOWN_FIELDS,
    COMPLETENESS_PROFILE_KNOWN_FIELDS,
    DELEGATION_CLAIM_REF_VERSION,
    DELEGATION_EVIDENCE_COMPLETENESS_PROFILE_VERSION,
    DELEGATION_EVIDENCE_ENVELOPE_VERSION,
    DELEGATION_EVIDENCE_REF_VERSION,
    DELEGATION_NON_REPUDIATION_BINDING_SET_VERSION,
    DELEGATION_NON_REPUDIATION_BINDING_VERSION,
    DELEGATION_NON_REPUDIATION_SIDE_EFFECTS_VERSION,
    DELEGATION_NON_REPUDIATION_STATUS_REPORT_VERSION,
    DELEGATION_NON_REPUDIATION_TASK_ID,
    DELEGATION_NON_REPUDIATION_UNAVAILABLE_BINDINGS,
    EVIDENCE_ENVELOPE_KNOWN_FIELDS,
    EVIDENCE_REF_KNOWN_FIELDS,
    NON_REPUDIATION_BINDING_KNOWN_FIELDS,
    NON_REPUDIATION_BINDING_SET_KNOWN_FIELDS,
    NON_REPUDIATION_SIDE_EFFECTS_KNOWN_FIELDS,
    NON_REPUDIATION_STATUS_REPORT_KNOWN_FIELDS,
    DelegationDisputeReadinessStatus,
    DelegationEvidenceCompletenessProfile,
    DelegationEvidenceEnvelope,
    DelegationEvidenceKind,
    DelegationEvidenceRef,
    DelegationEvidenceStatus,
    DelegationNonRepudiationBinding,
    DelegationNonRepudiationBindingSet,
    DelegationNonRepudiationClaimRef,
    DelegationNonRepudiationSideEffects,
    DelegationNonRepudiationStatusReport,
    DelegationProofReferenceStatus,
    build_delegation_evidence_completeness_profile,
    build_delegation_evidence_envelope,
    build_delegation_evidence_ref,
    build_delegation_non_repudiation_binding,
    build_delegation_non_repudiation_binding_set,
    build_delegation_non_repudiation_claim_ref,
    build_delegation_non_repudiation_status_report,
    hash_delegation_evidence_completeness_profile,
    hash_delegation_evidence_envelope,
    hash_delegation_evidence_ref,
    hash_delegation_non_repudiation_binding_set,
    hash_delegation_non_repudiation_claim_ref,
    serialize_delegation_evidence_envelope,
    serialize_delegation_non_repudiation_binding_set,
)

from .identity_mesh import (
    DELEGATION_IDENTITY_MESH_BINDING_SET_VERSION,
    DELEGATION_IDENTITY_MESH_BINDING_VERSION,
    DELEGATION_IDENTITY_MESH_ENVELOPE_VERSION,
    DELEGATION_IDENTITY_MESH_SIDE_EFFECTS_VERSION,
    DELEGATION_IDENTITY_MESH_STATUS_REPORT_VERSION,
    DELEGATION_IDENTITY_MESH_TASK_ID,
    DELEGATION_IDENTITY_MESH_UNAVAILABLE_BINDINGS,
    DELEGATION_MESH_PARTICIPANT_REF_VERSION,
    DELEGATION_MESH_READINESS_PROFILE_VERSION,
    DELEGATION_MESH_RELATIONSHIP_MAP_VERSION,
    DELEGATION_MESH_RELATIONSHIP_REF_VERSION,
    DELEGATION_MESH_SCOPE_REF_VERSION,
    MESH_BINDING_KNOWN_FIELDS,
    MESH_BINDING_SET_KNOWN_FIELDS,
    MESH_ENVELOPE_KNOWN_FIELDS,
    MESH_SCOPE_REF_KNOWN_FIELDS,
    MESH_SIDE_EFFECTS_KNOWN_FIELDS,
    MESH_STATUS_REPORT_KNOWN_FIELDS,
    PARTICIPANT_REF_KNOWN_FIELDS,
    READINESS_PROFILE_KNOWN_FIELDS,
    RELATIONSHIP_MAP_KNOWN_FIELDS,
    RELATIONSHIP_REF_KNOWN_FIELDS,
    DelegationIdentityMeshBinding,
    DelegationIdentityMeshBindingSet,
    DelegationIdentityMeshEnvelope,
    DelegationIdentityMeshSideEffects,
    DelegationIdentityMeshStatusReport,
    DelegationMeshParticipantKind,
    DelegationMeshParticipantRef,
    DelegationMeshRefStatus,
    DelegationMeshRelationshipKind,
    DelegationMeshRelationshipMap,
    DelegationMeshRelationshipRef,
    DelegationMeshResolutionReadinessProfile,
    DelegationMeshResolutionStatus,
    DelegationMeshScopeKind,
    DelegationMeshScopeRef,
    build_delegation_identity_mesh_binding,
    build_delegation_identity_mesh_binding_set,
    build_delegation_identity_mesh_envelope,
    build_delegation_identity_mesh_status_report,
    build_delegation_mesh_participant_ref,
    build_delegation_mesh_relationship_map,
    build_delegation_mesh_relationship_ref,
    build_delegation_mesh_resolution_readiness_profile,
    build_delegation_mesh_scope_ref,
    hash_delegation_identity_mesh_binding,
    hash_delegation_identity_mesh_binding_set,
    hash_delegation_identity_mesh_envelope,
    hash_delegation_mesh_participant_ref,
    hash_delegation_mesh_relationship_map,
    hash_delegation_mesh_relationship_ref,
    hash_delegation_mesh_resolution_readiness_profile,
    hash_delegation_mesh_scope_ref,
    serialize_delegation_identity_mesh_binding,
    serialize_delegation_identity_mesh_binding_set,
    serialize_delegation_identity_mesh_envelope,
    serialize_delegation_mesh_participant_ref,
    serialize_delegation_mesh_relationship_map,
    serialize_delegation_mesh_relationship_ref,
    serialize_delegation_mesh_resolution_readiness_profile,
    serialize_delegation_mesh_scope_ref,
)

from .scope import (
    BOUNDARY_MATRIX_KNOWN_FIELDS,
    BOUNDARY_REF_KNOWN_FIELDS,
    DELEGATION_BOUNDARY_MATRIX_ENTRY_VERSION,
    DELEGATION_BOUNDARY_MATRIX_VERSION,
    DELEGATION_BOUNDARY_REF_VERSION,
    DELEGATION_SCOPE_BINDING_SET_VERSION,
    DELEGATION_SCOPE_BINDING_VERSION,
    DELEGATION_SCOPE_ENVELOPE_VERSION,
    DELEGATION_SCOPE_EXCLUSION_REF_VERSION,
    DELEGATION_SCOPE_INCLUSION_REF_VERSION,
    DELEGATION_SCOPE_READINESS_PROFILE_VERSION,
    DELEGATION_SCOPE_REF_VERSION,
    DELEGATION_SCOPE_SIDE_EFFECTS_VERSION,
    DELEGATION_SCOPE_STATUS_REPORT_VERSION,
    DELEGATION_SCOPE_TASK_ID,
    DELEGATION_SCOPE_UNAVAILABLE_BINDINGS,
    EXCLUSION_REF_KNOWN_FIELDS,
    INCLUSION_REF_KNOWN_FIELDS,
    MATRIX_ENTRY_KNOWN_FIELDS,
    READINESS_PROFILE_KNOWN_FIELDS as SCOPE_READINESS_PROFILE_KNOWN_FIELDS,
    SCOPE_BINDING_KNOWN_FIELDS,
    SCOPE_BINDING_SET_KNOWN_FIELDS,
    SCOPE_ENVELOPE_KNOWN_FIELDS,
    SCOPE_REF_KNOWN_FIELDS,
    SCOPE_SIDE_EFFECTS_KNOWN_FIELDS,
    SCOPE_STATUS_REPORT_KNOWN_FIELDS,
    DelegationBoundaryKind,
    DelegationBoundaryMatrix,
    DelegationBoundaryMatrixEntry,
    DelegationBoundaryPosture,
    DelegationBoundaryRef,
    DelegationScopeBinding,
    DelegationScopeBindingSet,
    DelegationScopeDimension,
    DelegationScopeEnvelope,
    DelegationScopeExclusionRef,
    DelegationScopeInclusionRef,
    DelegationScopeKind,
    DelegationScopeReadinessProfile,
    DelegationScopeRef,
    DelegationScopeSideEffects,
    DelegationScopeStatus,
    DelegationScopeStatusReport,
    build_delegation_boundary_matrix,
    build_delegation_boundary_matrix_entry,
    build_delegation_boundary_ref,
    build_delegation_scope_binding,
    build_delegation_scope_binding_set,
    build_delegation_scope_envelope,
    build_delegation_scope_exclusion_ref,
    build_delegation_scope_inclusion_ref,
    build_delegation_scope_readiness_profile,
    build_delegation_scope_ref,
    build_delegation_scope_status_report,
    hash_delegation_boundary_matrix,
    hash_delegation_boundary_ref,
    hash_delegation_scope_binding_set,
    hash_delegation_scope_envelope,
    hash_delegation_scope_exclusion_ref,
    hash_delegation_scope_inclusion_ref,
    hash_delegation_scope_readiness_profile,
    hash_delegation_scope_ref,
    serialize_delegation_scope_binding_set,
    serialize_delegation_scope_envelope,
)

from .lifecycle import (
    DELEGATION_EXPIRY_REF_VERSION,
    DELEGATION_LIFECYCLE_BINDING_SET_VERSION,
    DELEGATION_LIFECYCLE_BINDING_VERSION,
    DELEGATION_LIFECYCLE_ENVELOPE_VERSION,
    DELEGATION_LIFECYCLE_READINESS_PROFILE_VERSION,
    DELEGATION_LIFECYCLE_SIDE_EFFECTS_VERSION,
    DELEGATION_LIFECYCLE_STATUS_REPORT_VERSION,
    DELEGATION_LIFECYCLE_TASK_ID,
    DELEGATION_LIFECYCLE_UNAVAILABLE_BINDINGS,
    DELEGATION_RENEWAL_REF_VERSION,
    DELEGATION_REVOCATION_REASON_REF_VERSION,
    DELEGATION_REVOCATION_REF_VERSION,
    DELEGATION_SUPERSESSION_REF_VERSION,
    DELEGATION_SUSPENSION_REF_VERSION,
    EXPIRY_REF_KNOWN_FIELDS,
    LIFECYCLE_BINDING_KNOWN_FIELDS,
    LIFECYCLE_BINDING_SET_KNOWN_FIELDS,
    LIFECYCLE_ENVELOPE_KNOWN_FIELDS,
    LIFECYCLE_READINESS_PROFILE_KNOWN_FIELDS,
    LIFECYCLE_SIDE_EFFECTS_KNOWN_FIELDS,
    LIFECYCLE_STATUS_REPORT_KNOWN_FIELDS,
    REASON_REF_KNOWN_FIELDS,
    RENEWAL_REF_KNOWN_FIELDS,
    REVOCATION_REF_KNOWN_FIELDS,
    SUPERSESSION_REF_KNOWN_FIELDS,
    SUSPENSION_REF_KNOWN_FIELDS,
    DelegationExpiryRef,
    DelegationLifecycleBinding,
    DelegationLifecycleBindingSet,
    DelegationLifecycleEnvelope,
    DelegationLifecycleEventKind,
    DelegationLifecycleReadinessProfile,
    DelegationLifecycleReferenceStatus,
    DelegationLifecycleSideEffects,
    DelegationLifecycleStatus,
    DelegationLifecycleStatusReport,
    DelegationRenewalRef,
    DelegationRevocationReasonKind,
    DelegationRevocationReasonRef,
    DelegationRevocationRef,
    DelegationSupersessionRef,
    DelegationSuspensionRef,
    build_delegation_expiry_ref,
    build_delegation_lifecycle_binding,
    build_delegation_lifecycle_binding_set,
    build_delegation_lifecycle_envelope,
    build_delegation_lifecycle_readiness_profile,
    build_delegation_lifecycle_status_report,
    build_delegation_renewal_ref,
    build_delegation_revocation_reason_ref,
    build_delegation_revocation_ref,
    build_delegation_supersession_ref,
    build_delegation_suspension_ref,
    hash_delegation_expiry_ref,
    hash_delegation_lifecycle_binding_set,
    hash_delegation_lifecycle_envelope,
    hash_delegation_lifecycle_readiness_profile,
    hash_delegation_renewal_ref,
    hash_delegation_revocation_reason_ref,
    hash_delegation_revocation_ref,
    hash_delegation_supersession_ref,
    hash_delegation_suspension_ref,
    serialize_delegation_lifecycle_binding_set,
    serialize_delegation_lifecycle_envelope,
)

from .shadow_resolver import (
    CONSISTENCY_MATRIX_KNOWN_FIELDS,
    DELEGATION_CONSISTENCY_FINDING_VERSION,
    DELEGATION_CONSISTENCY_MATRIX_ENTRY_VERSION,
    DELEGATION_CONSISTENCY_MATRIX_VERSION,
    DELEGATION_CONSISTENCY_SNAPSHOT_VERSION,
    DELEGATION_SHADOW_RESOLVER_INPUT_ENVELOPE_VERSION,
    DELEGATION_SHADOW_RESOLVER_READINESS_PROFILE_VERSION,
    DELEGATION_SHADOW_RESOLVER_RESULT_VERSION,
    DELEGATION_SHADOW_RESOLVER_SIDE_EFFECTS_VERSION,
    DELEGATION_SHADOW_RESOLVER_STATUS_REPORT_VERSION,
    DELEGATION_SHADOW_RESOLVER_TASK_ID,
    DELEGATION_SHADOW_RESOLVER_UNAVAILABLE_BINDINGS,
    FINDING_KNOWN_FIELDS,
    INPUT_ENVELOPE_KNOWN_FIELDS,
    MATRIX_ENTRY_KNOWN_FIELDS,
    READINESS_PROFILE_KNOWN_FIELDS as SHADOW_READINESS_PROFILE_KNOWN_FIELDS,
    SHADOW_RESULT_KNOWN_FIELDS,
    SIDE_EFFECTS_KNOWN_FIELDS as SHADOW_SIDE_EFFECTS_KNOWN_FIELDS,
    SNAPSHOT_KNOWN_FIELDS,
    STATUS_REPORT_KNOWN_FIELDS as SHADOW_STATUS_REPORT_KNOWN_FIELDS,
    DelegationConsistencyFamily,
    DelegationConsistencyFinding,
    DelegationConsistencyFindingKind,
    DelegationConsistencyMatrix,
    DelegationConsistencyMatrixEntry,
    DelegationConsistencySeverity,
    DelegationConsistencySnapshot,
    DelegationShadowResolverInputEnvelope,
    DelegationShadowResolverMode,
    DelegationShadowResolverReadinessProfile,
    DelegationShadowResolverResult,
    DelegationShadowResolverSideEffects,
    DelegationShadowResolverStatus,
    DelegationShadowResolverStatusReport,
    build_delegation_consistency_finding,
    build_delegation_consistency_matrix,
    build_delegation_consistency_matrix_entry,
    build_delegation_consistency_snapshot,
    build_delegation_shadow_resolver_input_envelope,
    build_delegation_shadow_resolver_readiness_profile,
    build_delegation_shadow_resolver_result,
    build_delegation_shadow_resolver_status_report,
    hash_delegation_consistency_finding,
    hash_delegation_consistency_matrix,
    hash_delegation_consistency_matrix_entry,
    hash_delegation_consistency_snapshot,
    hash_delegation_shadow_resolver_input_envelope,
    hash_delegation_shadow_resolver_readiness_profile,
    hash_delegation_shadow_resolver_result,
    hash_delegation_shadow_resolver_status_report,
    serialize_delegation_consistency_matrix,
    serialize_delegation_shadow_resolver_input_envelope,
    serialize_delegation_shadow_resolver_result,
)

from .operator_review import (
    APPROVAL_INTENT_REF_KNOWN_FIELDS,
    DELEGATION_APPROVAL_INTENT_REF_VERSION,
    DELEGATION_ESCALATION_INTENT_REF_VERSION,
    DELEGATION_MORE_CONTEXT_INTENT_REF_VERSION,
    DELEGATION_OPERATOR_REVIEW_BINDING_SET_VERSION,
    DELEGATION_OPERATOR_REVIEW_BINDING_VERSION,
    DELEGATION_OPERATOR_REVIEW_ENVELOPE_VERSION,
    DELEGATION_OPERATOR_REVIEW_READINESS_PROFILE_VERSION,
    DELEGATION_OPERATOR_REVIEW_REF_VERSION,
    DELEGATION_OPERATOR_REVIEW_SIDE_EFFECTS_VERSION,
    DELEGATION_OPERATOR_REVIEW_STATUS_REPORT_VERSION,
    DELEGATION_OPERATOR_REVIEW_TASK_ID,
    DELEGATION_OPERATOR_REVIEW_UNAVAILABLE_BINDINGS,
    DELEGATION_REJECTION_INTENT_REF_VERSION,
    DELEGATION_REVIEW_RATIONALE_REF_VERSION,
    ESCALATION_INTENT_REF_KNOWN_FIELDS,
    MORE_CONTEXT_INTENT_REF_KNOWN_FIELDS,
    OPERATOR_REVIEW_ENVELOPE_KNOWN_FIELDS,
    OPERATOR_REVIEW_REF_KNOWN_FIELDS,
    RATIONALE_REF_KNOWN_FIELDS,
    REJECTION_INTENT_REF_KNOWN_FIELDS,
    REVIEW_BINDING_KNOWN_FIELDS,
    REVIEW_BINDING_SET_KNOWN_FIELDS,
    REVIEW_READINESS_PROFILE_KNOWN_FIELDS,
    REVIEW_SIDE_EFFECTS_KNOWN_FIELDS,
    REVIEW_STATUS_REPORT_KNOWN_FIELDS,
    DelegationApprovalIntentRef,
    DelegationEscalationIntentRef,
    DelegationMoreContextIntentRef,
    DelegationOperatorReviewBinding,
    DelegationOperatorReviewBindingSet,
    DelegationOperatorReviewEnvelope,
    DelegationOperatorReviewIntentKind,
    DelegationOperatorReviewKind,
    DelegationOperatorReviewReadinessProfile,
    DelegationOperatorReviewRef,
    DelegationOperatorReviewReferenceStatus,
    DelegationOperatorReviewSideEffects,
    DelegationOperatorReviewStatus,
    DelegationOperatorReviewStatusReport,
    DelegationRejectionIntentRef,
    DelegationReviewRationaleKind,
    DelegationReviewRationaleRef,
    build_delegation_approval_intent_ref,
    build_delegation_escalation_intent_ref,
    build_delegation_more_context_intent_ref,
    build_delegation_operator_review_binding,
    build_delegation_operator_review_binding_set,
    build_delegation_operator_review_envelope,
    build_delegation_operator_review_readiness_profile,
    build_delegation_operator_review_ref,
    build_delegation_operator_review_status_report,
    build_delegation_rejection_intent_ref,
    build_delegation_review_rationale_ref,
    hash_delegation_approval_intent_ref,
    hash_delegation_escalation_intent_ref,
    hash_delegation_more_context_intent_ref,
    hash_delegation_operator_review_binding,
    hash_delegation_operator_review_binding_set,
    hash_delegation_operator_review_envelope,
    hash_delegation_operator_review_readiness_profile,
    hash_delegation_operator_review_ref,
    hash_delegation_operator_review_status_report,
    hash_delegation_rejection_intent_ref,
    hash_delegation_review_rationale_ref,
    serialize_delegation_operator_review_binding_set,
    serialize_delegation_operator_review_envelope,
)

from .policy_bridge import (
    BRIDGE_BINDING_KNOWN_FIELDS,
    BRIDGE_BINDING_SET_KNOWN_FIELDS,
    BRIDGE_ENVELOPE_KNOWN_FIELDS,
    BRIDGE_READINESS_PROFILE_KNOWN_FIELDS,
    BRIDGE_SIDE_EFFECTS_KNOWN_FIELDS,
    BRIDGE_STATUS_REPORT_KNOWN_FIELDS,
    COMPATIBILITY_MATRIX_ENTRY_KNOWN_FIELDS,
    COMPATIBILITY_MATRIX_PB_KNOWN_FIELDS,
    CUSTOS_BRIDGE_REF_KNOWN_FIELDS,
    CUSTOS_CONTEXT_REF_KNOWN_FIELDS,
    CUSTOS_DECISION_REQUEST_INTENT_REF_KNOWN_FIELDS,
    CUSTOS_DECISION_RESPONSE_PLACEHOLDER_REF_KNOWN_FIELDS,
    DELEGATION_CUSTOS_BRIDGE_REF_VERSION,
    DELEGATION_CUSTOS_CONTEXT_REF_VERSION,
    DELEGATION_CUSTOS_DECISION_REQUEST_INTENT_REF_VERSION,
    DELEGATION_CUSTOS_DECISION_RESPONSE_PLACEHOLDER_REF_VERSION,
    DELEGATION_POLICY_BRIDGE_REF_VERSION,
    DELEGATION_POLICY_CONTEXT_REF_VERSION,
    DELEGATION_POLICY_CUSTOS_BRIDGE_BINDING_SET_VERSION,
    DELEGATION_POLICY_CUSTOS_BRIDGE_BINDING_VERSION,
    DELEGATION_POLICY_CUSTOS_BRIDGE_ENVELOPE_VERSION,
    DELEGATION_POLICY_CUSTOS_BRIDGE_READINESS_PROFILE_VERSION,
    DELEGATION_POLICY_CUSTOS_BRIDGE_SIDE_EFFECTS_VERSION,
    DELEGATION_POLICY_CUSTOS_BRIDGE_STATUS_REPORT_VERSION,
    DELEGATION_POLICY_CUSTOS_BRIDGE_TASK_ID,
    DELEGATION_POLICY_CUSTOS_BRIDGE_UNAVAILABLE_BINDINGS,
    DELEGATION_POLICY_CUSTOS_COMPATIBILITY_MATRIX_ENTRY_VERSION,
    DELEGATION_POLICY_CUSTOS_COMPATIBILITY_MATRIX_VERSION,
    DELEGATION_POLICY_DECISION_REQUEST_INTENT_REF_VERSION,
    DELEGATION_POLICY_DECISION_RESPONSE_PLACEHOLDER_REF_VERSION,
    POLICY_BRIDGE_REF_KNOWN_FIELDS,
    POLICY_CONTEXT_REF_KNOWN_FIELDS,
    POLICY_DECISION_REQUEST_INTENT_REF_KNOWN_FIELDS,
    POLICY_DECISION_RESPONSE_PLACEHOLDER_REF_KNOWN_FIELDS,
    DelegationCustosBridgeRef,
    DelegationCustosContextKind,
    DelegationCustosContextRef,
    DelegationCustosDecisionRequestIntentRef,
    DelegationCustosDecisionResponsePlaceholderRef,
    DelegationPolicyBridgeRef,
    DelegationPolicyContextKind,
    DelegationPolicyContextRef,
    DelegationPolicyCustosBridgeBinding,
    DelegationPolicyCustosBridgeBindingSet,
    DelegationPolicyCustosBridgeEnvelope,
    DelegationPolicyCustosBridgeKind,
    DelegationPolicyCustosBridgeReadinessProfile,
    DelegationPolicyCustosBridgeReferenceStatus,
    DelegationPolicyCustosBridgeSideEffects,
    DelegationPolicyCustosBridgeStatus,
    DelegationPolicyCustosBridgeStatusReport,
    DelegationPolicyCustosCompatibilityFamily,
    DelegationPolicyCustosCompatibilityMatrix,
    DelegationPolicyCustosCompatibilityMatrixEntry,
    DelegationPolicyDecisionRequestIntentRef,
    DelegationPolicyDecisionResponsePlaceholderRef,
    build_delegation_custos_bridge_ref,
    build_delegation_custos_context_ref,
    build_delegation_custos_decision_request_intent_ref,
    build_delegation_custos_decision_response_placeholder_ref,
    build_delegation_policy_bridge_ref,
    build_delegation_policy_context_ref,
    build_delegation_policy_custos_bridge_binding,
    build_delegation_policy_custos_bridge_binding_set,
    build_delegation_policy_custos_bridge_envelope,
    build_delegation_policy_custos_bridge_readiness_profile,
    build_delegation_policy_custos_bridge_status_report,
    build_delegation_policy_custos_compatibility_matrix,
    build_delegation_policy_custos_compatibility_matrix_entry,
    build_delegation_policy_decision_request_intent_ref,
    build_delegation_policy_decision_response_placeholder_ref,
    hash_delegation_custos_bridge_ref,
    hash_delegation_custos_context_ref,
    hash_delegation_custos_decision_request_intent_ref,
    hash_delegation_custos_decision_response_placeholder_ref,
    hash_delegation_policy_bridge_ref,
    hash_delegation_policy_context_ref,
    hash_delegation_policy_custos_bridge_binding,
    hash_delegation_policy_custos_bridge_binding_set,
    hash_delegation_policy_custos_bridge_envelope,
    hash_delegation_policy_custos_bridge_readiness_profile,
    hash_delegation_policy_custos_bridge_status_report,
    hash_delegation_policy_custos_compatibility_matrix,
    hash_delegation_policy_custos_compatibility_matrix_entry,
    hash_delegation_policy_decision_request_intent_ref,
    hash_delegation_policy_decision_response_placeholder_ref,
    serialize_delegation_policy_custos_bridge_binding_set,
    serialize_delegation_policy_custos_bridge_envelope,
)

from .chain import (
    ACCEPTANCE_CLAIM_REF_KNOWN_FIELDS,
    CHAIN_BINDING_KNOWN_FIELDS,
    CHAIN_BINDING_SET_KNOWN_FIELDS,
    CHAIN_ENVELOPE_KNOWN_FIELDS,
    CHAIN_READINESS_PROFILE_KNOWN_FIELDS,
    CHAIN_REF_KNOWN_FIELDS,
    CHAIN_SIDE_EFFECTS_KNOWN_FIELDS,
    CHAIN_STATUS_REPORT_KNOWN_FIELDS,
    DELEGATION_CHAIN_BINDING_SET_VERSION,
    DELEGATION_CHAIN_BINDING_VERSION,
    DELEGATION_CHAIN_CONTINUITY_READINESS_PROFILE_VERSION,
    DELEGATION_CHAIN_ENVELOPE_VERSION,
    DELEGATION_CHAIN_REF_VERSION,
    DELEGATION_CHAIN_SIDE_EFFECTS_VERSION,
    DELEGATION_CHAIN_STATUS_REPORT_VERSION,
    DELEGATION_CHAIN_TASK_ID,
    DELEGATION_CHAIN_UNAVAILABLE_BINDINGS,
    DELEGATION_HANDOFF_ACCEPTANCE_CLAIM_REF_VERSION,
    DELEGATION_HANDOFF_CLAIM_REF_VERSION,
    DELEGATION_HANDOFF_REF_VERSION,
    DELEGATION_LINEAGE_MAP_VERSION,
    DELEGATION_PREDECESSOR_REF_VERSION,
    DELEGATION_RESPONSIBILITY_TRANSFER_CLAIM_REF_VERSION,
    DELEGATION_SUCCESSOR_REF_VERSION,
    HANDOFF_CLAIM_REF_KNOWN_FIELDS,
    HANDOFF_REF_KNOWN_FIELDS,
    LINEAGE_MAP_KNOWN_FIELDS,
    PREDECESSOR_REF_KNOWN_FIELDS,
    SUCCESSOR_REF_KNOWN_FIELDS,
    TRANSFER_CLAIM_REF_KNOWN_FIELDS,
    DelegationChainBinding,
    DelegationChainBindingSet,
    DelegationChainContinuityReadinessProfile,
    DelegationChainEnvelope,
    DelegationChainLinkKind,
    DelegationChainRef,
    DelegationChainReferenceStatus,
    DelegationChainSideEffects,
    DelegationChainStatus,
    DelegationChainStatusReport,
    DelegationHandoffAcceptanceClaimRef,
    DelegationHandoffClaimRef,
    DelegationHandoffKind,
    DelegationHandoffRef,
    DelegationLineageMap,
    DelegationPredecessorRef,
    DelegationResponsibilityTransferClaimRef,
    DelegationSuccessorRef,
    build_delegation_chain_binding,
    build_delegation_chain_binding_set,
    build_delegation_chain_continuity_readiness_profile,
    build_delegation_chain_envelope,
    build_delegation_chain_ref,
    build_delegation_chain_status_report,
    build_delegation_handoff_acceptance_claim_ref,
    build_delegation_handoff_claim_ref,
    build_delegation_handoff_ref,
    build_delegation_lineage_map,
    build_delegation_predecessor_ref,
    build_delegation_responsibility_transfer_claim_ref,
    build_delegation_successor_ref,
    hash_delegation_chain_binding,
    hash_delegation_chain_binding_set,
    hash_delegation_chain_continuity_readiness_profile,
    hash_delegation_chain_envelope,
    hash_delegation_chain_ref,
    hash_delegation_handoff_acceptance_claim_ref,
    hash_delegation_handoff_claim_ref,
    hash_delegation_handoff_ref,
    hash_delegation_lineage_map,
    hash_delegation_predecessor_ref,
    hash_delegation_responsibility_transfer_claim_ref,
    hash_delegation_successor_ref,
    serialize_delegation_chain_binding_set,
    serialize_delegation_chain_envelope,
)

from .runtime_readiness import (
    DELEGATION_RUNTIME_EXECUTION_READINESS_BINDING_SET_VERSION,
    DELEGATION_RUNTIME_EXECUTION_READINESS_BINDING_VERSION,
    DELEGATION_RUNTIME_EXECUTION_READINESS_ENVELOPE_VERSION,
    DELEGATION_RUNTIME_EXECUTION_READINESS_MATRIX_ENTRY_VERSION,
    DELEGATION_RUNTIME_EXECUTION_READINESS_MATRIX_VERSION,
    DELEGATION_RUNTIME_EXECUTION_READINESS_PROFILE_VERSION,
    DELEGATION_RUNTIME_EXECUTION_READINESS_SIDE_EFFECTS_VERSION,
    DELEGATION_RUNTIME_EXECUTION_READINESS_STATUS_REPORT_VERSION,
    DELEGATION_RUNTIME_EXECUTION_READINESS_TASK_ID,
    DELEGATION_RUNTIME_EXECUTION_READINESS_UNAVAILABLE_BINDINGS,
    DELEGATION_EXECUTION_BLOCKER_REF_VERSION,
    DELEGATION_EXECUTION_PRECONDITION_REF_VERSION,
    DELEGATION_EXECUTION_TARGET_REF_VERSION,
    DELEGATION_RUNTIME_ADMISSION_INTENT_REF_VERSION,
    DELEGATION_RUNTIME_ADMISSION_PLACEHOLDER_REF_VERSION,
    DELEGATION_RUNTIME_CONTEXT_REF_VERSION,
    DELEGATION_RUNTIME_READINESS_REF_VERSION,
    DELEGATION_RUNTIME_SESSION_PLACEHOLDER_REF_VERSION,
    DELEGATION_TOOL_EXECUTION_CONTEXT_REF_VERSION,
    # known fields
    EXECUTION_BLOCKER_REF_KNOWN_FIELDS,
    EXECUTION_PRECONDITION_REF_KNOWN_FIELDS,
    EXECUTION_TARGET_REF_KNOWN_FIELDS,
    READINESS_BINDING_KNOWN_FIELDS,
    READINESS_BINDING_SET_KNOWN_FIELDS,
    READINESS_ENVELOPE_KNOWN_FIELDS,
    READINESS_MATRIX_ENTRY_KNOWN_FIELDS,
    READINESS_MATRIX_KNOWN_FIELDS,
    READINESS_READINESS_PROFILE_KNOWN_FIELDS,
    READINESS_SIDE_EFFECTS_KNOWN_FIELDS,
    READINESS_STATUS_REPORT_KNOWN_FIELDS,
    RUNTIME_ADMISSION_INTENT_REF_KNOWN_FIELDS,
    RUNTIME_ADMISSION_PLACEHOLDER_REF_KNOWN_FIELDS,
    RUNTIME_CONTEXT_REF_KNOWN_FIELDS,
    RUNTIME_READINESS_REF_KNOWN_FIELDS,
    RUNTIME_SESSION_PLACEHOLDER_REF_KNOWN_FIELDS,
    TOOL_EXECUTION_CONTEXT_REF_KNOWN_FIELDS,
    # enums
    DelegationExecutionContextKind,
    DelegationRuntimeContextKind,
    DelegationRuntimeExecutionReadinessFamily,
    DelegationRuntimeExecutionReadinessKind,
    DelegationRuntimeExecutionReadinessReferenceStatus,
    DelegationRuntimeExecutionReadinessStatus,
    # dataclasses
    DelegationExecutionBlockerRef,
    DelegationExecutionPreconditionRef,
    DelegationExecutionTargetRef,
    DelegationRuntimeAdmissionIntentRef,
    DelegationRuntimeAdmissionPlaceholderRef,
    DelegationRuntimeContextRef,
    DelegationRuntimeExecutionReadinessBinding,
    DelegationRuntimeExecutionReadinessBindingSet,
    DelegationRuntimeExecutionReadinessEnvelope,
    DelegationRuntimeExecutionReadinessMatrix,
    DelegationRuntimeExecutionReadinessMatrixEntry,
    DelegationRuntimeExecutionReadinessProfile,
    DelegationRuntimeExecutionReadinessSideEffects,
    DelegationRuntimeExecutionReadinessStatusReport,
    DelegationRuntimeReadinessRef,
    DelegationRuntimeSessionPlaceholderRef,
    DelegationToolExecutionContextRef,
    # builders
    build_delegation_execution_blocker_ref,
    build_delegation_execution_precondition_ref,
    build_delegation_execution_target_ref,
    build_delegation_runtime_admission_intent_ref,
    build_delegation_runtime_admission_placeholder_ref,
    build_delegation_runtime_context_ref,
    build_delegation_runtime_execution_readiness_binding,
    build_delegation_runtime_execution_readiness_binding_set,
    build_delegation_runtime_execution_readiness_envelope,
    build_delegation_runtime_execution_readiness_matrix,
    build_delegation_runtime_execution_readiness_matrix_entry,
    build_delegation_runtime_execution_readiness_profile,
    build_delegation_runtime_execution_readiness_status_report,
    build_delegation_runtime_readiness_ref,
    build_delegation_runtime_session_placeholder_ref,
    build_delegation_tool_execution_context_ref,
    # hash functions
    hash_delegation_execution_blocker_ref,
    hash_delegation_execution_precondition_ref,
    hash_delegation_execution_target_ref,
    hash_delegation_runtime_admission_intent_ref,
    hash_delegation_runtime_admission_placeholder_ref,
    hash_delegation_runtime_context_ref,
    hash_delegation_runtime_execution_readiness_binding,
    hash_delegation_runtime_execution_readiness_binding_set,
    hash_delegation_runtime_execution_readiness_envelope,
    hash_delegation_runtime_execution_readiness_matrix,
    hash_delegation_runtime_execution_readiness_matrix_entry,
    hash_delegation_runtime_execution_readiness_profile,
    hash_delegation_runtime_execution_readiness_status_report,
    hash_delegation_runtime_readiness_ref,
    hash_delegation_runtime_session_placeholder_ref,
    hash_delegation_tool_execution_context_ref,
    # serializers
    serialize_delegation_runtime_execution_readiness_binding_set,
    serialize_delegation_runtime_execution_readiness_envelope,
)

from .trace_audit_bridge import (
    DELEGATION_TRACE_AUDIT_BRIDGE_TASK_ID,
    DELEGATION_TRACE_BRIDGE_REF_VERSION,
    DELEGATION_AUDIT_BRIDGE_REF_VERSION,
    DELEGATION_LEDGER_BRIDGE_REF_VERSION,
    DELEGATION_TRACE_EVENT_INTENT_REF_VERSION,
    DELEGATION_AUDIT_EVENT_INTENT_REF_VERSION,
    DELEGATION_LEDGER_ENTRY_PLACEHOLDER_REF_VERSION,
    DELEGATION_REPLAY_CONTEXT_REF_VERSION,
    DELEGATION_FORK_CONTEXT_REF_VERSION,
    DELEGATION_CAUSAL_CHAIN_CONTEXT_REF_VERSION,
    DELEGATION_TRACE_AUDIT_READINESS_MATRIX_ENTRY_VERSION,
    DELEGATION_TRACE_AUDIT_READINESS_MATRIX_VERSION,
    DELEGATION_TRACE_AUDIT_READINESS_PROFILE_VERSION,
    DELEGATION_TRACE_AUDIT_BRIDGE_ENVELOPE_VERSION,
    DELEGATION_TRACE_AUDIT_BRIDGE_BINDING_VERSION,
    DELEGATION_TRACE_AUDIT_BRIDGE_BINDING_SET_VERSION,
    DELEGATION_TRACE_AUDIT_BRIDGE_SIDE_EFFECTS_VERSION,
    DELEGATION_TRACE_AUDIT_BRIDGE_STATUS_REPORT_VERSION,
    DELEGATION_TRACE_AUDIT_BRIDGE_UNAVAILABLE_BINDINGS,
    # known fields
    TRACE_BRIDGE_REF_KNOWN_FIELDS,
    AUDIT_BRIDGE_REF_KNOWN_FIELDS,
    LEDGER_BRIDGE_REF_KNOWN_FIELDS,
    TRACE_EVENT_INTENT_REF_KNOWN_FIELDS,
    AUDIT_EVENT_INTENT_REF_KNOWN_FIELDS,
    LEDGER_ENTRY_PLACEHOLDER_REF_KNOWN_FIELDS,
    REPLAY_CONTEXT_REF_KNOWN_FIELDS,
    FORK_CONTEXT_REF_KNOWN_FIELDS,
    CAUSAL_CHAIN_CONTEXT_REF_KNOWN_FIELDS,
    READINESS_MATRIX_ENTRY_KNOWN_FIELDS,
    READINESS_MATRIX_KNOWN_FIELDS,
    TRACE_AUDIT_READINESS_PROFILE_KNOWN_FIELDS,
    BRIDGE_ENVELOPE_KNOWN_FIELDS,
    BRIDGE_BINDING_KNOWN_FIELDS,
    BRIDGE_BINDING_SET_KNOWN_FIELDS,
    BRIDGE_SIDE_EFFECTS_KNOWN_FIELDS,
    BRIDGE_STATUS_REPORT_KNOWN_FIELDS,
    # enums
    DelegationTraceAuditBridgeKind,
    DelegationTraceAuditBridgeReferenceStatus,
    DelegationTraceAuditBridgeStatus,
    DelegationTraceContextKind,
    DelegationAuditContextKind,
    DelegationTraceAuditReadinessFamily,
    # dataclasses
    DelegationTraceBridgeRef,
    DelegationAuditBridgeRef,
    DelegationLedgerBridgeRef,
    DelegationTraceEventIntentRef,
    DelegationAuditEventIntentRef,
    DelegationLedgerEntryPlaceholderRef,
    DelegationReplayContextRef,
    DelegationForkContextRef,
    DelegationCausalChainContextRef,
    DelegationTraceAuditReadinessMatrixEntry,
    DelegationTraceAuditReadinessMatrix,
    DelegationTraceAuditReadinessProfile,
    DelegationTraceAuditBridgeEnvelope,
    DelegationTraceAuditBridgeBinding,
    DelegationTraceAuditBridgeBindingSet,
    DelegationTraceAuditBridgeSideEffects,
    DelegationTraceAuditBridgeStatusReport,
    # builders
    build_delegation_trace_bridge_ref,
    build_delegation_audit_bridge_ref,
    build_delegation_ledger_bridge_ref,
    build_delegation_trace_event_intent_ref,
    build_delegation_audit_event_intent_ref,
    build_delegation_ledger_entry_placeholder_ref,
    build_delegation_replay_context_ref,
    build_delegation_fork_context_ref,
    build_delegation_causal_chain_context_ref,
    build_delegation_trace_audit_readiness_matrix_entry,
    build_delegation_trace_audit_readiness_matrix,
    build_delegation_trace_audit_readiness_profile,
    build_delegation_trace_audit_bridge_envelope,
    build_delegation_trace_audit_bridge_binding,
    build_delegation_trace_audit_bridge_binding_set,
    build_delegation_trace_audit_bridge_status_report,
    # hash functions
    hash_delegation_trace_bridge_ref,
    hash_delegation_audit_bridge_ref,
    hash_delegation_ledger_bridge_ref,
    hash_delegation_trace_event_intent_ref,
    hash_delegation_audit_event_intent_ref,
    hash_delegation_ledger_entry_placeholder_ref,
    hash_delegation_replay_context_ref,
    hash_delegation_fork_context_ref,
    hash_delegation_causal_chain_context_ref,
    hash_delegation_trace_audit_readiness_matrix_entry,
    hash_delegation_trace_audit_readiness_matrix,
    hash_delegation_trace_audit_readiness_profile,
    hash_delegation_trace_audit_bridge_envelope,
    hash_delegation_trace_audit_bridge_binding,
    hash_delegation_trace_audit_bridge_binding_set,
    hash_delegation_trace_audit_bridge_status_report,
    # serializers
    serialize_delegation_trace_audit_bridge_envelope,
    serialize_delegation_trace_audit_bridge_binding_set,
)

__all__ = [
    # P1.8.0 foundation constants
    "ACTOR_REF_KNOWN_FIELDS",
    "AUTHORITY_REF_KNOWN_FIELDS",
    "CONSTRAINT_KNOWN_FIELDS",
    "DELEGATION_FOUNDATION_STATUS_VERSION",
    "DELEGATION_MODULE_NAME",
    "DELEGATION_SCHEMA_VERSION",
    "DELEGATION_TASK_ID",
    "DELEGATION_UNAVAILABLE_BINDINGS",
    "FOUNDATION_STATUS_KNOWN_FIELDS",
    "IDENTITY_MESH_REF_KNOWN_FIELDS",
    "NON_REPUDIATION_REF_KNOWN_FIELDS",
    "RECORD_KNOWN_FIELDS",
    "SIDE_EFFECTS_KNOWN_FIELDS",
    "SUBJECT_KNOWN_FIELDS",
    # P1.8.0 enums
    "DelegationActorKind",
    "DelegationAuthorityKind",
    "DelegationConstraintKind",
    "DelegationFoundationCapability",
    "DelegationErrorCode",
    "DelegationSourceLabel",
    "DelegationSubjectKind",
    "NonRepudiationProofStatus",
    # P1.8.0 dataclasses
    "AgentIdentityMeshRef",
    "DelegationActorRef",
    "DelegationAuthorityRef",
    "DelegationConstraint",
    "DelegationFoundationStatus",
    "DelegationRecord",
    "DelegationSideEffects",
    "DelegationStructuredError",
    "DelegationSubject",
    "NonRepudiationRef",
    # P1.8.0 errors
    "DelegationError",
    "DelegationSerializationError",
    "DelegationUnknownFieldError",
    "DelegationValidationError",
    # P1.8.0 builders / helpers
    "build_agent_identity_mesh_ref",
    "build_delegation_actor_ref",
    "build_delegation_authority_ref",
    "build_delegation_constraint",
    "build_delegation_foundation_status",
    "build_delegation_record",
    "build_delegation_subject",
    "build_non_repudiation_ref",
    "hash_delegation_record",
    "serialize_delegation_record",
    "stable_hash",
    "to_canonical_dict",
    "to_canonical_json",
    "validate_known_fields",
    # P1.8.1 identity constants
    "DELEGATION_IDENTITY_SCHEMA_VERSION",
    "DELEGATION_IDENTITY_SIDE_EFFECTS_VERSION",
    "DELEGATION_IDENTITY_STATUS_REPORT_VERSION",
    "DELEGATION_IDENTITY_TASK_ID",
    "DELEGATION_IDENTITY_UNAVAILABLE_BINDINGS",
    "DELEGATION_REF_BINDING_SCHEMA_VERSION",
    "DELEGATION_REF_KNOWN_FIELDS",
    "DELEGATION_REF_SCHEMA_VERSION",
    "IDENTITY_KNOWN_FIELDS",
    "IDENTITY_SIDE_EFFECTS_KNOWN_FIELDS",
    "IDENTITY_STATUS_REPORT_KNOWN_FIELDS",
    "REF_BINDING_KNOWN_FIELDS",
    # P1.8.1 enums
    "DelegationIdentityKind",
    "DelegationIdentityStatus",
    "DelegationRefBindingKind",
    # P1.8.1 dataclasses
    "DelegationIdentity",
    "DelegationIdentitySideEffects",
    "DelegationIdentityStatusReport",
    "DelegationRef",
    "DelegationRefBinding",
    # P1.8.1 builders / helpers
    "build_delegation_identity",
    "build_delegation_identity_status_report",
    "build_delegation_ref",
    "build_delegation_ref_binding",
    "hash_delegation_identity",
    "hash_delegation_ref",
    "serialize_delegation_identity",
    "serialize_delegation_ref",
    # P1.8.2 role constants
    "DELEGATED_SUBJECT_REF_VERSION",
    "DELEGATION_PARTY_ROLE_REF_VERSION",
    "DELEGATION_ROLE_BINDING_SET_VERSION",
    "DELEGATION_ROLE_BINDING_VERSION",
    "DELEGATION_ROLES_TASK_ID",
    "DELEGATION_ROLES_UNAVAILABLE_BINDINGS",
    "DELEGATION_ROLE_SIDE_EFFECTS_VERSION",
    "DELEGATION_ROLE_STATUS_REPORT_VERSION",
    "PARTY_ROLE_REF_KNOWN_FIELDS",
    "ROLE_BINDING_KNOWN_FIELDS",
    "ROLE_BINDING_SET_KNOWN_FIELDS",
    "ROLE_SIDE_EFFECTS_KNOWN_FIELDS",
    "ROLE_STATUS_REPORT_KNOWN_FIELDS",
    "SUBJECT_ROLE_REF_KNOWN_FIELDS",
    # P1.8.2 enums
    "DelegationRoleBindingStatus",
    "DelegationRoleKind",
    # P1.8.2 dataclasses
    "DelegatedSubjectRef",
    "DelegationPartyRoleRef",
    "DelegationRoleBinding",
    "DelegationRoleBindingSet",
    "DelegationRoleSideEffects",
    "DelegationRoleStatusReport",
    # P1.8.2 builders / helpers / hash functions
    "build_delegated_subject_ref",
    "build_delegation_party_role_ref",
    "build_delegation_role_binding",
    "build_delegation_role_binding_set",
    "build_delegation_role_status_report",
    "compute_role_binding_hash",
    "compute_role_binding_set_hash",
    "compute_role_ref_hash",
    "compute_role_status_report_hash",
    "compute_subject_role_hash",
    "hash_delegation_role_binding_set",
    "serialize_delegation_role_binding_set",
    # P1.8.3 constraint constants
    "CONSTRAINT_BINDING_KNOWN_FIELDS",
    "CONSTRAINT_REF_KNOWN_FIELDS",
    "CONSTRAINT_SET_KNOWN_FIELDS",
    "CONSTRAINT_SIDE_EFFECTS_KNOWN_FIELDS",
    "CONSTRAINT_STATUS_REPORT_KNOWN_FIELDS",
    "DELEGATION_CONSTRAINTS_TASK_ID",
    "DELEGATION_CONSTRAINTS_UNAVAILABLE_BINDINGS",
    "DELEGATION_CONSTRAINT_BINDING_VERSION",
    "DELEGATION_CONSTRAINT_REF_VERSION",
    "DELEGATION_CONSTRAINT_SET_VERSION",
    "DELEGATION_CONSTRAINT_SIDE_EFFECTS_VERSION",
    "DELEGATION_CONSTRAINT_STATUS_REPORT_VERSION",
    # P1.8.3 enums
    "DelegationConstraintSeverity",
    "DelegationConstraintStatus",
    # P1.8.3 dataclasses
    "DelegationConstraintBinding",
    "DelegationConstraintRef",
    "DelegationConstraintSet",
    "DelegationConstraintSideEffects",
    "DelegationConstraintStatusReport",
    # P1.8.3 builders / helpers / hash functions
    "build_delegation_constraint_binding",
    "build_delegation_constraint_ref",
    "build_delegation_constraint_set",
    "build_delegation_constraint_status_report",
    "hash_delegation_constraint_ref",
    "hash_delegation_constraint_set",
    "serialize_delegation_constraint_ref",
    "serialize_delegation_constraint_set",
    # P1.8.4 authority constants
    "AUTHORITY_BINDING_KNOWN_FIELDS",
    "AUTHORITY_BINDING_SET_KNOWN_FIELDS",
    "AUTHORITY_REF_KNOWN_FIELDS",
    "AUTHORITY_SIDE_EFFECTS_KNOWN_FIELDS",
    "AUTHORITY_STATUS_REPORT_KNOWN_FIELDS",
    "DELEGATION_AUTHORITY_BINDING_SET_VERSION",
    "DELEGATION_AUTHORITY_BINDING_VERSION",
    "DELEGATION_AUTHORITY_REF_VERSION",
    "DELEGATION_AUTHORITY_SIDE_EFFECTS_VERSION",
    "DELEGATION_AUTHORITY_STATUS_REPORT_VERSION",
    "DELEGATION_AUTHORITY_TASK_ID",
    "DELEGATION_AUTHORITY_UNAVAILABLE_BINDINGS",
    # P1.8.4 enums
    "DelegationAuthorityRefKind",
    "DelegationAuthorityRefStatus",
    # P1.8.4 dataclasses
    "DelegationAuthorityBinding",
    "DelegationAuthorityBindingSet",
    "DelegationAuthorityRef",
    "DelegationAuthoritySideEffects",
    "DelegationAuthorityStatusReport",
    # P1.8.4 builders / helpers / hash functions
    "build_delegation_authority_binding",
    "build_delegation_authority_binding_set",
    "build_delegation_authority_ref",
    "build_delegation_authority_status_report",
    "hash_delegation_authority_binding_set",
    "hash_delegation_authority_ref",
    "serialize_delegation_authority_binding_set",
    "serialize_delegation_authority_ref",
    # P1.8.5 non-repudiation constants
    "CLAIM_REF_KNOWN_FIELDS",
    "COMPLETENESS_PROFILE_KNOWN_FIELDS",
    "DELEGATION_CLAIM_REF_VERSION",
    "DELEGATION_EVIDENCE_COMPLETENESS_PROFILE_VERSION",
    "DELEGATION_EVIDENCE_ENVELOPE_VERSION",
    "DELEGATION_EVIDENCE_REF_VERSION",
    "DELEGATION_NON_REPUDIATION_BINDING_SET_VERSION",
    "DELEGATION_NON_REPUDIATION_BINDING_VERSION",
    "DELEGATION_NON_REPUDIATION_SIDE_EFFECTS_VERSION",
    "DELEGATION_NON_REPUDIATION_STATUS_REPORT_VERSION",
    "DELEGATION_NON_REPUDIATION_TASK_ID",
    "DELEGATION_NON_REPUDIATION_UNAVAILABLE_BINDINGS",
    "EVIDENCE_ENVELOPE_KNOWN_FIELDS",
    "EVIDENCE_REF_KNOWN_FIELDS",
    "NON_REPUDIATION_BINDING_KNOWN_FIELDS",
    "NON_REPUDIATION_BINDING_SET_KNOWN_FIELDS",
    "NON_REPUDIATION_SIDE_EFFECTS_KNOWN_FIELDS",
    "NON_REPUDIATION_STATUS_REPORT_KNOWN_FIELDS",
    # P1.8.5 enums
    "DelegationDisputeReadinessStatus",
    "DelegationEvidenceKind",
    "DelegationEvidenceStatus",
    "DelegationProofReferenceStatus",
    # P1.8.5 dataclasses
    "DelegationEvidenceRef",
    "DelegationNonRepudiationClaimRef",
    "DelegationEvidenceEnvelope",
    "DelegationEvidenceCompletenessProfile",
    "DelegationNonRepudiationBinding",
    "DelegationNonRepudiationBindingSet",
    "DelegationNonRepudiationSideEffects",
    "DelegationNonRepudiationStatusReport",
    # P1.8.5 builders / helpers / hash functions
    "build_delegation_evidence_ref",
    "build_delegation_non_repudiation_claim_ref",
    "build_delegation_evidence_envelope",
    "build_delegation_evidence_completeness_profile",
    "build_delegation_non_repudiation_binding",
    "build_delegation_non_repudiation_binding_set",
    "build_delegation_non_repudiation_status_report",
    "serialize_delegation_evidence_envelope",
    "serialize_delegation_non_repudiation_binding_set",
    "hash_delegation_evidence_ref",
    "hash_delegation_non_repudiation_claim_ref",
    "hash_delegation_evidence_envelope",
    "hash_delegation_evidence_completeness_profile",
    "hash_delegation_non_repudiation_binding_set",
    # P1.8.6 identity mesh constants
    "DELEGATION_IDENTITY_MESH_BINDING_SET_VERSION",
    "DELEGATION_IDENTITY_MESH_BINDING_VERSION",
    "DELEGATION_IDENTITY_MESH_ENVELOPE_VERSION",
    "DELEGATION_IDENTITY_MESH_SIDE_EFFECTS_VERSION",
    "DELEGATION_IDENTITY_MESH_STATUS_REPORT_VERSION",
    "DELEGATION_IDENTITY_MESH_TASK_ID",
    "DELEGATION_IDENTITY_MESH_UNAVAILABLE_BINDINGS",
    "DELEGATION_MESH_PARTICIPANT_REF_VERSION",
    "DELEGATION_MESH_READINESS_PROFILE_VERSION",
    "DELEGATION_MESH_RELATIONSHIP_MAP_VERSION",
    "DELEGATION_MESH_RELATIONSHIP_REF_VERSION",
    "DELEGATION_MESH_SCOPE_REF_VERSION",
    "MESH_BINDING_KNOWN_FIELDS",
    "MESH_BINDING_SET_KNOWN_FIELDS",
    "MESH_ENVELOPE_KNOWN_FIELDS",
    "MESH_SCOPE_REF_KNOWN_FIELDS",
    "MESH_SIDE_EFFECTS_KNOWN_FIELDS",
    "MESH_STATUS_REPORT_KNOWN_FIELDS",
    "PARTICIPANT_REF_KNOWN_FIELDS",
    "READINESS_PROFILE_KNOWN_FIELDS",
    "RELATIONSHIP_MAP_KNOWN_FIELDS",
    "RELATIONSHIP_REF_KNOWN_FIELDS",
    # P1.8.6 enums
    "DelegationMeshParticipantKind",
    "DelegationMeshRelationshipKind",
    "DelegationMeshScopeKind",
    "DelegationMeshRefStatus",
    "DelegationMeshResolutionStatus",
    # P1.8.6 dataclasses
    "DelegationIdentityMeshBinding",
    "DelegationIdentityMeshBindingSet",
    "DelegationIdentityMeshEnvelope",
    "DelegationIdentityMeshSideEffects",
    "DelegationIdentityMeshStatusReport",
    "DelegationMeshParticipantRef",
    "DelegationMeshRelationshipMap",
    "DelegationMeshRelationshipRef",
    "DelegationMeshResolutionReadinessProfile",
    "DelegationMeshScopeRef",
    # P1.8.6 builders / helpers / hash functions
    "build_delegation_identity_mesh_binding",
    "build_delegation_identity_mesh_binding_set",
    "build_delegation_identity_mesh_envelope",
    "build_delegation_identity_mesh_status_report",
    "build_delegation_mesh_participant_ref",
    "build_delegation_mesh_relationship_map",
    "build_delegation_mesh_relationship_ref",
    "build_delegation_mesh_resolution_readiness_profile",
    "build_delegation_mesh_scope_ref",
    "hash_delegation_identity_mesh_binding",
    "hash_delegation_identity_mesh_binding_set",
    "hash_delegation_identity_mesh_envelope",
    "hash_delegation_mesh_participant_ref",
    "hash_delegation_mesh_relationship_map",
    "hash_delegation_mesh_relationship_ref",
    "hash_delegation_mesh_resolution_readiness_profile",
    "hash_delegation_mesh_scope_ref",
    "serialize_delegation_identity_mesh_binding",
    "serialize_delegation_identity_mesh_binding_set",
    "serialize_delegation_identity_mesh_envelope",
    "serialize_delegation_mesh_participant_ref",
    "serialize_delegation_mesh_relationship_map",
    "serialize_delegation_mesh_relationship_ref",
    "serialize_delegation_mesh_resolution_readiness_profile",
    "serialize_delegation_mesh_scope_ref",
    # P1.8.7 scope constants
    "BOUNDARY_MATRIX_KNOWN_FIELDS",
    "BOUNDARY_REF_KNOWN_FIELDS",
    "DELEGATION_BOUNDARY_MATRIX_ENTRY_VERSION",
    "DELEGATION_BOUNDARY_MATRIX_VERSION",
    "DELEGATION_BOUNDARY_REF_VERSION",
    "DELEGATION_SCOPE_BINDING_SET_VERSION",
    "DELEGATION_SCOPE_BINDING_VERSION",
    "DELEGATION_SCOPE_ENVELOPE_VERSION",
    "DELEGATION_SCOPE_EXCLUSION_REF_VERSION",
    "DELEGATION_SCOPE_INCLUSION_REF_VERSION",
    "DELEGATION_SCOPE_READINESS_PROFILE_VERSION",
    "DELEGATION_SCOPE_REF_VERSION",
    "DELEGATION_SCOPE_SIDE_EFFECTS_VERSION",
    "DELEGATION_SCOPE_STATUS_REPORT_VERSION",
    "DELEGATION_SCOPE_TASK_ID",
    "DELEGATION_SCOPE_UNAVAILABLE_BINDINGS",
    "EXCLUSION_REF_KNOWN_FIELDS",
    "INCLUSION_REF_KNOWN_FIELDS",
    "MATRIX_ENTRY_KNOWN_FIELDS",
    "SCOPE_READINESS_PROFILE_KNOWN_FIELDS",
    "SCOPE_BINDING_KNOWN_FIELDS",
    "SCOPE_BINDING_SET_KNOWN_FIELDS",
    "SCOPE_ENVELOPE_KNOWN_FIELDS",
    "SCOPE_REF_KNOWN_FIELDS",
    "SCOPE_SIDE_EFFECTS_KNOWN_FIELDS",
    "SCOPE_STATUS_REPORT_KNOWN_FIELDS",
    # P1.8.7 enums
    "DelegationBoundaryKind",
    "DelegationBoundaryPosture",
    "DelegationScopeDimension",
    "DelegationScopeKind",
    "DelegationScopeStatus",
    # P1.8.7 dataclasses
    "DelegationBoundaryMatrix",
    "DelegationBoundaryMatrixEntry",
    "DelegationBoundaryRef",
    "DelegationScopeBinding",
    "DelegationScopeBindingSet",
    "DelegationScopeEnvelope",
    "DelegationScopeExclusionRef",
    "DelegationScopeInclusionRef",
    "DelegationScopeReadinessProfile",
    "DelegationScopeRef",
    "DelegationScopeSideEffects",
    "DelegationScopeStatusReport",
    # P1.8.7 builders / helpers / hash functions
    "build_delegation_boundary_matrix",
    "build_delegation_boundary_matrix_entry",
    "build_delegation_boundary_ref",
    "build_delegation_scope_binding",
    "build_delegation_scope_binding_set",
    "build_delegation_scope_envelope",
    "build_delegation_scope_exclusion_ref",
    "build_delegation_scope_inclusion_ref",
    "build_delegation_scope_readiness_profile",
    "build_delegation_scope_ref",
    "build_delegation_scope_status_report",
    "hash_delegation_boundary_matrix",
    "hash_delegation_boundary_ref",
    "hash_delegation_scope_binding_set",
    "hash_delegation_scope_envelope",
    "hash_delegation_scope_exclusion_ref",
    "hash_delegation_scope_inclusion_ref",
    "hash_delegation_scope_readiness_profile",
    "hash_delegation_scope_ref",
    "serialize_delegation_scope_binding_set",
    "serialize_delegation_scope_envelope",
    # P1.8.8 lifecycle constants
    "DELEGATION_EXPIRY_REF_VERSION",
    "DELEGATION_LIFECYCLE_BINDING_SET_VERSION",
    "DELEGATION_LIFECYCLE_BINDING_VERSION",
    "DELEGATION_LIFECYCLE_ENVELOPE_VERSION",
    "DELEGATION_LIFECYCLE_READINESS_PROFILE_VERSION",
    "DELEGATION_LIFECYCLE_SIDE_EFFECTS_VERSION",
    "DELEGATION_LIFECYCLE_STATUS_REPORT_VERSION",
    "DELEGATION_LIFECYCLE_TASK_ID",
    "DELEGATION_LIFECYCLE_UNAVAILABLE_BINDINGS",
    "DELEGATION_RENEWAL_REF_VERSION",
    "DELEGATION_REVOCATION_REASON_REF_VERSION",
    "DELEGATION_REVOCATION_REF_VERSION",
    "DELEGATION_SUPERSESSION_REF_VERSION",
    "DELEGATION_SUSPENSION_REF_VERSION",
    "EXPIRY_REF_KNOWN_FIELDS",
    "LIFECYCLE_BINDING_KNOWN_FIELDS",
    "LIFECYCLE_BINDING_SET_KNOWN_FIELDS",
    "LIFECYCLE_ENVELOPE_KNOWN_FIELDS",
    "LIFECYCLE_READINESS_PROFILE_KNOWN_FIELDS",
    "LIFECYCLE_SIDE_EFFECTS_KNOWN_FIELDS",
    "LIFECYCLE_STATUS_REPORT_KNOWN_FIELDS",
    "REASON_REF_KNOWN_FIELDS",
    "RENEWAL_REF_KNOWN_FIELDS",
    "REVOCATION_REF_KNOWN_FIELDS",
    "SUPERSESSION_REF_KNOWN_FIELDS",
    "SUSPENSION_REF_KNOWN_FIELDS",
    # P1.8.8 enums
    "DelegationLifecycleEventKind",
    "DelegationLifecycleReferenceStatus",
    "DelegationLifecycleStatus",
    "DelegationRevocationReasonKind",
    # P1.8.8 dataclasses
    "DelegationExpiryRef",
    "DelegationLifecycleBinding",
    "DelegationLifecycleBindingSet",
    "DelegationLifecycleEnvelope",
    "DelegationLifecycleReadinessProfile",
    "DelegationLifecycleSideEffects",
    "DelegationLifecycleStatusReport",
    "DelegationRenewalRef",
    "DelegationRevocationReasonRef",
    "DelegationRevocationRef",
    "DelegationSupersessionRef",
    "DelegationSuspensionRef",
    # P1.8.8 builders / helpers / hash functions
    "build_delegation_expiry_ref",
    "build_delegation_lifecycle_binding",
    "build_delegation_lifecycle_binding_set",
    "build_delegation_lifecycle_envelope",
    "build_delegation_lifecycle_readiness_profile",
    "build_delegation_lifecycle_status_report",
    "build_delegation_renewal_ref",
    "build_delegation_revocation_reason_ref",
    "build_delegation_revocation_ref",
    "build_delegation_supersession_ref",
    "build_delegation_suspension_ref",
    "hash_delegation_expiry_ref",
    "hash_delegation_lifecycle_binding_set",
    "hash_delegation_lifecycle_envelope",
    "hash_delegation_lifecycle_readiness_profile",
    "hash_delegation_renewal_ref",
    "hash_delegation_revocation_reason_ref",
    "hash_delegation_revocation_ref",
    "hash_delegation_supersession_ref",
    "hash_delegation_suspension_ref",
    "serialize_delegation_lifecycle_binding_set",
    "serialize_delegation_lifecycle_envelope",
    # P1.8.9 chain constants
    "ACCEPTANCE_CLAIM_REF_KNOWN_FIELDS",
    "CHAIN_BINDING_KNOWN_FIELDS",
    "CHAIN_BINDING_SET_KNOWN_FIELDS",
    "CHAIN_ENVELOPE_KNOWN_FIELDS",
    "CHAIN_READINESS_PROFILE_KNOWN_FIELDS",
    "CHAIN_REF_KNOWN_FIELDS",
    "CHAIN_SIDE_EFFECTS_KNOWN_FIELDS",
    "CHAIN_STATUS_REPORT_KNOWN_FIELDS",
    "DELEGATION_CHAIN_BINDING_SET_VERSION",
    "DELEGATION_CHAIN_BINDING_VERSION",
    "DELEGATION_CHAIN_CONTINUITY_READINESS_PROFILE_VERSION",
    "DELEGATION_CHAIN_ENVELOPE_VERSION",
    "DELEGATION_CHAIN_REF_VERSION",
    "DELEGATION_CHAIN_SIDE_EFFECTS_VERSION",
    "DELEGATION_CHAIN_STATUS_REPORT_VERSION",
    "DELEGATION_CHAIN_TASK_ID",
    "DELEGATION_CHAIN_UNAVAILABLE_BINDINGS",
    "DELEGATION_HANDOFF_ACCEPTANCE_CLAIM_REF_VERSION",
    "DELEGATION_HANDOFF_CLAIM_REF_VERSION",
    "DELEGATION_HANDOFF_REF_VERSION",
    "DELEGATION_LINEAGE_MAP_VERSION",
    "DELEGATION_PREDECESSOR_REF_VERSION",
    "DELEGATION_RESPONSIBILITY_TRANSFER_CLAIM_REF_VERSION",
    "DELEGATION_SUCCESSOR_REF_VERSION",
    "HANDOFF_CLAIM_REF_KNOWN_FIELDS",
    "HANDOFF_REF_KNOWN_FIELDS",
    "LINEAGE_MAP_KNOWN_FIELDS",
    "PREDECESSOR_REF_KNOWN_FIELDS",
    "SUCCESSOR_REF_KNOWN_FIELDS",
    "TRANSFER_CLAIM_REF_KNOWN_FIELDS",
    # P1.8.9 enums
    "DelegationChainLinkKind",
    "DelegationHandoffKind",
    "DelegationChainReferenceStatus",
    "DelegationChainStatus",
    # P1.8.9 dataclasses
    "DelegationChainRef",
    "DelegationPredecessorRef",
    "DelegationSuccessorRef",
    "DelegationHandoffRef",
    "DelegationHandoffClaimRef",
    "DelegationHandoffAcceptanceClaimRef",
    "DelegationResponsibilityTransferClaimRef",
    "DelegationLineageMap",
    "DelegationChainContinuityReadinessProfile",
    "DelegationChainEnvelope",
    "DelegationChainBinding",
    "DelegationChainBindingSet",
    "DelegationChainSideEffects",
    "DelegationChainStatusReport",
    # P1.8.9 builders / helpers / hash functions
    "build_delegation_chain_ref",
    "build_delegation_predecessor_ref",
    "build_delegation_successor_ref",
    "build_delegation_handoff_ref",
    "build_delegation_handoff_claim_ref",
    "build_delegation_handoff_acceptance_claim_ref",
    "build_delegation_responsibility_transfer_claim_ref",
    "build_delegation_lineage_map",
    "build_delegation_chain_continuity_readiness_profile",
    "build_delegation_chain_envelope",
    "build_delegation_chain_binding",
    "build_delegation_chain_binding_set",
    "build_delegation_chain_status_report",
    "hash_delegation_chain_ref",
    "hash_delegation_predecessor_ref",
    "hash_delegation_successor_ref",
    "hash_delegation_handoff_ref",
    "hash_delegation_handoff_claim_ref",
    "hash_delegation_handoff_acceptance_claim_ref",
    "hash_delegation_responsibility_transfer_claim_ref",
    "hash_delegation_lineage_map",
    "hash_delegation_chain_continuity_readiness_profile",
    "hash_delegation_chain_envelope",
    "hash_delegation_chain_binding",
    "hash_delegation_chain_binding_set",
    "serialize_delegation_chain_envelope",
    "serialize_delegation_chain_binding_set",
    # P1.8.10 shadow resolver constants
    "CONSISTENCY_MATRIX_KNOWN_FIELDS",
    "DELEGATION_CONSISTENCY_FINDING_VERSION",
    "DELEGATION_CONSISTENCY_MATRIX_ENTRY_VERSION",
    "DELEGATION_CONSISTENCY_MATRIX_VERSION",
    "DELEGATION_CONSISTENCY_SNAPSHOT_VERSION",
    "DELEGATION_SHADOW_RESOLVER_INPUT_ENVELOPE_VERSION",
    "DELEGATION_SHADOW_RESOLVER_READINESS_PROFILE_VERSION",
    "DELEGATION_SHADOW_RESOLVER_RESULT_VERSION",
    "DELEGATION_SHADOW_RESOLVER_SIDE_EFFECTS_VERSION",
    "DELEGATION_SHADOW_RESOLVER_STATUS_REPORT_VERSION",
    "DELEGATION_SHADOW_RESOLVER_TASK_ID",
    "DELEGATION_SHADOW_RESOLVER_UNAVAILABLE_BINDINGS",
    "FINDING_KNOWN_FIELDS",
    "INPUT_ENVELOPE_KNOWN_FIELDS",
    "MATRIX_ENTRY_KNOWN_FIELDS",
    "SHADOW_READINESS_PROFILE_KNOWN_FIELDS",
    "SHADOW_RESULT_KNOWN_FIELDS",
    "SHADOW_SIDE_EFFECTS_KNOWN_FIELDS",
    "SNAPSHOT_KNOWN_FIELDS",
    "SHADOW_STATUS_REPORT_KNOWN_FIELDS",
    # P1.8.10 enums
    "DelegationConsistencyFamily",
    "DelegationConsistencyFindingKind",
    "DelegationConsistencySeverity",
    "DelegationShadowResolverMode",
    "DelegationShadowResolverStatus",
    # P1.8.10 dataclasses
    "DelegationConsistencyFinding",
    "DelegationConsistencyMatrix",
    "DelegationConsistencyMatrixEntry",
    "DelegationConsistencySnapshot",
    "DelegationShadowResolverInputEnvelope",
    "DelegationShadowResolverReadinessProfile",
    "DelegationShadowResolverResult",
    "DelegationShadowResolverSideEffects",
    "DelegationShadowResolverStatusReport",
    # P1.8.10 builders / helpers / hash functions / serializers
    "build_delegation_consistency_finding",
    "build_delegation_consistency_matrix",
    "build_delegation_consistency_matrix_entry",
    "build_delegation_consistency_snapshot",
    "build_delegation_shadow_resolver_input_envelope",
    "build_delegation_shadow_resolver_readiness_profile",
    "build_delegation_shadow_resolver_result",
    "build_delegation_shadow_resolver_status_report",
    "hash_delegation_consistency_finding",
    "hash_delegation_consistency_matrix",
    "hash_delegation_consistency_matrix_entry",
    "hash_delegation_consistency_snapshot",
    "hash_delegation_shadow_resolver_input_envelope",
    "hash_delegation_shadow_resolver_readiness_profile",
    "hash_delegation_shadow_resolver_result",
    "hash_delegation_shadow_resolver_status_report",
    "serialize_delegation_consistency_matrix",
    "serialize_delegation_shadow_resolver_input_envelope",
    "serialize_delegation_shadow_resolver_result",
    # P1.8.11 operator review constants
    "APPROVAL_INTENT_REF_KNOWN_FIELDS",
    "DELEGATION_APPROVAL_INTENT_REF_VERSION",
    "DELEGATION_ESCALATION_INTENT_REF_VERSION",
    "DELEGATION_MORE_CONTEXT_INTENT_REF_VERSION",
    "DELEGATION_OPERATOR_REVIEW_BINDING_SET_VERSION",
    "DELEGATION_OPERATOR_REVIEW_BINDING_VERSION",
    "DELEGATION_OPERATOR_REVIEW_ENVELOPE_VERSION",
    "DELEGATION_OPERATOR_REVIEW_READINESS_PROFILE_VERSION",
    "DELEGATION_OPERATOR_REVIEW_REF_VERSION",
    "DELEGATION_OPERATOR_REVIEW_SIDE_EFFECTS_VERSION",
    "DELEGATION_OPERATOR_REVIEW_STATUS_REPORT_VERSION",
    "DELEGATION_OPERATOR_REVIEW_TASK_ID",
    "DELEGATION_OPERATOR_REVIEW_UNAVAILABLE_BINDINGS",
    "DELEGATION_REJECTION_INTENT_REF_VERSION",
    "DELEGATION_REVIEW_RATIONALE_REF_VERSION",
    "ESCALATION_INTENT_REF_KNOWN_FIELDS",
    "MORE_CONTEXT_INTENT_REF_KNOWN_FIELDS",
    "OPERATOR_REVIEW_ENVELOPE_KNOWN_FIELDS",
    "OPERATOR_REVIEW_REF_KNOWN_FIELDS",
    "RATIONALE_REF_KNOWN_FIELDS",
    "REJECTION_INTENT_REF_KNOWN_FIELDS",
    "REVIEW_BINDING_KNOWN_FIELDS",
    "REVIEW_BINDING_SET_KNOWN_FIELDS",
    "REVIEW_READINESS_PROFILE_KNOWN_FIELDS",
    "REVIEW_SIDE_EFFECTS_KNOWN_FIELDS",
    "REVIEW_STATUS_REPORT_KNOWN_FIELDS",
    # P1.8.11 enums
    "DelegationOperatorReviewKind",
    "DelegationOperatorReviewIntentKind",
    "DelegationOperatorReviewReferenceStatus",
    "DelegationOperatorReviewStatus",
    "DelegationReviewRationaleKind",
    # P1.8.11 dataclasses
    "DelegationOperatorReviewRef",
    "DelegationApprovalIntentRef",
    "DelegationRejectionIntentRef",
    "DelegationEscalationIntentRef",
    "DelegationMoreContextIntentRef",
    "DelegationReviewRationaleRef",
    "DelegationOperatorReviewReadinessProfile",
    "DelegationOperatorReviewEnvelope",
    "DelegationOperatorReviewBinding",
    "DelegationOperatorReviewBindingSet",
    "DelegationOperatorReviewSideEffects",
    "DelegationOperatorReviewStatusReport",
    # P1.8.11 builders / helpers / hash functions / serializers
    "build_delegation_operator_review_ref",
    "build_delegation_approval_intent_ref",
    "build_delegation_rejection_intent_ref",
    "build_delegation_escalation_intent_ref",
    "build_delegation_more_context_intent_ref",
    "build_delegation_review_rationale_ref",
    "build_delegation_operator_review_readiness_profile",
    "build_delegation_operator_review_envelope",
    "build_delegation_operator_review_binding",
    "build_delegation_operator_review_binding_set",
    "build_delegation_operator_review_status_report",
    "hash_delegation_operator_review_ref",
    "hash_delegation_approval_intent_ref",
    "hash_delegation_rejection_intent_ref",
    "hash_delegation_escalation_intent_ref",
    "hash_delegation_more_context_intent_ref",
    "hash_delegation_review_rationale_ref",
    "hash_delegation_operator_review_readiness_profile",
    "hash_delegation_operator_review_envelope",
    "hash_delegation_operator_review_binding",
    "hash_delegation_operator_review_binding_set",
    "hash_delegation_operator_review_status_report",
    "serialize_delegation_operator_review_envelope",
    "serialize_delegation_operator_review_binding_set",
    # P1.8.12 policy/Custos bridge constants
    "DELEGATION_CUSTOS_BRIDGE_REF_VERSION",
    "DELEGATION_CUSTOS_CONTEXT_REF_VERSION",
    "DELEGATION_CUSTOS_DECISION_REQUEST_INTENT_REF_VERSION",
    "DELEGATION_CUSTOS_DECISION_RESPONSE_PLACEHOLDER_REF_VERSION",
    "DELEGATION_POLICY_BRIDGE_REF_VERSION",
    "DELEGATION_POLICY_CONTEXT_REF_VERSION",
    "DELEGATION_POLICY_CUSTOS_BRIDGE_BINDING_SET_VERSION",
    "DELEGATION_POLICY_CUSTOS_BRIDGE_BINDING_VERSION",
    "DELEGATION_POLICY_CUSTOS_BRIDGE_ENVELOPE_VERSION",
    "DELEGATION_POLICY_CUSTOS_BRIDGE_READINESS_PROFILE_VERSION",
    "DELEGATION_POLICY_CUSTOS_BRIDGE_SIDE_EFFECTS_VERSION",
    "DELEGATION_POLICY_CUSTOS_BRIDGE_STATUS_REPORT_VERSION",
    "DELEGATION_POLICY_CUSTOS_BRIDGE_TASK_ID",
    "DELEGATION_POLICY_CUSTOS_BRIDGE_UNAVAILABLE_BINDINGS",
    "DELEGATION_POLICY_CUSTOS_COMPATIBILITY_MATRIX_ENTRY_VERSION",
    "DELEGATION_POLICY_CUSTOS_COMPATIBILITY_MATRIX_VERSION",
    "DELEGATION_POLICY_DECISION_REQUEST_INTENT_REF_VERSION",
    "DELEGATION_POLICY_DECISION_RESPONSE_PLACEHOLDER_REF_VERSION",
    # P1.8.12 known fields
    "POLICY_BRIDGE_REF_KNOWN_FIELDS",
    "CUSTOS_BRIDGE_REF_KNOWN_FIELDS",
    "POLICY_CONTEXT_REF_KNOWN_FIELDS",
    "CUSTOS_CONTEXT_REF_KNOWN_FIELDS",
    "POLICY_DECISION_REQUEST_INTENT_REF_KNOWN_FIELDS",
    "CUSTOS_DECISION_REQUEST_INTENT_REF_KNOWN_FIELDS",
    "POLICY_DECISION_RESPONSE_PLACEHOLDER_REF_KNOWN_FIELDS",
    "CUSTOS_DECISION_RESPONSE_PLACEHOLDER_REF_KNOWN_FIELDS",
    "COMPATIBILITY_MATRIX_ENTRY_KNOWN_FIELDS",
    "COMPATIBILITY_MATRIX_PB_KNOWN_FIELDS",
    "BRIDGE_READINESS_PROFILE_KNOWN_FIELDS",
    "BRIDGE_ENVELOPE_KNOWN_FIELDS",
    "BRIDGE_BINDING_KNOWN_FIELDS",
    "BRIDGE_BINDING_SET_KNOWN_FIELDS",
    "BRIDGE_SIDE_EFFECTS_KNOWN_FIELDS",
    "BRIDGE_STATUS_REPORT_KNOWN_FIELDS",
    # P1.8.12 enums
    "DelegationPolicyCustosBridgeKind",
    "DelegationPolicyCustosBridgeReferenceStatus",
    "DelegationPolicyCustosBridgeStatus",
    "DelegationPolicyContextKind",
    "DelegationCustosContextKind",
    "DelegationPolicyCustosCompatibilityFamily",
    # P1.8.12 dataclasses
    "DelegationPolicyBridgeRef",
    "DelegationCustosBridgeRef",
    "DelegationPolicyContextRef",
    "DelegationCustosContextRef",
    "DelegationPolicyDecisionRequestIntentRef",
    "DelegationCustosDecisionRequestIntentRef",
    "DelegationPolicyDecisionResponsePlaceholderRef",
    "DelegationCustosDecisionResponsePlaceholderRef",
    "DelegationPolicyCustosCompatibilityMatrixEntry",
    "DelegationPolicyCustosCompatibilityMatrix",
    "DelegationPolicyCustosBridgeReadinessProfile",
    "DelegationPolicyCustosBridgeEnvelope",
    "DelegationPolicyCustosBridgeBinding",
    "DelegationPolicyCustosBridgeBindingSet",
    "DelegationPolicyCustosBridgeSideEffects",
    "DelegationPolicyCustosBridgeStatusReport",
    # P1.8.12 builders / helpers / hash functions / serializers
    "build_delegation_policy_bridge_ref",
    "build_delegation_custos_bridge_ref",
    "build_delegation_policy_context_ref",
    "build_delegation_custos_context_ref",
    "build_delegation_policy_decision_request_intent_ref",
    "build_delegation_custos_decision_request_intent_ref",
    "build_delegation_policy_decision_response_placeholder_ref",
    "build_delegation_custos_decision_response_placeholder_ref",
    "build_delegation_policy_custos_compatibility_matrix_entry",
    "build_delegation_policy_custos_compatibility_matrix",
    "build_delegation_policy_custos_bridge_readiness_profile",
    "build_delegation_policy_custos_bridge_envelope",
    "build_delegation_policy_custos_bridge_binding",
    "build_delegation_policy_custos_bridge_binding_set",
    "build_delegation_policy_custos_bridge_status_report",
    "hash_delegation_policy_bridge_ref",
    "hash_delegation_custos_bridge_ref",
    "hash_delegation_policy_context_ref",
    "hash_delegation_custos_context_ref",
    "hash_delegation_policy_decision_request_intent_ref",
    "hash_delegation_custos_decision_request_intent_ref",
    "hash_delegation_policy_decision_response_placeholder_ref",
    "hash_delegation_custos_decision_response_placeholder_ref",
    "hash_delegation_policy_custos_compatibility_matrix_entry",
    "hash_delegation_policy_custos_compatibility_matrix",
    "hash_delegation_policy_custos_bridge_readiness_profile",
    "hash_delegation_policy_custos_bridge_envelope",
    "hash_delegation_policy_custos_bridge_binding",
    "hash_delegation_policy_custos_bridge_binding_set",
    "hash_delegation_policy_custos_bridge_status_report",
    "serialize_delegation_policy_custos_bridge_envelope",
    "serialize_delegation_policy_custos_bridge_binding_set",
    # P1.8.13 runtime/execution readiness constants
    "DELEGATION_RUNTIME_EXECUTION_READINESS_BINDING_SET_VERSION",
    "DELEGATION_RUNTIME_EXECUTION_READINESS_BINDING_VERSION",
    "DELEGATION_RUNTIME_EXECUTION_READINESS_ENVELOPE_VERSION",
    "DELEGATION_RUNTIME_EXECUTION_READINESS_MATRIX_ENTRY_VERSION",
    "DELEGATION_RUNTIME_EXECUTION_READINESS_MATRIX_VERSION",
    "DELEGATION_RUNTIME_EXECUTION_READINESS_PROFILE_VERSION",
    "DELEGATION_RUNTIME_EXECUTION_READINESS_SIDE_EFFECTS_VERSION",
    "DELEGATION_RUNTIME_EXECUTION_READINESS_STATUS_REPORT_VERSION",
    "DELEGATION_RUNTIME_EXECUTION_READINESS_TASK_ID",
    "DELEGATION_RUNTIME_EXECUTION_READINESS_UNAVAILABLE_BINDINGS",
    "DELEGATION_EXECUTION_BLOCKER_REF_VERSION",
    "DELEGATION_EXECUTION_PRECONDITION_REF_VERSION",
    "DELEGATION_EXECUTION_TARGET_REF_VERSION",
    "DELEGATION_RUNTIME_ADMISSION_INTENT_REF_VERSION",
    "DELEGATION_RUNTIME_ADMISSION_PLACEHOLDER_REF_VERSION",
    "DELEGATION_RUNTIME_CONTEXT_REF_VERSION",
    "DELEGATION_RUNTIME_READINESS_REF_VERSION",
    "DELEGATION_RUNTIME_SESSION_PLACEHOLDER_REF_VERSION",
    "DELEGATION_TOOL_EXECUTION_CONTEXT_REF_VERSION",
    # P1.8.13 known fields
    "EXECUTION_BLOCKER_REF_KNOWN_FIELDS",
    "EXECUTION_PRECONDITION_REF_KNOWN_FIELDS",
    "EXECUTION_TARGET_REF_KNOWN_FIELDS",
    "READINESS_BINDING_KNOWN_FIELDS",
    "READINESS_BINDING_SET_KNOWN_FIELDS",
    "READINESS_ENVELOPE_KNOWN_FIELDS",
    "READINESS_MATRIX_ENTRY_KNOWN_FIELDS",
    "READINESS_MATRIX_KNOWN_FIELDS",
    "READINESS_READINESS_PROFILE_KNOWN_FIELDS",
    "READINESS_SIDE_EFFECTS_KNOWN_FIELDS",
    "READINESS_STATUS_REPORT_KNOWN_FIELDS",
    "RUNTIME_ADMISSION_INTENT_REF_KNOWN_FIELDS",
    "RUNTIME_ADMISSION_PLACEHOLDER_REF_KNOWN_FIELDS",
    "RUNTIME_CONTEXT_REF_KNOWN_FIELDS",
    "RUNTIME_READINESS_REF_KNOWN_FIELDS",
    "RUNTIME_SESSION_PLACEHOLDER_REF_KNOWN_FIELDS",
    "TOOL_EXECUTION_CONTEXT_REF_KNOWN_FIELDS",
    # P1.8.13 enums
    "DelegationExecutionContextKind",
    "DelegationRuntimeContextKind",
    "DelegationRuntimeExecutionReadinessFamily",
    "DelegationRuntimeExecutionReadinessKind",
    "DelegationRuntimeExecutionReadinessReferenceStatus",
    "DelegationRuntimeExecutionReadinessStatus",
    # P1.8.13 dataclasses
    "DelegationExecutionBlockerRef",
    "DelegationExecutionPreconditionRef",
    "DelegationExecutionTargetRef",
    "DelegationRuntimeAdmissionIntentRef",
    "DelegationRuntimeAdmissionPlaceholderRef",
    "DelegationRuntimeContextRef",
    "DelegationRuntimeExecutionReadinessBinding",
    "DelegationRuntimeExecutionReadinessBindingSet",
    "DelegationRuntimeExecutionReadinessEnvelope",
    "DelegationRuntimeExecutionReadinessMatrix",
    "DelegationRuntimeExecutionReadinessMatrixEntry",
    "DelegationRuntimeExecutionReadinessProfile",
    "DelegationRuntimeExecutionReadinessSideEffects",
    "DelegationRuntimeExecutionReadinessStatusReport",
    "DelegationRuntimeReadinessRef",
    "DelegationRuntimeSessionPlaceholderRef",
    "DelegationToolExecutionContextRef",
    # P1.8.13 builders
    "build_delegation_execution_blocker_ref",
    "build_delegation_execution_precondition_ref",
    "build_delegation_execution_target_ref",
    "build_delegation_runtime_admission_intent_ref",
    "build_delegation_runtime_admission_placeholder_ref",
    "build_delegation_runtime_context_ref",
    "build_delegation_runtime_execution_readiness_binding",
    "build_delegation_runtime_execution_readiness_binding_set",
    "build_delegation_runtime_execution_readiness_envelope",
    "build_delegation_runtime_execution_readiness_matrix",
    "build_delegation_runtime_execution_readiness_matrix_entry",
    "build_delegation_runtime_execution_readiness_profile",
    "build_delegation_runtime_execution_readiness_status_report",
    "build_delegation_runtime_readiness_ref",
    "build_delegation_runtime_session_placeholder_ref",
    "build_delegation_tool_execution_context_ref",
    # P1.8.13 hash functions
    "hash_delegation_execution_blocker_ref",
    "hash_delegation_execution_precondition_ref",
    "hash_delegation_execution_target_ref",
    "hash_delegation_runtime_admission_intent_ref",
    "hash_delegation_runtime_admission_placeholder_ref",
    "hash_delegation_runtime_context_ref",
    "hash_delegation_runtime_execution_readiness_binding",
    "hash_delegation_runtime_execution_readiness_binding_set",
    "hash_delegation_runtime_execution_readiness_envelope",
    "hash_delegation_runtime_execution_readiness_matrix",
    "hash_delegation_runtime_execution_readiness_matrix_entry",
    "hash_delegation_runtime_execution_readiness_profile",
    "hash_delegation_runtime_execution_readiness_status_report",
    "hash_delegation_runtime_readiness_ref",
    "hash_delegation_runtime_session_placeholder_ref",
    "hash_delegation_tool_execution_context_ref",
    # P1.8.13 serializers
    "serialize_delegation_runtime_execution_readiness_binding_set",
    "serialize_delegation_runtime_execution_readiness_envelope",
    # P1.8.14 trace/audit bridge constants
    "DELEGATION_TRACE_AUDIT_BRIDGE_TASK_ID",
    "DELEGATION_TRACE_BRIDGE_REF_VERSION",
    "DELEGATION_AUDIT_BRIDGE_REF_VERSION",
    "DELEGATION_LEDGER_BRIDGE_REF_VERSION",
    "DELEGATION_TRACE_EVENT_INTENT_REF_VERSION",
    "DELEGATION_AUDIT_EVENT_INTENT_REF_VERSION",
    "DELEGATION_LEDGER_ENTRY_PLACEHOLDER_REF_VERSION",
    "DELEGATION_REPLAY_CONTEXT_REF_VERSION",
    "DELEGATION_FORK_CONTEXT_REF_VERSION",
    "DELEGATION_CAUSAL_CHAIN_CONTEXT_REF_VERSION",
    "DELEGATION_TRACE_AUDIT_READINESS_MATRIX_ENTRY_VERSION",
    "DELEGATION_TRACE_AUDIT_READINESS_MATRIX_VERSION",
    "DELEGATION_TRACE_AUDIT_READINESS_PROFILE_VERSION",
    "DELEGATION_TRACE_AUDIT_BRIDGE_ENVELOPE_VERSION",
    "DELEGATION_TRACE_AUDIT_BRIDGE_BINDING_VERSION",
    "DELEGATION_TRACE_AUDIT_BRIDGE_BINDING_SET_VERSION",
    "DELEGATION_TRACE_AUDIT_BRIDGE_SIDE_EFFECTS_VERSION",
    "DELEGATION_TRACE_AUDIT_BRIDGE_STATUS_REPORT_VERSION",
    "DELEGATION_TRACE_AUDIT_BRIDGE_UNAVAILABLE_BINDINGS",
    # P1.8.14 known fields
    "TRACE_BRIDGE_REF_KNOWN_FIELDS",
    "AUDIT_BRIDGE_REF_KNOWN_FIELDS",
    "LEDGER_BRIDGE_REF_KNOWN_FIELDS",
    "TRACE_EVENT_INTENT_REF_KNOWN_FIELDS",
    "AUDIT_EVENT_INTENT_REF_KNOWN_FIELDS",
    "LEDGER_ENTRY_PLACEHOLDER_REF_KNOWN_FIELDS",
    "REPLAY_CONTEXT_REF_KNOWN_FIELDS",
    "FORK_CONTEXT_REF_KNOWN_FIELDS",
    "CAUSAL_CHAIN_CONTEXT_REF_KNOWN_FIELDS",
    "READINESS_MATRIX_ENTRY_KNOWN_FIELDS",
    "READINESS_MATRIX_KNOWN_FIELDS",
    "TRACE_AUDIT_READINESS_PROFILE_KNOWN_FIELDS",
    "BRIDGE_ENVELOPE_KNOWN_FIELDS",
    "BRIDGE_BINDING_KNOWN_FIELDS",
    "BRIDGE_BINDING_SET_KNOWN_FIELDS",
    "BRIDGE_SIDE_EFFECTS_KNOWN_FIELDS",
    "BRIDGE_STATUS_REPORT_KNOWN_FIELDS",
    # P1.8.14 enums
    "DelegationTraceAuditBridgeKind",
    "DelegationTraceAuditBridgeReferenceStatus",
    "DelegationTraceAuditBridgeStatus",
    "DelegationTraceContextKind",
    "DelegationAuditContextKind",
    "DelegationTraceAuditReadinessFamily",
    # P1.8.14 dataclasses
    "DelegationTraceBridgeRef",
    "DelegationAuditBridgeRef",
    "DelegationLedgerBridgeRef",
    "DelegationTraceEventIntentRef",
    "DelegationAuditEventIntentRef",
    "DelegationLedgerEntryPlaceholderRef",
    "DelegationReplayContextRef",
    "DelegationForkContextRef",
    "DelegationCausalChainContextRef",
    "DelegationTraceAuditReadinessMatrixEntry",
    "DelegationTraceAuditReadinessMatrix",
    "DelegationTraceAuditReadinessProfile",
    "DelegationTraceAuditBridgeEnvelope",
    "DelegationTraceAuditBridgeBinding",
    "DelegationTraceAuditBridgeBindingSet",
    "DelegationTraceAuditBridgeSideEffects",
    "DelegationTraceAuditBridgeStatusReport",
    # P1.8.14 builders
    "build_delegation_trace_bridge_ref",
    "build_delegation_audit_bridge_ref",
    "build_delegation_ledger_bridge_ref",
    "build_delegation_trace_event_intent_ref",
    "build_delegation_audit_event_intent_ref",
    "build_delegation_ledger_entry_placeholder_ref",
    "build_delegation_replay_context_ref",
    "build_delegation_fork_context_ref",
    "build_delegation_causal_chain_context_ref",
    "build_delegation_trace_audit_readiness_matrix_entry",
    "build_delegation_trace_audit_readiness_matrix",
    "build_delegation_trace_audit_readiness_profile",
    "build_delegation_trace_audit_bridge_envelope",
    "build_delegation_trace_audit_bridge_binding",
    "build_delegation_trace_audit_bridge_binding_set",
    "build_delegation_trace_audit_bridge_status_report",
    # P1.8.14 hash functions
    "hash_delegation_trace_bridge_ref",
    "hash_delegation_audit_bridge_ref",
    "hash_delegation_ledger_bridge_ref",
    "hash_delegation_trace_event_intent_ref",
    "hash_delegation_audit_event_intent_ref",
    "hash_delegation_ledger_entry_placeholder_ref",
    "hash_delegation_replay_context_ref",
    "hash_delegation_fork_context_ref",
    "hash_delegation_causal_chain_context_ref",
    "hash_delegation_trace_audit_readiness_matrix_entry",
    "hash_delegation_trace_audit_readiness_matrix",
    "hash_delegation_trace_audit_readiness_profile",
    "hash_delegation_trace_audit_bridge_envelope",
    "hash_delegation_trace_audit_bridge_binding",
    "hash_delegation_trace_audit_bridge_binding_set",
    "hash_delegation_trace_audit_bridge_status_report",
    # P1.8.14 serializers
    "serialize_delegation_trace_audit_bridge_envelope",
    "serialize_delegation_trace_audit_bridge_binding_set",
]
