"""Delegation / Non-Repudiation / Agent Identity Mesh Foundation (P1.8.0).

Foundation-only package: typed delegation records, reference-only evidence hooks,
identity mesh references, deterministic serialization, and honest capability reporting.
P1.8.0 does not authorize, enforce, verify, execute, or write trace/Ledger.

Architectural law:
  - DelegationRecord is not permission.
  - AuthorityRef is not granted authority.
  - NonRepudiationRef is not verified proof.
  - AgentIdentityMeshRef is not live mesh activation.
"""
from __future__ import annotations

from .foundation import (
    ACTOR_REF_KNOWN_FIELDS,
    AUTHORITY_REF_KNOWN_FIELDS,
    CONSTRAINT_KNOWN_FIELDS,
    DELEGATION_FOUNDATION_STATUS_VERSION,
    DELEGATION_MODULE_NAME,
    DELEGATION_SCHEMA_VERSION,
    DELEGATION_TASK_ID,
    DELEGATION_UNAVAILABLE_BINDINGS,
    FOUNDATION_STATUS_KNOWN_FIELDS,
    IDENTITY_MESH_REF_KNOWN_FIELDS,
    NON_REPUDIATION_REF_KNOWN_FIELDS,
    RECORD_KNOWN_FIELDS,
    SIDE_EFFECTS_KNOWN_FIELDS,
    SUBJECT_KNOWN_FIELDS,
    AgentIdentityMeshRef,
    DelegationActorKind,
    DelegationActorRef,
    DelegationAuthorityKind,
    DelegationAuthorityRef,
    DelegationConstraint,
    DelegationConstraintKind,
    DelegationError,
    DelegationErrorCode,
    DelegationFoundationCapability,
    DelegationFoundationStatus,
    DelegationRecord,
    DelegationSerializationError,
    DelegationSideEffects,
    DelegationSourceLabel,
    DelegationStructuredError,
    DelegationSubject,
    DelegationSubjectKind,
    DelegationUnknownFieldError,
    DelegationValidationError,
    NonRepudiationProofStatus,
    NonRepudiationRef,
    build_agent_identity_mesh_ref,
    build_delegation_actor_ref,
    build_delegation_authority_ref,
    build_delegation_constraint,
    build_delegation_foundation_status,
    build_delegation_record,
    build_delegation_subject,
    build_non_repudiation_ref,
    hash_delegation_record,
    serialize_delegation_record,
    stable_hash,
    to_canonical_dict,
    to_canonical_json,
    validate_known_fields,
)

__all__ = [
    "ACTOR_REF_KNOWN_FIELDS",
    "AUTHORITY_REF_KNOWN_FIELDS",
    "AgentIdentityMeshRef",
    "CONSTRAINT_KNOWN_FIELDS",
    "DELEGATION_FOUNDATION_STATUS_VERSION",
    "DELEGATION_MODULE_NAME",
    "DELEGATION_SCHEMA_VERSION",
    "DELEGATION_TASK_ID",
    "DELEGATION_UNAVAILABLE_BINDINGS",
    "DelegationActorKind",
    "DelegationActorRef",
    "DelegationAuthorityKind",
    "DelegationAuthorityRef",
    "DelegationConstraint",
    "DelegationConstraintKind",
    "DelegationError",
    "DelegationErrorCode",
    "DelegationFoundationCapability",
    "DelegationFoundationStatus",
    "DelegationRecord",
    "DelegationSerializationError",
    "DelegationSideEffects",
    "DelegationSourceLabel",
    "DelegationStructuredError",
    "DelegationSubject",
    "DelegationSubjectKind",
    "DelegationUnknownFieldError",
    "DelegationValidationError",
    "FOUNDATION_STATUS_KNOWN_FIELDS",
    "IDENTITY_MESH_REF_KNOWN_FIELDS",
    "NON_REPUDIATION_REF_KNOWN_FIELDS",
    "NonRepudiationProofStatus",
    "NonRepudiationRef",
    "RECORD_KNOWN_FIELDS",
    "SIDE_EFFECTS_KNOWN_FIELDS",
    "SUBJECT_KNOWN_FIELDS",
    "build_agent_identity_mesh_ref",
    "build_delegation_actor_ref",
    "build_delegation_authority_ref",
    "build_delegation_constraint",
    "build_delegation_foundation_status",
    "build_delegation_record",
    "build_delegation_subject",
    "build_non_repudiation_ref",
    "hash_delegation_record",
    "serialize_delegation_record",
    "stable_hash",
    "to_canonical_dict",
    "to_canonical_json",
    "validate_known_fields",
]
