"""AurelTrace Spine — P5-TRACE-A foundation.

P5-TRACE-A is an adapter and structured hash-verification foundation *over* the
existing trace implementation (``agentic_runtime.trace`` +
``agentic_runtime.core_types`` records). It does not replace ``trace.py``, does
not create a second trace source of truth, does not execute, does not authorize,
and does not implement replay, Shell UI, an API server, an event bus, P9
enforcement, or any Rust/WASM substrate.

Law: Runtime emits. Trace canonicalizes. P5 verifies. Projections derive.
Custos authorizes. Operator decides.
"""

from __future__ import annotations

from .evidence_ref import (
    EvidenceKind,
    EvidenceRef,
    EvidenceStatus,
    TraceBindingCoverageStatus,
    evidence_ref_has_no_authority,
    make_evidence_ref,
    make_missing_evidence_ref,
)
from .golden_thread import (
    CausalEdgeKind,
    CausalGraphEdge,
    CausalGraphNode,
    CausalNodeKind,
    GoldenThreadGraph,
    GoldenThreadRef,
    GoldenThreadSegment,
    build_causal_graph,
    build_golden_thread_ref,
    build_golden_thread_segment,
)
from .replay_readiness import (
    REPLAY_UNAVAILABLE_REASON,
    ReplayReadinessAssessment,
    ReplayReadinessStatus,
    TraceTimeSliceRef,
    assess_replay_readiness,
    build_trace_time_slice_ref,
)
from .trace_projection_feed import (
    ProjectionFeedSummary,
    TraceProjectionFeed,
    TraceProjectionFeedEntry,
    build_trace_projection_feed,
    build_trace_projection_feed_entry,
    summarize_projection_feed,
)
from .p3_binding import (
    P3_DOMAIN,
    P3SourceObjectKind,
    P3TraceBinding,
    build_p3_trace_binding,
    make_p3_evidence_ref,
)
from .p4_binding import (
    P4_DOMAIN,
    P4SourceObjectKind,
    P4TraceBinding,
    build_p4_trace_binding,
    make_p4_evidence_ref,
)
from .runtime_submit_bridge import (
    RUNTIME_SUBMIT_DOMAIN,
    RuntimeSubmitTraceBinding,
    RuntimeSubmitTraceBridge,
    TraceBindingCoverageSummary,
    binding_from_submit_coverage_report,
    build_runtime_submit_trace_binding,
    missing_evidence_from_coverage_report,
    runtime_submit_binding_status,
    summarize_binding_coverage,
)
from .trace_doctrine import (
    AUREL_TRACE_DOCTRINE_ID,
    AurelTraceDoctrine,
    build_aurel_trace_doctrine,
)
from .trace_query import (
    TraceAuditSummary,
    TraceBindingSummary,
    TraceEvidenceSummary,
    TraceEventSummary,
    TraceQueryReadModel,
    TraceRunSummary,
    TraceVerificationSummary,
)
from .trace_resolver import (
    TraceVerificationDecision,
    TraceVerificationStatus as TraceResolverStatus,
    TraceVerificationTargetKind,
    TraceVerifiedResolver,
    resolve_chain_head,
    resolve_evidence_set,
    resolve_p3_binding,
    resolve_p4_binding,
    resolve_runtime_submit_binding,
    resolve_trace_event,
    resolve_trace_run,
    resolve_trace_target,
)
from .trace_envelope import (
    SUPPORTED_RECORD_EVENT_KINDS,
    CanonicalTraceEventEnvelope,
    EnvelopeAdaptationResult,
    TraceEnvelopeUnsupportedError,
    canonical_envelope_from_existing_record,
    envelopes_from_ledger,
    is_supported_record,
    trace_run_ref_from_ledger,
    try_canonical_envelope,
)
from .trace_hash import (
    AUREL_TRACE_CONTRACT_VERSION,
    CANONICAL_ENVELOPE_SCHEMA_VERSION,
    GENESIS_ENTRY_HASH,
    AurelTraceError,
    TraceHashMaterial,
    TraceIntegrityStatus,
    TraceTruthLabel,
    canonical_event_hash_material,
    canonical_event_id_from_hash_material,
    canonical_payload_hash,
    canonical_trace_json,
    recompute_entry_hash,
    trace_sha,
)
from .trace_inventory import (
    EXISTING_TRACE_INVENTORY_ID,
    ExistingTraceInventory,
    build_existing_trace_inventory,
)
from .trace_receipts import (
    TraceChainHeadReceipt,
    TraceCheckpointReceipt,
    TraceVerificationReceipt,
    VerifiedTraceRange,
    build_trace_chain_head_receipt,
    build_trace_checkpoint_receipt,
    build_trace_verification_receipt,
    build_verified_trace_range,
)
from .trace_refs import (
    TraceBindingRef,
    TraceEntryRef,
    TraceEventRef,
    TraceRunRef,
    build_trace_binding_ref,
    build_trace_entry_ref,
    build_trace_event_ref,
    build_trace_run_ref,
)
from .trace_schema import (
    AUREL_TRACE_LOG_SCHEMA_VERSION,
    DEFAULT_TRACE_SCHEMA_VERSION,
    TRACE_SCHEMA_REGISTRY_ID,
    TraceEventUpcasterContract,
    TraceSchemaCompatibility,
    TraceSchemaCompatibilityDecision,
    TraceSchemaDescriptor,
    TraceSchemaRegistry,
    TraceSchemaStatus,
    TraceUpcasterStatus,
    build_default_trace_schema_registry,
)
from .submit_coverage import (
    SUBMIT_TRACE_COVERAGE_AUDIT_ID,
    SUBMIT_TRACE_COVERAGE_REPORT_ID,
    SubmitCoverageStatus,
    SubmitEvidenceCoverageSummary,
    SubmitEvidenceRequirement,
    SubmitEvidenceRequirementKind,
    SubmitTraceCoverageAudit,
    SubmitTraceCoverageReport,
    SubmitTraceGap,
    build_submit_trace_coverage_audit,
    build_submit_trace_coverage_report,
)
from .trace_verify import (
    HashChainVerificationSummary,
    TraceFindingSeverity,
    TraceHashFinding,
    TraceHashFindingKind,
    TraceHashVerificationRequest,
    TraceHashVerificationResult,
    TraceVerificationScope,
    TraceVerificationStatus,
    verify_canonical_trace_hash_chain,
    verify_trace_records,
)

__all__ = [
    "AUREL_TRACE_CONTRACT_VERSION",
    "AUREL_TRACE_DOCTRINE_ID",
    "AUREL_TRACE_LOG_SCHEMA_VERSION",
    "CANONICAL_ENVELOPE_SCHEMA_VERSION",
    "DEFAULT_TRACE_SCHEMA_VERSION",
    "EXISTING_TRACE_INVENTORY_ID",
    "GENESIS_ENTRY_HASH",
    "P3_DOMAIN",
    "P4_DOMAIN",
    "RUNTIME_SUBMIT_DOMAIN",
    "SUBMIT_TRACE_COVERAGE_AUDIT_ID",
    "SUBMIT_TRACE_COVERAGE_REPORT_ID",
    "SUPPORTED_RECORD_EVENT_KINDS",
    "TRACE_SCHEMA_REGISTRY_ID",
    "REPLAY_UNAVAILABLE_REASON",
    "AurelTraceDoctrine",
    "AurelTraceError",
    "CanonicalTraceEventEnvelope",
    "CausalEdgeKind",
    "CausalGraphEdge",
    "CausalGraphNode",
    "CausalNodeKind",
    "EnvelopeAdaptationResult",
    "EvidenceKind",
    "EvidenceRef",
    "EvidenceStatus",
    "ExistingTraceInventory",
    "GoldenThreadGraph",
    "GoldenThreadRef",
    "GoldenThreadSegment",
    "HashChainVerificationSummary",
    "ProjectionFeedSummary",
    "ReplayReadinessAssessment",
    "ReplayReadinessStatus",
    "P3SourceObjectKind",
    "P3TraceBinding",
    "P4SourceObjectKind",
    "P4TraceBinding",
    "RuntimeSubmitTraceBinding",
    "RuntimeSubmitTraceBridge",
    "SubmitCoverageStatus",
    "SubmitEvidenceCoverageSummary",
    "SubmitEvidenceRequirement",
    "SubmitEvidenceRequirementKind",
    "SubmitTraceCoverageAudit",
    "SubmitTraceCoverageReport",
    "SubmitTraceGap",
    "TraceAuditSummary",
    "TraceBindingCoverageStatus",
    "TraceBindingCoverageSummary",
    "TraceBindingRef",
    "TraceBindingSummary",
    "TraceChainHeadReceipt",
    "TraceCheckpointReceipt",
    "TraceEntryRef",
    "TraceEnvelopeUnsupportedError",
    "TraceEventRef",
    "TraceEventSummary",
    "TraceEventUpcasterContract",
    "TraceEvidenceSummary",
    "TraceFindingSeverity",
    "TraceHashFinding",
    "TraceHashFindingKind",
    "TraceHashMaterial",
    "TraceHashVerificationRequest",
    "TraceHashVerificationResult",
    "TraceIntegrityStatus",
    "TraceProjectionFeed",
    "TraceProjectionFeedEntry",
    "TraceQueryReadModel",
    "TraceResolverStatus",
    "TraceRunRef",
    "TraceRunSummary",
    "TraceSchemaCompatibility",
    "TraceSchemaCompatibilityDecision",
    "TraceSchemaDescriptor",
    "TraceSchemaRegistry",
    "TraceSchemaStatus",
    "TraceTimeSliceRef",
    "TraceTruthLabel",
    "TraceUpcasterStatus",
    "TraceVerificationDecision",
    "TraceVerificationReceipt",
    "TraceVerificationScope",
    "TraceVerificationStatus",
    "TraceVerificationSummary",
    "TraceVerificationTargetKind",
    "TraceVerifiedResolver",
    "VerifiedTraceRange",
    "assess_replay_readiness",
    "binding_from_submit_coverage_report",
    "build_aurel_trace_doctrine",
    "build_causal_graph",
    "build_default_trace_schema_registry",
    "build_existing_trace_inventory",
    "build_golden_thread_ref",
    "build_golden_thread_segment",
    "build_p3_trace_binding",
    "build_p4_trace_binding",
    "build_runtime_submit_trace_binding",
    "build_submit_trace_coverage_audit",
    "build_submit_trace_coverage_report",
    "build_trace_binding_ref",
    "build_trace_chain_head_receipt",
    "build_trace_checkpoint_receipt",
    "build_trace_entry_ref",
    "build_trace_event_ref",
    "build_trace_projection_feed",
    "build_trace_projection_feed_entry",
    "build_trace_run_ref",
    "build_trace_time_slice_ref",
    "build_trace_verification_receipt",
    "build_verified_trace_range",
    "canonical_envelope_from_existing_record",
    "canonical_event_hash_material",
    "canonical_event_id_from_hash_material",
    "canonical_payload_hash",
    "canonical_trace_json",
    "envelopes_from_ledger",
    "evidence_ref_has_no_authority",
    "is_supported_record",
    "make_evidence_ref",
    "make_missing_evidence_ref",
    "make_p3_evidence_ref",
    "make_p4_evidence_ref",
    "missing_evidence_from_coverage_report",
    "recompute_entry_hash",
    "resolve_chain_head",
    "resolve_evidence_set",
    "resolve_p3_binding",
    "resolve_p4_binding",
    "resolve_runtime_submit_binding",
    "resolve_trace_event",
    "resolve_trace_run",
    "resolve_trace_target",
    "runtime_submit_binding_status",
    "summarize_binding_coverage",
    "summarize_projection_feed",
    "trace_run_ref_from_ledger",
    "trace_sha",
    "try_canonical_envelope",
    "verify_canonical_trace_hash_chain",
    "verify_trace_records",
]
