"""Path Governance & Source Trust Foundation (P1.7.0).

Foundation-only package: labels, posture vocabulary, closed-world validation,
deterministic serialization, and honest capability reporting.
P1.7.1 adds deterministic path identity schema objects without enforcement.
P1.7.2 adds deterministic source identity schema objects without trust resolution.
P1.7.3 adds deterministic source trust label taxonomy objects without resolver behavior.
P1.7.4 adds deterministic trusted root registry seed objects without authority resolution.
P1.7.5 adds deterministic path normalization and shadow escape candidate detection.
P1.7.6 adds deterministic path authority scope declaration objects without resolver behavior.
P1.7.7 adds deterministic untrusted content boundary declaration objects without filtering or enforcement.
P1.7.8 adds deterministic source provenance and evidence binding seed objects without truth verification or trace/Ledger writes.

Architectural law:
  - Projection source labels describe operator-visible truth.
  - Source trust labels describe content origin/trust — a separate axis.
  - P1.7.0 does not resolve paths, enforce governance, bind CLI, or write Ledger.
"""
from __future__ import annotations

from .errors import (
    PathGovernanceError,
    PathGovernanceErrorCode,
    PathGovernanceSerializationError,
    PathGovernanceStructuredError,
    PathGovernanceUnknownFieldError,
    PathGovernanceValidationError,
)
from .foundation import (
    PATH_GOVERNANCE_UNAVAILABLE_REASONS,
    get_path_governance_foundation_status,
)
from .labels import ProjectionSourceLabel, SourceTrustLabel
from .canonical_path import (
    TRAVERSAL_WARNING,
    normalize_path_string,
    path_normalization_warnings,
)
from .path_identity import (
    CANONICAL_PATH_REF_KNOWN_FIELDS,
    PATH_IDENTITY_KNOWN_FIELDS,
    PATH_IDENTITY_SCHEMA_VERSION,
    PATH_IDENTITY_TASK_ID,
    PATH_REF_KNOWN_FIELDS,
    CanonicalPathRef,
    CanonicalizationStatus,
    PathIdentity,
    PathKind,
    PathRef,
    PathSensitivity,
    build_path_identity,
)
from .source_identity import (
    SOURCE_IDENTITY_KNOWN_FIELDS,
    SOURCE_IDENTITY_SCHEMA_VERSION,
    SOURCE_IDENTITY_TASK_ID,
    SOURCE_LINEAGE_REF_KNOWN_FIELDS,
    SOURCE_REF_KNOWN_FIELDS,
    SourceIdentity,
    SourceKind,
    SourceLineageRef,
    SourceLineageRelationship,
    SourceOrigin,
    SourceRef,
    build_source_identity,
    compute_lineage_hash,
    compute_source_id,
)
from .source_trust_taxonomy import (
    SOURCE_TRUST_TAXONOMY_KNOWN_FIELDS,
    SOURCE_TRUST_TAXONOMY_TASK_ID,
    SOURCE_TRUST_TAXONOMY_VERSION,
    TRUST_LABEL_DEFINITION_KNOWN_FIELDS,
    SourceTrustTaxonomy,
    TrustLabelDefinition,
    TrustPosture,
    build_source_trust_taxonomy,
    compute_definition_hash,
    compute_taxonomy_hash,
)
from .path_normalization import (
    PATH_NORMALIZATION_RESULT_KNOWN_FIELDS,
    PATH_NORMALIZATION_TASK_ID,
    PATH_NORMALIZATION_VERSION,
    PathEscapeSignal,
    PathNormalizationResult,
    PathNormalizationStatus,
    normalize_path_for_governance,
)
from .escape_detection import (
    ESCAPE_DETECTION_CONTRACT_KNOWN_FIELDS,
    PATH_BOUNDARY_CHECK_RESULT_KNOWN_FIELDS,
    PATH_ESCAPE_DETECTION_TASK_ID,
    PATH_ESCAPE_DETECTION_VERSION,
    EscapeDetectionContract,
    PathBoundaryCheckResult,
    PathBoundaryStatus,
    detect_path_escape_candidates,
)
from .path_authority_scope import (
    PATH_AUTHORITY_CONSTRAINT_KNOWN_FIELDS,
    PATH_AUTHORITY_SCOPE_KNOWN_FIELDS,
    PATH_AUTHORITY_SCOPE_REGISTRY_KNOWN_FIELDS,
    PATH_AUTHORITY_SCOPE_REGISTRY_VERSION,
    PATH_AUTHORITY_SCOPE_TASK_ID,
    PATH_AUTHORITY_SCOPE_VERSION,
    PATH_AUTHORITY_SUBJECT_KNOWN_FIELDS,
    PathAuthorityBasis,
    PathAuthorityConstraint,
    PathAuthorityConstraintKind,
    PathAuthorityScope,
    PathAuthorityScopeRegistry,
    PathAuthoritySubject,
    PathAuthoritySubjectKind,
    build_path_authority_scope,
    build_path_authority_scope_registry,
    compute_authority_scope_registry_hash,
    compute_constraint_id,
    compute_scope_hash,
    compute_scope_id,
    compute_subject_id,
)
from .source_provenance import (
    PROVENANCE_BINDING_KNOWN_FIELDS,
    PROVENANCE_BINDING_REGISTRY_KNOWN_FIELDS,
    SOURCE_CLAIM_REF_KNOWN_FIELDS,
    SOURCE_EVIDENCE_REF_KNOWN_FIELDS,
    SOURCE_PROVENANCE_BINDING_REGISTRY_VERSION,
    SOURCE_PROVENANCE_BINDING_VERSION,
    SOURCE_PROVENANCE_REF_KNOWN_FIELDS,
    SOURCE_PROVENANCE_TASK_ID,
    EvidenceBindingKind,
    EvidenceConfidence,
    ProvenanceBinding,
    ProvenanceBindingRegistry,
    SourceClaimKind,
    SourceClaimRef,
    SourceEvidenceRef,
    SourceProvenanceKind,
    SourceProvenanceRef,
    build_provenance_binding,
    build_provenance_binding_registry,
    build_source_claim_ref,
    build_source_evidence_ref,
    build_source_provenance_ref,
    compute_binding_hash,
    compute_binding_id,
    compute_claim_hash,
    compute_claim_id,
    compute_evidence_hash,
    compute_evidence_id,
    compute_provenance_binding_registry_hash,
    compute_provenance_hash,
    compute_provenance_id,
)
from .untrusted_content_boundary import (
    BOUNDARY_RESTRICTION_KNOWN_FIELDS,
    UNTRUSTED_CONTENT_BOUNDARY_KNOWN_FIELDS,
    UNTRUSTED_CONTENT_BOUNDARY_REGISTRY_KNOWN_FIELDS,
    UNTRUSTED_CONTENT_BOUNDARY_REGISTRY_VERSION,
    UNTRUSTED_CONTENT_BOUNDARY_TASK_ID,
    UNTRUSTED_CONTENT_BOUNDARY_VERSION,
    BoundaryRestriction,
    BoundaryRestrictionKind,
    ContentInfluenceSurface,
    UntrustedBoundaryPosture,
    UntrustedContentBoundary,
    UntrustedContentBoundaryRegistry,
    UntrustedContentKind,
    build_untrusted_content_boundary,
    build_untrusted_content_boundary_registry,
    compute_boundary_hash,
    compute_boundary_id,
    compute_restriction_id,
    compute_untrusted_boundary_registry_hash,
    default_influence_surfaces_for_trust_label,
    default_posture_for_trust_label,
    default_restrictions_for_trust_label,
)
from .trusted_roots import (
    PATH_SCOPE_DENY_KNOWN_FIELDS,
    PATH_SCOPE_GRANT_KNOWN_FIELDS,
    TRUSTED_ROOT_KNOWN_FIELDS,
    TRUSTED_ROOT_REGISTRY_KNOWN_FIELDS,
    TRUSTED_ROOT_REGISTRY_TASK_ID,
    TRUSTED_ROOT_REGISTRY_VERSION,
    PathScopeAction,
    PathScopeDeny,
    PathScopeGrant,
    PathScopeReason,
    TrustedRoot,
    TrustedRootKind,
    TrustedRootRegistry,
    build_trusted_root_registry,
    compute_deny_id,
    compute_grant_id,
    compute_registry_hash,
    compute_root_id,
)
from .serialization import stable_hash, to_canonical_dict, to_canonical_json
from .types import (
    CAPABILITY_STATUS_KNOWN_FIELDS,
    PATH_GOVERNANCE_MODULE_NAME,
    PATH_GOVERNANCE_MODULE_VERSION,
    PATH_GOVERNANCE_TASK_ID,
    FoundationPosture,
    PathGovernanceCapabilityStatus,
)
from .validation import validate_known_fields

__all__ = [
    "CAPABILITY_STATUS_KNOWN_FIELDS",
    "BOUNDARY_RESTRICTION_KNOWN_FIELDS",
    "EvidenceBindingKind",
    "EvidenceConfidence",
    "FoundationPosture",
    "CANONICAL_PATH_REF_KNOWN_FIELDS",
    "PATH_GOVERNANCE_MODULE_NAME",
    "PATH_GOVERNANCE_MODULE_VERSION",
    "PATH_GOVERNANCE_TASK_ID",
    "ESCAPE_DETECTION_CONTRACT_KNOWN_FIELDS",
    "PATH_AUTHORITY_CONSTRAINT_KNOWN_FIELDS",
    "PATH_AUTHORITY_SCOPE_KNOWN_FIELDS",
    "PATH_AUTHORITY_SCOPE_REGISTRY_KNOWN_FIELDS",
    "PATH_AUTHORITY_SCOPE_REGISTRY_VERSION",
    "PATH_AUTHORITY_SCOPE_TASK_ID",
    "PATH_AUTHORITY_SCOPE_VERSION",
    "PATH_AUTHORITY_SUBJECT_KNOWN_FIELDS",
    "PATH_BOUNDARY_CHECK_RESULT_KNOWN_FIELDS",
    "PATH_ESCAPE_DETECTION_TASK_ID",
    "PATH_ESCAPE_DETECTION_VERSION",
    "PATH_GOVERNANCE_UNAVAILABLE_REASONS",
    "PATH_NORMALIZATION_RESULT_KNOWN_FIELDS",
    "PATH_NORMALIZATION_TASK_ID",
    "PATH_NORMALIZATION_VERSION",
    "PATH_IDENTITY_KNOWN_FIELDS",
    "PATH_IDENTITY_SCHEMA_VERSION",
    "PATH_IDENTITY_TASK_ID",
    "PATH_SCOPE_DENY_KNOWN_FIELDS",
    "PATH_SCOPE_GRANT_KNOWN_FIELDS",
    "PATH_REF_KNOWN_FIELDS",
    "SOURCE_IDENTITY_KNOWN_FIELDS",
    "SOURCE_IDENTITY_SCHEMA_VERSION",
    "SOURCE_IDENTITY_TASK_ID",
    "SOURCE_LINEAGE_REF_KNOWN_FIELDS",
    "SOURCE_REF_KNOWN_FIELDS",
    "SOURCE_TRUST_TAXONOMY_KNOWN_FIELDS",
    "SOURCE_TRUST_TAXONOMY_TASK_ID",
    "SOURCE_TRUST_TAXONOMY_VERSION",
    "TRUST_LABEL_DEFINITION_KNOWN_FIELDS",
    "TRUSTED_ROOT_KNOWN_FIELDS",
    "TRUSTED_ROOT_REGISTRY_KNOWN_FIELDS",
    "TRUSTED_ROOT_REGISTRY_TASK_ID",
    "TRUSTED_ROOT_REGISTRY_VERSION",
    "UNTRUSTED_CONTENT_BOUNDARY_KNOWN_FIELDS",
    "UNTRUSTED_CONTENT_BOUNDARY_REGISTRY_KNOWN_FIELDS",
    "UNTRUSTED_CONTENT_BOUNDARY_REGISTRY_VERSION",
    "UNTRUSTED_CONTENT_BOUNDARY_TASK_ID",
    "UNTRUSTED_CONTENT_BOUNDARY_VERSION",
    "UntrustedBoundaryPosture",
    "UntrustedContentBoundary",
    "UntrustedContentBoundaryRegistry",
    "UntrustedContentKind",
    "ContentInfluenceSurface",
    "EscapeDetectionContract",
    "BoundaryRestriction",
    "BoundaryRestrictionKind",
    "CanonicalPathRef",
    "CanonicalizationStatus",
    "PathAuthorityBasis",
    "PathAuthorityConstraint",
    "PathAuthorityConstraintKind",
    "PathAuthorityScope",
    "PathAuthorityScopeRegistry",
    "PathAuthoritySubject",
    "PathAuthoritySubjectKind",
    "PathBoundaryCheckResult",
    "PathBoundaryStatus",
    "PathEscapeSignal",
    "PathGovernanceCapabilityStatus",
    "PathNormalizationResult",
    "PathNormalizationStatus",
    "PathGovernanceError",
    "PathGovernanceErrorCode",
    "PathGovernanceSerializationError",
    "PathGovernanceStructuredError",
    "PathGovernanceUnknownFieldError",
    "PathGovernanceValidationError",
    "PathIdentity",
    "PathKind",
    "PathRef",
    "PathSensitivity",
    "PathScopeAction",
    "PathScopeDeny",
    "PathScopeGrant",
    "PathScopeReason",
    "PROVENANCE_BINDING_KNOWN_FIELDS",
    "PROVENANCE_BINDING_REGISTRY_KNOWN_FIELDS",
    "SOURCE_CLAIM_REF_KNOWN_FIELDS",
    "SOURCE_EVIDENCE_REF_KNOWN_FIELDS",
    "SOURCE_PROVENANCE_BINDING_REGISTRY_VERSION",
    "SOURCE_PROVENANCE_BINDING_VERSION",
    "SOURCE_PROVENANCE_REF_KNOWN_FIELDS",
    "SOURCE_PROVENANCE_TASK_ID",
    "ProvenanceBinding",
    "ProvenanceBindingRegistry",
    "SourceClaimKind",
    "SourceClaimRef",
    "SourceEvidenceRef",
    "SourceProvenanceKind",
    "SourceProvenanceRef",
    "build_provenance_binding",
    "build_provenance_binding_registry",
    "build_source_claim_ref",
    "build_source_evidence_ref",
    "build_source_provenance_ref",
    "compute_binding_hash",
    "compute_binding_id",
    "compute_claim_hash",
    "compute_claim_id",
    "compute_evidence_hash",
    "compute_evidence_id",
    "compute_provenance_binding_registry_hash",
    "compute_provenance_hash",
    "compute_provenance_id",
    "ProjectionSourceLabel",
    "SourceIdentity",
    "SourceKind",
    "SourceLineageRef",
    "SourceLineageRelationship",
    "SourceOrigin",
    "SourceRef",
    "SourceTrustLabel",
    "SourceTrustTaxonomy",
    "TrustLabelDefinition",
    "TrustPosture",
    "TrustedRoot",
    "TrustedRootKind",
    "TrustedRootRegistry",
    "TRAVERSAL_WARNING",
    "build_untrusted_content_boundary",
    "build_untrusted_content_boundary_registry",
    "build_path_authority_scope",
    "build_path_authority_scope_registry",
    "build_path_identity",
    "detect_path_escape_candidates",
    "build_source_identity",
    "build_source_trust_taxonomy",
    "build_trusted_root_registry",
    "compute_boundary_hash",
    "compute_boundary_id",
    "compute_restriction_id",
    "compute_untrusted_boundary_registry_hash",
    "default_influence_surfaces_for_trust_label",
    "default_posture_for_trust_label",
    "default_restrictions_for_trust_label",
    "compute_authority_scope_registry_hash",
    "compute_constraint_id",
    "compute_definition_hash",
    "compute_scope_hash",
    "compute_scope_id",
    "compute_subject_id",
    "compute_deny_id",
    "compute_grant_id",
    "compute_lineage_hash",
    "compute_registry_hash",
    "compute_root_id",
    "compute_source_id",
    "compute_taxonomy_hash",
    "get_path_governance_foundation_status",
    "normalize_path_for_governance",
    "normalize_path_string",
    "path_normalization_warnings",
    "stable_hash",
    "to_canonical_dict",
    "to_canonical_json",
    "validate_known_fields",
]
