"""Identity layer (P1.4.0–P1.4.7).

Architectural law:
  - Identity is not policy.
  - Persona is not authority.
  - Operator Contract is not autonomy.
  - Communication Mode is not permission.
  - Self-Model is not authority or capability verification.
  - Agent Identity Card proves who acts; it does not grant authority.
  - Competence may evolve; sovereignty relation to Operator does not.
"""
from __future__ import annotations

from .authority_relation import build_authority_relation
from .communication_modes import (
    COMMUNICATION_MODES_VALIDATOR_VERSION,
    REQUIRED_MODES,
    AurelCommunicationModeRegistry,
    CommunicationModeAttestation,
    CommunicationModeError,
    CommunicationModeGlobalBoundaries,
    CommunicationModeInvariant,
    CommunicationModeLookupResult,
    CommunicationModeRegistryHash,
    CommunicationModeSafeSummary,
    CommunicationModeSpec,
    CommunicationModeValidationResult,
    default_communication_modes_path,
    load_communication_mode_registry,
    parse_communication_modes_document,
)
from .mode_hash import (
    compute_communication_mode_registry_hash,
    registry_to_canonical_dict,
)
from .mode_registry import get_communication_mode
from .mode_summary import (
    build_communication_mode_safe_summary,
    communication_mode_safe_summary_to_dict,
)
from .mode_validation import (
    build_communication_mode_attestation,
    validate_communication_mode_registry,
    write_communication_mode_attestation,
)
from .kernel import (
    VALIDATOR_VERSION,
    AurelIdentityKernel,
    DevelopmentAllowed,
    DevelopmentForbidden,
    IdentityImmutables,
    IdentityInvariant,
    IdentityKernelAttestation,
    IdentityKernelError,
    IdentityKernelHash,
    IdentityKernelValidationResult,
    default_identity_kernel_path,
    load_identity_kernel,
    parse_identity_kernel_document,
)
from .kernel_hash import compute_identity_kernel_hash, kernel_to_canonical_dict
from .kernel_validation import (
    build_identity_kernel_attestation,
    validate_identity_kernel,
    write_identity_kernel_attestation,
)
from .p14_scope import P14_FORWARD_HOOKS, P14_PATCHES, P14_SCOPE_IN, P14_SCOPE_OUT
from .persona import (
    PERSONA_VALIDATOR_VERSION,
    AurelPersonaManifest,
    PersonaBoundaries,
    PersonaChallengeBehavior,
    PersonaHonesty,
    PersonaInvariant,
    PersonaManifestAttestation,
    PersonaManifestError,
    PersonaManifestHash,
    PersonaManifestValidationResult,
    PersonaOperatorInteraction,
    PersonaPosture,
    PersonaPromptSafety,
    PersonaRiskCommunication,
    PersonaSafeSummary,
    PersonaVoice,
    default_persona_manifest_path,
    load_persona_manifest,
    parse_persona_manifest_document,
)
from .persona_hash import compute_persona_manifest_hash, persona_to_canonical_dict
from .persona_summary import build_persona_safe_summary, persona_safe_summary_to_dict
from .persona_validation import (
    build_persona_manifest_attestation,
    validate_persona_manifest,
    write_persona_manifest_attestation,
)
from .operator_contract import (
    OPERATOR_CONTRACT_VALIDATOR_VERSION,
    AccountabilityRules,
    AurelOperatorContract,
    AuthorityRelation,
    ContractParty,
    ExecutionAuthorityRules,
    NonManipulationRules,
    OperatorAuthorityRules,
    OperatorContractAttestation,
    OperatorContractBoundaries,
    OperatorContractError,
    OperatorContractHash,
    OperatorContractInvariant,
    OperatorContractParties,
    OperatorContractSafeSummary,
    OperatorContractValidationResult,
    OperatorFuturePlaceholders,
    RelationshipBehaviorRules,
    default_operator_contract_path,
    load_operator_contract,
    parse_operator_contract_document,
)
from .operator_contract_hash import (
    compute_operator_contract_hash,
    contract_to_canonical_dict,
)
from .operator_contract_summary import (
    build_operator_contract_safe_summary,
    operator_contract_safe_summary_to_dict,
)
from .operator_contract_validation import (
    build_operator_contract_attestation,
    validate_operator_contract,
    write_operator_contract_attestation,
)
from .capability_status import ALLOWED_CAPABILITY_STATUSES, CapabilityStatus, REQUIRED_CAPABILITY_STATUSES
from .self_model import (
    AurelSelfModel,
    SelfModelAttestation,
    SelfModelCapability,
    SelfModelEvidencePosture,
    SelfModelHash,
    SelfModelKnownLimitation,
    SelfModelSourceBundle,
    SelfModelValidationResult,
)
from .self_model_attestation import build_self_model_attestation, write_self_model_attestation
from .self_model_hash import (
    compute_self_model_hash,
    compute_self_model_policy_hash,
    policy_to_canonical_dict,
    self_model_to_canonical_dict,
)
from .self_model_policy import (
    SELF_MODEL_VALIDATOR_VERSION,
    SelfModelBoundaries,
    SelfModelCapabilityStatuses,
    SelfModelError,
    SelfModelHonestyRules,
    SelfModelInvariant,
    SelfModelPolicy,
    SelfModelPolicyHash,
    SelfModelPolicyValidationResult,
    SelfModelRequiredSections,
    SelfModelSourceRequirements,
    default_self_model_policy_path,
    load_self_model_policy,
    parse_self_model_policy_document,
)
from .self_model_validation import validate_aurel_self_model, validate_self_model_policy
from .identity_taxonomy import (
    TAXONOMY_NOT_IMPLEMENTED_NOTES,
    IdentityType,
    taxonomy_notes_for_null_fields,
)
from .runtime_instance import (
    RUNTIME_INSTANCE_PREFIX,
    RuntimeInstanceId,
    generate_runtime_instance_id,
)
from .agent_identity_card import (
    AgentIdentityCardAttestation,
    AurelAgentIdentityCard,
    RuntimeAgentIdentityCardHash,
    StableAgentIdentityHash,
)
from .agent_identity_card_attestation import (
    build_agent_identity_card_attestation,
    write_agent_identity_card_attestation,
)
from .agent_identity_card_hash import (
    compute_runtime_agent_identity_card_hash,
    compute_stable_agent_identity_hash,
    runtime_card_to_canonical_dict,
    stable_identity_to_canonical_dict,
)
from .agent_identity_card_policy import (
    AGENT_IDENTITY_CARD_VALIDATOR_VERSION,
    AgentAuthorityBinding,
    AgentFuturePlaceholders,
    AgentIdentityBoundaries,
    AgentIdentityCardConfig,
    AgentIdentityCardError,
    AgentIdentityCardValidationResult,
    AgentIdentityConfig,
    AgentIdentityInvariant,
    AgentIdentityTaxonomy,
    AgentRuntimeIdentity,
    AgentSourceBindings,
    default_agent_identity_card_path,
    load_agent_identity_card_config,
    parse_agent_identity_card_document,
)
from .agent_identity_card_validation import (
    validate_agent_identity_card,
    validate_agent_identity_card_config,
    validator_version,
)
from .authority_delta import (
    AuthorityDelta,
    AuthorityDeltaInput,
    AuthorityDeltaReport,
    AuthorityDeltaSeverity,
    AuthorityDeltaType,
    CAPABILITY_STATUS_ORDER,
    CLAIM_STATUS_ORDER,
    DOCTRINE_STATUS_ORDER,
    RISK_CEILING_ORDER,
    authority_delta_report_to_dict,
    authority_delta_requires_consent,
    authority_delta_requires_evidence,
    authority_delta_to_dict,
    classify_authority_delta,
    compare_authority_surfaces,
    detect_authority_deltas,
    extract_authority_surface,
    highest_authority_delta_severity,
    resolve_authority_delta_severity,
    summarize_authority_delta_report,
)
from .identity_test_battery import (
    IdentityBatteryStatus,
    IdentityTestCase,
    IdentityTestResult,
    IdentityTestBatteryReport,
    IdentityTestSeverity,
    format_identity_test_battery_report,
    identity_test_battery_report_to_dict,
    identity_test_cases,
    identity_test_result_to_dict,
    run_identity_test_battery,
    run_identity_test_case,
)
from .agent_lifecycle import (
    AgentLifecycleEligibilityProfile,
    AgentLifecyclePolicy,
    AgentLifecycleState,
    AgentLifecycleTransitionDecision,
    AgentLifecycleTransitionEvent,
    AgentLifecycleTransitionRequest,
    LifecycleLane,
    LifecycleReasonCode,
    agent_lifecycle_eligibility_profile_to_dict,
    agent_lifecycle_policy_to_dict,
    agent_lifecycle_transition_decision_to_dict,
    agent_lifecycle_transition_event_to_dict,
    agent_lifecycle_transition_request_to_dict,
    build_agent_lifecycle_eligibility_profile,
    create_lifecycle_transition_event,
    default_agent_lifecycle_policy,
    format_lifecycle_decision_human,
    format_lifecycle_profile_human,
    recommend_lifecycle_state,
    validate_agent_lifecycle_transition,
)
from .trust_evidence import (
    TrustEvidenceBundle,
    TrustEvidenceKind,
    TrustEvidenceLink,
    TrustEvidenceLinkageReport,
    TrustEvidenceRef,
    TrustEvidenceRequirement,
    TrustEvidenceStatus,
    TrustPosture,
    build_trust_evidence_bundle,
    default_trust_evidence_requirements_for_lifecycle,
    evidence_ref_from_authority_delta_report,
    evidence_ref_from_consent_record,
    evidence_ref_from_lifecycle_decision,
    evidence_ref_from_source_attestation,
    evidence_ref_from_test_battery_report,
    format_trust_evidence_bundle_human,
    format_trust_evidence_report_human,
    resolve_trust_posture,
    trust_evidence_bundle_to_dict,
    trust_evidence_link_to_dict,
    trust_evidence_linkage_report_to_dict,
    trust_evidence_ref_to_dict,
    trust_evidence_requirement_to_dict,
    validate_trust_evidence_bundle,
)
from .p14_seal_readiness import (
    P14_CLI_GROUPS,
    P14_INVARIANTS,
    P1419_INVARIANTS,
    P14_KNOWN_LIMITATIONS,
    P1420_SEAL_CHECKLIST,
    P14ModuleStatus,
    P14SealReadinessReport,
    build_p14_seal_readiness_report,
    format_p14_seal_readiness_human,
    p14_module_status_to_dict,
    p14_seal_readiness_report_to_dict,
)
from .p14_exit_seal import (
    P14_LIMITATIONS,
    P14SealCheck,
    P14SealCheckResult,
    P14SealCheckSeverity,
    P14SealCheckStatus,
    P14SealDecision,
    P14SealReport,
    P14SealStatus,
    decide_p14_seal_status,
    format_p14_seal_report,
    p14_seal_check_result_to_dict,
    p14_seal_check_to_dict,
    p14_seal_checks,
    p14_seal_decision_to_dict,
    p14_seal_report_to_dict,
    run_p14_exit_seal,
    run_p14_seal_check,
)
from .identity_cli_surface import (
    IdentityCliEnvelope,
    IdentityCliStatus,
    IdentityStatusReport,
    IdentitySubsystemStatus,
    build_identity_cli_envelope,
    build_identity_status_report,
    format_envelope_human,
    format_identity_status_human,
    identity_cli_envelope_to_dict,
    identity_status_report_to_dict,
    identity_substatus_to_dict,
    verify_identity_surface,
)
from .operator_consent import (
    ConsentBindingValidation,
    ConsentValidationError,
    OperatorConsentDecision,
    OperatorConsentRecord,
    OperatorConsentRequest,
    OperatorConsentScope,
    OperatorConsentStatus,
    build_operator_consent_request,
    consent_binding_validation_to_dict,
    deny_operator_consent,
    grant_operator_consent,
    operator_consent_decision_to_dict,
    operator_consent_record_to_dict,
    operator_consent_request_to_dict,
    revoke_operator_consent,
    validate_operator_consent_binding,
)

__all__ = [
    "P14_FORWARD_HOOKS",
    "P14_PATCHES",
    "P14_SCOPE_IN",
    "P14_SCOPE_OUT",
    "VALIDATOR_VERSION",
    "AurelIdentityKernel",
    "DevelopmentAllowed",
    "DevelopmentForbidden",
    "IdentityImmutables",
    "IdentityInvariant",
    "IdentityKernelAttestation",
    "IdentityKernelError",
    "IdentityKernelHash",
    "IdentityKernelValidationResult",
    "build_identity_kernel_attestation",
    "compute_identity_kernel_hash",
    "default_identity_kernel_path",
    "kernel_to_canonical_dict",
    "load_identity_kernel",
    "parse_identity_kernel_document",
    "validate_identity_kernel",
    "write_identity_kernel_attestation",
    "PERSONA_VALIDATOR_VERSION",
    "AurelPersonaManifest",
    "PersonaBoundaries",
    "PersonaChallengeBehavior",
    "PersonaHonesty",
    "PersonaInvariant",
    "PersonaManifestAttestation",
    "PersonaManifestError",
    "PersonaManifestHash",
    "PersonaManifestValidationResult",
    "PersonaOperatorInteraction",
    "PersonaPosture",
    "PersonaPromptSafety",
    "PersonaRiskCommunication",
    "PersonaSafeSummary",
    "PersonaVoice",
    "build_persona_manifest_attestation",
    "build_persona_safe_summary",
    "compute_persona_manifest_hash",
    "default_persona_manifest_path",
    "load_persona_manifest",
    "parse_persona_manifest_document",
    "persona_safe_summary_to_dict",
    "persona_to_canonical_dict",
    "validate_persona_manifest",
    "write_persona_manifest_attestation",
    "OPERATOR_CONTRACT_VALIDATOR_VERSION",
    "AccountabilityRules",
    "AurelOperatorContract",
    "AuthorityRelation",
    "ContractParty",
    "ExecutionAuthorityRules",
    "NonManipulationRules",
    "OperatorAuthorityRules",
    "OperatorContractAttestation",
    "OperatorContractBoundaries",
    "OperatorContractError",
    "OperatorContractHash",
    "OperatorContractInvariant",
    "OperatorContractParties",
    "OperatorContractSafeSummary",
    "OperatorContractValidationResult",
    "OperatorFuturePlaceholders",
    "RelationshipBehaviorRules",
    "build_authority_relation",
    "build_operator_contract_attestation",
    "build_operator_contract_safe_summary",
    "compute_operator_contract_hash",
    "contract_to_canonical_dict",
    "default_operator_contract_path",
    "load_operator_contract",
    "operator_contract_safe_summary_to_dict",
    "parse_operator_contract_document",
    "validate_operator_contract",
    "write_operator_contract_attestation",
    "COMMUNICATION_MODES_VALIDATOR_VERSION",
    "REQUIRED_MODES",
    "AurelCommunicationModeRegistry",
    "CommunicationModeAttestation",
    "CommunicationModeError",
    "CommunicationModeGlobalBoundaries",
    "CommunicationModeInvariant",
    "CommunicationModeLookupResult",
    "CommunicationModeRegistryHash",
    "CommunicationModeSafeSummary",
    "CommunicationModeSpec",
    "CommunicationModeValidationResult",
    "build_communication_mode_attestation",
    "build_communication_mode_safe_summary",
    "communication_mode_safe_summary_to_dict",
    "compute_communication_mode_registry_hash",
    "default_communication_modes_path",
    "get_communication_mode",
    "load_communication_mode_registry",
    "parse_communication_modes_document",
    "registry_to_canonical_dict",
    "validate_communication_mode_registry",
    "write_communication_mode_attestation",
    "ALLOWED_CAPABILITY_STATUSES",
    "REQUIRED_CAPABILITY_STATUSES",
    "CapabilityStatus",
    "SELF_MODEL_VALIDATOR_VERSION",
    "AurelSelfModel",
    "SelfModelAttestation",
    "SelfModelBoundaries",
    "SelfModelCapability",
    "SelfModelCapabilityStatuses",
    "SelfModelError",
    "SelfModelEvidencePosture",
    "SelfModelHash",
    "SelfModelHonestyRules",
    "SelfModelInvariant",
    "SelfModelKnownLimitation",
    "SelfModelPolicy",
    "SelfModelPolicyHash",
    "SelfModelPolicyValidationResult",
    "SelfModelRequiredSections",
    "SelfModelSourceBundle",
    "SelfModelSourceRequirements",
    "SelfModelValidationResult",
    "build_aurel_self_model",
    "build_aurel_self_model_from_paths",
    "build_self_model_attestation",
    "compute_self_model_hash",
    "compute_self_model_policy_hash",
    "default_self_model_policy_path",
    "load_self_model_policy",
    "parse_self_model_policy_document",
    "policy_to_canonical_dict",
    "self_model_to_canonical_dict",
    "validate_aurel_self_model",
    "validate_self_model_policy",
    "write_self_model_attestation",
    "AGENT_IDENTITY_CARD_VALIDATOR_VERSION",
    "AgentAuthorityBinding",
    "AgentFuturePlaceholders",
    "AgentIdentityBoundaries",
    "AgentIdentityCardAttestation",
    "AgentIdentityCardConfig",
    "AgentIdentityCardError",
    "AgentIdentityCardValidationResult",
    "AgentIdentityConfig",
    "AgentIdentityInvariant",
    "AgentIdentityTaxonomy",
    "AgentRuntimeIdentity",
    "AgentSourceBindings",
    "AurelAgentIdentityCard",
    "IdentityType",
    "RUNTIME_INSTANCE_PREFIX",
    "RuntimeAgentIdentityCardHash",
    "RuntimeInstanceId",
    "StableAgentIdentityHash",
    "TAXONOMY_NOT_IMPLEMENTED_NOTES",
    "build_agent_identity_card",
    "build_agent_identity_card_attestation",
    "build_agent_identity_card_from_paths",
    "compute_runtime_agent_identity_card_hash",
    "compute_stable_agent_identity_hash",
    "default_agent_identity_card_path",
    "generate_runtime_instance_id",
    "load_agent_identity_card_config",
    "parse_agent_identity_card_document",
    "runtime_card_to_canonical_dict",
    "stable_identity_to_canonical_dict",
    "taxonomy_notes_for_null_fields",
    "validate_agent_identity_card",
    "validate_agent_identity_card_config",
    "validator_version",
    "write_agent_identity_card_attestation",
    # P1.4.13 Authority Delta Detector
    "AuthorityDeltaType",
    "AuthorityDeltaSeverity",
    "AuthorityDelta",
    "AuthorityDeltaInput",
    "AuthorityDeltaReport",
    "RISK_CEILING_ORDER",
    "CLAIM_STATUS_ORDER",
    "DOCTRINE_STATUS_ORDER",
    "CAPABILITY_STATUS_ORDER",
    "authority_delta_to_dict",
    "authority_delta_report_to_dict",
    "classify_authority_delta",
    "compare_authority_surfaces",
    "detect_authority_deltas",
    "extract_authority_surface",
    "highest_authority_delta_severity",
    "resolve_authority_delta_severity",
    "authority_delta_requires_consent",
    "authority_delta_requires_evidence",
    "summarize_authority_delta_report",
    # P1.4.14 Operator Consent Binding
    "OperatorConsentStatus",
    "OperatorConsentScope",
    "OperatorConsentRequest",
    "OperatorConsentRecord",
    "ConsentBindingValidation",
    "OperatorConsentDecision",
    "ConsentValidationError",
    "build_operator_consent_request",
    "grant_operator_consent",
    "deny_operator_consent",
    "revoke_operator_consent",
    "validate_operator_consent_binding",
    "operator_consent_request_to_dict",
    "operator_consent_record_to_dict",
    "consent_binding_validation_to_dict",
    "operator_consent_decision_to_dict",
    # P1.4.15 Identity CLI Surface
    "IdentityCliStatus",
    "IdentityCliEnvelope",
    "IdentitySubsystemStatus",
    "IdentityStatusReport",
    "build_identity_cli_envelope",
    "identity_cli_envelope_to_dict",
    "identity_substatus_to_dict",
    "identity_status_report_to_dict",
    "build_identity_status_report",
    "verify_identity_surface",
    "format_identity_status_human",
    "format_envelope_human",
    # P1.4.16 Identity Test Battery
    "IdentityBatteryStatus",
    "IdentityTestSeverity",
    "IdentityTestCase",
    "IdentityTestResult",
    "IdentityTestBatteryReport",
    "identity_test_cases",
    "run_identity_test_case",
    "run_identity_test_battery",
    "identity_test_result_to_dict",
    "identity_test_battery_report_to_dict",
    "format_identity_test_battery_report",
    # P1.4.17 Agent Lifecycle
    "AgentLifecycleState",
    "LifecycleReasonCode",
    "LifecycleLane",
    "AgentLifecycleTransitionRequest",
    "AgentLifecycleTransitionDecision",
    "AgentLifecycleTransitionEvent",
    "AgentLifecyclePolicy",
    "AgentLifecycleEligibilityProfile",
    "default_agent_lifecycle_policy",
    "validate_agent_lifecycle_transition",
    "build_agent_lifecycle_eligibility_profile",
    "recommend_lifecycle_state",
    "create_lifecycle_transition_event",
    "agent_lifecycle_transition_request_to_dict",
    "agent_lifecycle_transition_decision_to_dict",
    "agent_lifecycle_transition_event_to_dict",
    "agent_lifecycle_eligibility_profile_to_dict",
    "agent_lifecycle_policy_to_dict",
    "format_lifecycle_decision_human",
    "format_lifecycle_profile_human",
    # P1.4.18 Trust Evidence Linkage
    "TrustEvidenceKind",
    "TrustEvidenceStatus",
    "TrustPosture",
    "TrustEvidenceRef",
    "TrustEvidenceRequirement",
    "TrustEvidenceLink",
    "TrustEvidenceBundle",
    "TrustEvidenceLinkageReport",
    "default_trust_evidence_requirements_for_lifecycle",
    "build_trust_evidence_bundle",
    "validate_trust_evidence_bundle",
    "resolve_trust_posture",
    "evidence_ref_from_source_attestation",
    "evidence_ref_from_test_battery_report",
    "evidence_ref_from_consent_record",
    "evidence_ref_from_authority_delta_report",
    "evidence_ref_from_lifecycle_decision",
    "trust_evidence_ref_to_dict",
    "trust_evidence_requirement_to_dict",
    "trust_evidence_link_to_dict",
    "trust_evidence_bundle_to_dict",
    "trust_evidence_linkage_report_to_dict",
    "format_trust_evidence_bundle_human",
    "format_trust_evidence_report_human",
    # P1.4.19 Seal Readiness
    "P14ModuleStatus",
    "P14SealReadinessReport",
    "P14_CLI_GROUPS",
    "P14_INVARIANTS",
    "P1419_INVARIANTS",
    "P14_KNOWN_LIMITATIONS",
    "P1420_SEAL_CHECKLIST",
    "build_p14_seal_readiness_report",
    "p14_module_status_to_dict",
    "p14_seal_readiness_report_to_dict",
    "format_p14_seal_readiness_human",
    # P1.4.20 Exit Seal
    "P14SealStatus",
    "P14SealCheckSeverity",
    "P14SealCheckStatus",
    "P14SealCheck",
    "P14SealCheckResult",
    "P14SealDecision",
    "P14SealReport",
    "P14_LIMITATIONS",
    "p14_seal_checks",
    "run_p14_seal_check",
    "run_p14_exit_seal",
    "decide_p14_seal_status",
    "p14_seal_check_to_dict",
    "p14_seal_check_result_to_dict",
    "p14_seal_decision_to_dict",
    "p14_seal_report_to_dict",
    "format_p14_seal_report",
]

_LAZY_EXPORTS = {
    "build_aurel_self_model": ".self_model_builder",
    "build_aurel_self_model_from_paths": ".self_model_builder",
    "build_agent_identity_card": ".agent_identity_card_builder",
    "build_agent_identity_card_from_paths": ".agent_identity_card_builder",
}


def __getattr__(name: str):
    target = _LAZY_EXPORTS.get(name)
    if target is not None:
        import importlib
        module = importlib.import_module(target, __name__)
        return getattr(module, name)
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
