"""AurelShell seven-surface cognitive OS contract foundation (P2.0-A).

Contract-only shell and surface registry layer. AurelShell reveals governed
state; surfaces are projections; registry is not product UI.
"""

from __future__ import annotations

from .contracts import (
    AUREL_SHELL_DISPLAY_NAME,
    AUREL_SHELL_ID,
    AUREL_SHELL_NEXT_PACK_ID,
    AUREL_SHELL_PACK_CHECKPOINT_IDS,
    AUREL_SHELL_PACK_TASK_ID,
    AUREL_SHELL_SECTION_ID,
    AurelShellBoundary,
    AurelShellContract,
    AurelShellRole,
    AurelShellSideEffectProof,
    AurelShellTruthLabel,
    AurelShellValidationError,
    assert_shell_boundary_invariants,
    assert_shell_does_not_execute,
    assert_shell_is_not_source_of_truth,
    build_aurel_shell_boundary,
    build_aurel_shell_contract,
    serialize_aurel_shell_contract,
)
from .read_model import (
    AurelSurfaceRegistrySnapshot,
    P20ACheckpointRead,
    P20ACheckpointStatus,
    P20AShellFoundationSurfaceRegistryResult,
    build_p2_0_a_shell_foundation_surface_registry_result,
    build_surface_registry_snapshot,
    detect_surface_taxonomy_drift,
    serialize_p2_0_a_pack_result,
    serialize_surface_registry_snapshot,
)
from .surface_registry import (
    CANONICAL_SURFACE_KINDS,
    CANONICAL_SURFACE_ORDER,
    OLD_SURFACE_TAXONOMY,
    AurelSurfaceAgentAccess,
    AurelSurfaceAuthorityBoundary,
    AurelSurfaceAvailability,
    AurelSurfaceCapabilityBoundary,
    AurelSurfaceContract,
    AurelSurfaceKind,
    AurelSurfaceRegistry,
    AurelSurfaceSourceOfTruth,
    AurelSurfaceTruthLabel,
    SURFACE_KIND_DISPLAY_NAMES,
    SURFACE_KIND_IDS,
    assert_hub_is_not_execution_authority,
    assert_ide_is_not_runtime_authority,
    assert_no_old_surface_taxonomy_active,
    assert_settings_is_non_root,
    assert_settings_is_not_system,
    assert_surface_registry_has_exactly_v5_5_surfaces,
    assert_system_is_operator_only,
    build_default_surface_registry,
    build_surface_contract,
    serialize_surface_contract,
    serialize_surface_registry,
)

__all__ = [
    "AUREL_SHELL_DISPLAY_NAME",
    "AUREL_SHELL_ID",
    "AUREL_SHELL_NEXT_PACK_ID",
    "AUREL_SHELL_PACK_CHECKPOINT_IDS",
    "AUREL_SHELL_PACK_TASK_ID",
    "AUREL_SHELL_SECTION_ID",
    "AurelShellBoundary",
    "AurelShellContract",
    "AurelShellRole",
    "AurelShellSideEffectProof",
    "AurelShellTruthLabel",
    "AurelShellValidationError",
    "AurelSurfaceAgentAccess",
    "AurelSurfaceAuthorityBoundary",
    "AurelSurfaceAvailability",
    "AurelSurfaceCapabilityBoundary",
    "AurelSurfaceContract",
    "AurelSurfaceKind",
    "AurelSurfaceRegistry",
    "AurelSurfaceRegistrySnapshot",
    "AurelSurfaceSourceOfTruth",
    "AurelSurfaceTruthLabel",
    "CANONICAL_SURFACE_KINDS",
    "CANONICAL_SURFACE_ORDER",
    "OLD_SURFACE_TAXONOMY",
    "P20ACheckpointRead",
    "P20ACheckpointStatus",
    "P20AShellFoundationSurfaceRegistryResult",
    "SURFACE_KIND_DISPLAY_NAMES",
    "SURFACE_KIND_IDS",
    "assert_hub_is_not_execution_authority",
    "assert_ide_is_not_runtime_authority",
    "assert_no_old_surface_taxonomy_active",
    "assert_settings_is_non_root",
    "assert_settings_is_not_system",
    "assert_shell_boundary_invariants",
    "assert_shell_does_not_execute",
    "assert_shell_is_not_source_of_truth",
    "assert_surface_registry_has_exactly_v5_5_surfaces",
    "assert_system_is_operator_only",
    "build_aurel_shell_boundary",
    "build_aurel_shell_contract",
    "build_default_surface_registry",
    "build_p2_0_a_shell_foundation_surface_registry_result",
    "build_surface_contract",
    "build_surface_registry_snapshot",
    "detect_surface_taxonomy_drift",
    "serialize_aurel_shell_contract",
    "serialize_p2_0_a_pack_result",
    "serialize_surface_contract",
    "serialize_surface_registry",
    "serialize_surface_registry_snapshot",
]
