"""Policy Cards & Behavioral Contracts (P1.6.0).

First-class, typed, versioned, scoped, validated, deterministic, hash-ready,
closed-world governance objects for AurelCore.

Policy is not documentation. Policy is not a prompt. Policy is not advice.
Policy is a governed runtime object.

Architectural laws:
  - A policy card must never grant authority merely by existing.
  - A behavioral contract must never grant authority, bypass policy cards,
    or enforce runtime behavior.
  - Unknown authority/safety fields must fail closed.
  - Metadata must not become a shadow control plane.
  - Raw source hash and canonical hash are conceptually separate.
  - P1.6.0-P1.6.2 are foundation only.
"""
from __future__ import annotations

from .contract_schema import (
    BEHAVIORAL_CONTRACT_BEHAVIOR_FIELDS,
    BEHAVIORAL_CONTRACT_CANONICAL_FIELDS,
    BEHAVIORAL_CONTRACT_CONTROL_FIELDS,
    BEHAVIORAL_CONTRACT_DANGEROUS_FIELD_NAMES,
    BEHAVIORAL_CONTRACT_DANGEROUS_METADATA_KEYS,
    BEHAVIORAL_CONTRACT_DESCRIPTIVE_FIELDS,
    BEHAVIORAL_CONTRACT_EVIDENCE_FIELDS,
    BEHAVIORAL_CONTRACT_FORBIDDEN_FIELDS,
    BEHAVIORAL_CONTRACT_IDENTITY_FIELDS,
    BEHAVIORAL_CONTRACT_OPTIONAL_FIELDS,
    BEHAVIORAL_CONTRACT_REQUIRED_FIELDS,
    BEHAVIORAL_CONTRACT_RUNTIME_FUTURE_FIELDS,
    BEHAVIORAL_CONTRACT_SCHEMA_VERSION,
    BEHAVIORAL_CONTRACT_SOURCE_FIELDS,
    BEHAVIORAL_CONTRACT_SUBJECT_FIELDS,
    SUPPORTED_BEHAVIORAL_CONTRACT_SCHEMA_VERSIONS,
    export_behavioral_contract_schema,
    get_behavioral_contract_schema,
    is_supported_behavioral_contract_schema_version,
    validate_behavioral_contract_schema_version,
)
from .risk_tier_schema import (
    DEFAULT_RISK_ACTION_CLASS_MAPPINGS,
    DEFAULT_RISK_TIER_DEFINITIONS,
    REQUIRED_RISK_TIERS,
    RISK_TIER_ACTION_MAPPING_OPTIONAL_FIELDS,
    RISK_TIER_ACTION_MAPPING_REQUIRED_FIELDS,
    RISK_TIER_CANONICAL_FIELDS,
    RISK_TIER_DANGEROUS_FIELD_NAMES,
    RISK_TIER_DANGEROUS_METADATA_KEYS,
    RISK_TIER_DEFINITION_REQUIRED_FIELDS,
    RISK_TIER_FORBIDDEN_FIELDS,
    RISK_TIER_OPTIONAL_FIELDS,
    RISK_TIER_POLICY_CARD_SCHEMA_VERSION,
    RISK_TIER_REQUIRED_FIELDS,
    SUPPORTED_RISK_TIER_POLICY_CARD_SCHEMA_VERSIONS,
    export_risk_tier_policy_schema,
    get_risk_tier_policy_schema,
    is_supported_risk_tier_policy_schema_version,
    validate_risk_tier_policy_schema_version,
)
from .contracts import (
    BehavioralContract,
    BehavioralContractEscalationAction,
    BehavioralContractEscalationRule,
    BehavioralContractEscalationTrigger,
    BehavioralContractEvidenceRequirement,
    BehavioralContractEvidenceType,
    BehavioralContractIdentity,
    BehavioralContractObligation,
    BehavioralContractObligationType,
    BehavioralContractPostcondition,
    BehavioralContractPostconditionType,
    BehavioralContractPrecondition,
    BehavioralContractPreconditionType,
    BehavioralContractProhibition,
    BehavioralContractProhibitionType,
    BehavioralContractScope,
    BehavioralContractScopeType,
    BehavioralContractSource,
    BehavioralContractStatus,
    BehavioralContractSubject,
    BehavioralContractSubjectType,
    BehavioralContractValidationIssue,
    BehavioralContractValidationResult,
    behavioral_contract_to_canonical_dict,
    compute_behavioral_contract_hash,
    load_behavioral_contract_from_dict,
    serialize_behavioral_contract_canonical,
    validate_behavioral_contract,
)
from .errors import (
    BehavioralContractError,
    BehavioralContractHashError,
    BehavioralContractSerializationError,
    BehavioralContractUnknownFieldError,
    BehavioralContractUnsafeFieldError,
    BehavioralContractValidationError,
    DataResidencyPolicyCardError,
    DataResidencyPolicyCardHashError,
    DataResidencyPolicyCardSerializationError,
    DataResidencyPolicyCardUnknownFieldError,
    DataResidencyPolicyCardUnsafeFieldError,
    DataResidencyPolicyCardValidationError,
    HumanOversightPolicyCardError,
    HumanOversightPolicyCardHashError,
    HumanOversightPolicyCardSerializationError,
    HumanOversightPolicyCardUnknownFieldError,
    HumanOversightPolicyCardUnsafeFieldError,
    HumanOversightPolicyCardValidationError,
    MemoryWritePolicyCardError,
    MemoryWritePolicyCardHashError,
    MemoryWritePolicyCardSerializationError,
    MemoryWritePolicyCardUnknownFieldError,
    MemoryWritePolicyCardUnsafeFieldError,
    MemoryWritePolicyCardValidationError,
    PromptPolicyCardError,
    PromptPolicyCardHashError,
    PromptPolicyCardSerializationError,
    PromptPolicyCardUnknownFieldError,
    PromptPolicyCardUnsafeFieldError,
    PromptPolicyCardValidationError,
    PolicyCardError,
    PolicyCardHashError,
    PolicyCardSerializationError,
    PolicyCardUnknownFieldError,
    PolicyCardUnsafeFieldError,
    PolicyCardValidationError,
    ToolPermissionPolicyCardError,
    ToolPermissionPolicyCardHashError,
    ToolPermissionPolicyCardSerializationError,
    ToolPermissionPolicyCardUnknownFieldError,
    ToolPermissionPolicyCardUnsafeFieldError,
    ToolPermissionPolicyCardValidationError,
    RiskTierPolicyCardError,
    RiskTierPolicyCardHashError,
    RiskTierPolicyCardSerializationError,
    RiskTierPolicyCardUnknownFieldError,
    RiskTierPolicyCardUnsafeFieldError,
    RiskTierPolicyCardValidationError,
    SandboxPolicyCardDecisionError,
    SandboxPolicyCardError,
    SandboxPolicyCardHashError,
    SandboxPolicyCardSchemaError,
    SandboxPolicyCardSerializationError,
    SandboxPolicyCardUnknownFieldError,
    SandboxPolicyCardUnsafeFieldError,
    SandboxPolicyCardValidationError,
)
from .hashing import compute_policy_card_hash
from .human_oversight import (
    ConfirmationRequirement,
    HumanOversightAction,
    HumanOversightEscalationRule,
    HumanOversightLevel,
    HumanOversightMode,
    HumanOversightPolicyCard,
    HumanOversightTrigger,
    HumanOversightValidationIssue,
    HumanOversightValidationResult,
    OversightEvidenceRequirement,
    OversightEvidenceType,
    ReviewerRequirement,
    RiskTierOversightMapping,
    compute_human_oversight_policy_card_hash,
    create_default_human_oversight_policy_card,
    human_oversight_policy_card_to_canonical_dict,
    load_human_oversight_policy_card_from_dict,
    serialize_human_oversight_policy_card_canonical,
    validate_human_oversight_policy_card,
    validate_human_oversight_policy_card_dict,
)
from .human_oversight_schema import (
    DEFAULT_HUMAN_OVERSIGHT_ESCALATION_RULES,
    DEFAULT_RISK_TIER_OVERSIGHT_MAPPINGS,
    HUMAN_OVERSIGHT_CANONICAL_FIELDS,
    HUMAN_OVERSIGHT_CONFIRMATION_REQUIRED_FIELDS,
    HUMAN_OVERSIGHT_DANGEROUS_FIELD_NAMES,
    HUMAN_OVERSIGHT_DANGEROUS_METADATA_KEYS,
    HUMAN_OVERSIGHT_ESCALATION_RULE_REQUIRED_FIELDS,
    HUMAN_OVERSIGHT_EVIDENCE_REQUIRED_FIELDS,
    HUMAN_OVERSIGHT_FORBIDDEN_FIELDS,
    HUMAN_OVERSIGHT_MAPPING_REQUIRED_FIELDS,
    HUMAN_OVERSIGHT_OPTIONAL_FIELDS,
    HUMAN_OVERSIGHT_POLICY_CARD_SCHEMA_VERSION,
    HUMAN_OVERSIGHT_REQUIRED_FIELDS,
    HUMAN_OVERSIGHT_REVIEWER_REQUIRED_FIELDS,
    REQUIRED_HUMAN_OVERSIGHT_RISK_TIERS,
    SUPPORTED_HUMAN_OVERSIGHT_POLICY_CARD_SCHEMA_VERSIONS,
    export_human_oversight_policy_schema,
    get_human_oversight_policy_schema,
    is_supported_human_oversight_policy_schema_version,
    validate_human_oversight_policy_schema_version,
)
from .models import (
    PolicyCard,
    PolicyCardAuthorityBinding,
    PolicyCardIdentity,
    PolicyCardKind,
    PolicyCardRiskBinding,
    PolicyCardScope,
    PolicyCardScopeType,
    PolicyCardSource,
    PolicyCardStatus,
    PolicyCardValidationIssue,
    PolicyCardValidationResult,
)
from .risk_tiers import (
    EvidenceExpectation,
    OversightLevel,
    ReversibilityLevel,
    RiskActionClass,
    RiskActionClassMapping,
    RiskTier,
    RiskTierDefinition,
    RiskTierPolicyCard,
    RiskTierValidationIssue,
    RiskTierValidationResult,
    compute_risk_tier_policy_card_hash,
    create_default_risk_tier_policy_card,
    load_risk_tier_policy_card_from_dict,
    risk_tier_policy_card_to_canonical_dict,
    serialize_risk_tier_policy_card_canonical,
    validate_risk_tier_policy_card,
    validate_risk_tier_policy_card_dict,
)
from .schema import (
    POLICY_CARD_CANONICAL_FIELDS,
    POLICY_CARD_DANGEROUS_METADATA_KEYS,
    POLICY_CARD_FORBIDDEN_FIELDS,
    POLICY_CARD_OPTIONAL_FIELDS,
    POLICY_CARD_REQUIRED_FIELDS,
    POLICY_CARD_SCHEMA_VERSION,
    SUPPORTED_POLICY_CARD_SCHEMA_VERSIONS,
    export_policy_card_schema,
    get_policy_card_schema,
    is_supported_policy_card_schema_version,
    validate_policy_card_schema_version,
)
from .serialization import (
    policy_card_to_canonical_dict,
    serialize_policy_card_canonical,
)
from .data_residency import (
    DataClass,
    DataEgressRule,
    DataExposurePermission,
    DataExposureRule,
    DataResidencyPolicyCard,
    DataResidencyRule,
    DataResidencyValidationIssue,
    DataResidencyValidationResult,
    DataResidencyZone,
    ProcessingLocation,
    RedactionRequirement,
    RedactionRequirementType,
    StorageRequirement,
    StorageRequirementType,
    compute_data_residency_policy_card_hash,
    create_default_data_residency_policy_card,
    data_residency_policy_card_to_canonical_dict,
    load_data_residency_policy_card_from_dict,
    serialize_data_residency_policy_card_canonical,
    validate_data_residency_policy_card,
    validate_data_residency_policy_card_dict,
)
from .data_residency_schema import (
    DATA_EGRESS_RULE_OPTIONAL_FIELDS,
    DATA_EGRESS_RULE_REQUIRED_FIELDS,
    DATA_EXPOSURE_RULE_REQUIRED_FIELDS,
    DATA_RESIDENCY_CANONICAL_FIELDS,
    DATA_RESIDENCY_DANGEROUS_FIELD_NAMES,
    DATA_RESIDENCY_DANGEROUS_METADATA_KEYS,
    DATA_RESIDENCY_FORBIDDEN_FIELDS,
    DATA_RESIDENCY_OPTIONAL_FIELDS,
    DATA_RESIDENCY_POLICY_CARD_SCHEMA_VERSION,
    DATA_RESIDENCY_REQUIRED_FIELDS,
    DATA_RESIDENCY_RULE_OPTIONAL_FIELDS,
    DATA_RESIDENCY_RULE_REQUIRED_FIELDS,
    REDACTION_REQUIREMENT_REQUIRED_FIELDS,
    REQUIRED_DATA_CLASSES,
    STORAGE_REQUIREMENT_REQUIRED_FIELDS,
    STRICT_LOCAL_ONLY_DATA_CLASSES,
    SUPPORTED_DATA_RESIDENCY_POLICY_CARD_SCHEMA_VERSIONS,
    export_data_residency_policy_schema,
    get_data_residency_policy_schema,
    is_supported_data_residency_policy_schema_version,
    validate_data_residency_policy_schema_version,
)
from .tool_permissions import (
    ToolCategory,
    ToolIdentityMatcher,
    ToolMatchMode,
    ToolPermissionCondition,
    ToolPermissionDecision,
    ToolPermissionPolicyCard,
    ToolPermissionRule,
    ToolPermissionType,
    ToolPermissionValidationIssue,
    ToolPermissionValidationResult,
    ToolScopeType,
    compute_tool_permission_policy_card_hash,
    create_default_tool_permission_policy_card,
    load_tool_permission_policy_card_from_dict,
    serialize_tool_permission_policy_card_canonical,
    tool_permission_policy_card_to_canonical_dict,
    validate_tool_permission_policy_card,
    validate_tool_permission_policy_card_dict,
)
from .tool_permission_schema import (
    DANGEROUS_TOOL_PERMISSION_TYPES,
    DEFAULT_DENY_TOOL_CATEGORIES,
    HIGH_RISK_TOOL_PERMISSION_TYPES,
    SUPPORTED_TOOL_PERMISSION_POLICY_CARD_SCHEMA_VERSIONS,
    TOOL_IDENTITY_MATCHER_OPTIONAL_FIELDS,
    TOOL_IDENTITY_MATCHER_REQUIRED_FIELDS,
    TOOL_PERMISSION_CANONICAL_FIELDS,
    TOOL_PERMISSION_CONDITION_OPTIONAL_FIELDS,
    TOOL_PERMISSION_CONDITION_REQUIRED_FIELDS,
    TOOL_PERMISSION_DANGEROUS_FIELD_NAMES,
    TOOL_PERMISSION_DANGEROUS_METADATA_KEYS,
    TOOL_PERMISSION_FORBIDDEN_FIELDS,
    TOOL_PERMISSION_OPTIONAL_FIELDS,
    TOOL_PERMISSION_POLICY_CARD_SCHEMA_VERSION,
    TOOL_PERMISSION_REQUIRED_FIELDS,
    TOOL_PERMISSION_RULE_OPTIONAL_FIELDS,
    TOOL_PERMISSION_RULE_REQUIRED_FIELDS,
    export_tool_permission_policy_schema,
    get_tool_permission_policy_schema,
    is_supported_tool_permission_policy_schema_version,
    validate_tool_permission_policy_schema_version,
)
from .memory_write import (
    MemoryRetentionClass,
    MemoryVerificationStatus,
    MemoryWriteDecision,
    MemoryWritePolicyCard,
    MemoryWriteRequirement,
    MemoryWriteRequirementType,
    MemoryWriteRule,
    MemoryWriteType,
    MemoryWriteValidationIssue,
    MemoryWriteValidationResult,
    MemoryZone,
    compute_memory_write_policy_card_hash,
    create_default_memory_write_policy_card,
    load_memory_write_policy_card_from_dict,
    memory_write_policy_card_to_canonical_dict,
    serialize_memory_write_policy_card_canonical,
    validate_memory_write_policy_card,
    validate_memory_write_policy_card_dict,
)
from .memory_write_schema import (
    DEFAULT_MEMORY_WRITE_RULES,
    MEMORY_WRITE_CANONICAL_FIELDS,
    MEMORY_WRITE_DANGEROUS_FIELD_NAMES,
    MEMORY_WRITE_DANGEROUS_METADATA_KEYS,
    MEMORY_WRITE_FORBIDDEN_FIELDS,
    MEMORY_WRITE_OPTIONAL_FIELDS,
    MEMORY_WRITE_POLICY_CARD_SCHEMA_VERSION,
    MEMORY_WRITE_REQUIRED_FIELDS,
    MEMORY_WRITE_REQUIREMENT_OPTIONAL_FIELDS,
    MEMORY_WRITE_REQUIREMENT_REQUIRED_FIELDS,
    MEMORY_WRITE_RULE_OPTIONAL_FIELDS,
    MEMORY_WRITE_RULE_REQUIRED_FIELDS,
    PROTECTED_MEMORY_ZONES,
    STRICT_MEMORY_DATA_CLASSES,
    SUPPORTED_MEMORY_WRITE_POLICY_CARD_SCHEMA_VERSIONS,
    export_memory_write_policy_schema,
    get_memory_write_policy_schema,
    is_supported_memory_write_policy_schema_version,
    validate_memory_write_policy_schema_version,
)
from .prompt_policy import (
    PromptBoundaryRequirement,
    PromptBoundaryRequirementType,
    PromptHandlingRule,
    PromptInjectionPattern,
    PromptInjectionRisk,
    PromptInjectionSignal,
    PromptPolicyCard,
    PromptPolicyDecision,
    PromptPolicyValidationIssue,
    PromptPolicyValidationResult,
    PromptRole,
    PromptSourceType,
    PromptTrustLevel,
    compute_prompt_policy_card_hash,
    create_default_prompt_policy_card,
    load_prompt_policy_card_from_dict,
    prompt_policy_card_to_canonical_dict,
    serialize_prompt_policy_card_canonical,
    validate_prompt_policy_card,
    validate_prompt_policy_card_dict,
)
from .prompt_policy_schema import (
    DEFAULT_PROMPT_HANDLING_RULES,
    EXTERNAL_PROMPT_SOURCES,
    PROMPT_BOUNDARY_REQUIREMENT_REQUIRED_FIELDS,
    PROMPT_HANDLING_RULE_OPTIONAL_FIELDS,
    PROMPT_HANDLING_RULE_REQUIRED_FIELDS,
    PROMPT_INJECTION_SIGNAL_REQUIRED_FIELDS,
    PROMPT_POLICY_CANONICAL_FIELDS,
    PROMPT_POLICY_CARD_SCHEMA_VERSION,
    PROMPT_POLICY_DANGEROUS_FIELD_NAMES,
    PROMPT_POLICY_DANGEROUS_METADATA_KEYS,
    PROMPT_POLICY_FORBIDDEN_FIELDS,
    PROMPT_POLICY_OPTIONAL_FIELDS,
    PROMPT_POLICY_REQUIRED_FIELDS,
    PROTECTED_PROMPT_SOURCES,
    SUPPORTED_PROMPT_POLICY_CARD_SCHEMA_VERSIONS,
    TRUSTED_PROMPT_SOURCES,
    UNTRUSTED_PROMPT_SOURCES,
    export_prompt_policy_schema,
    get_prompt_policy_schema,
    is_supported_prompt_policy_schema_version,
    validate_prompt_policy_schema_version,
)
from .sandbox import (
    ApprovalRequirement,
    CommandClass,
    DEFAULT_APPROVAL_REQUIREMENTS,
    DEFAULT_BACKEND_RULES,
    DEFAULT_COMMAND_RULES,
    DEFAULT_EGRESS_RULES,
    DEFAULT_FILESYSTEM_RULES,
    DEFAULT_RISK_TIER_SANDBOX_MAPPINGS,
    EgressPolicy,
    FilesystemScope,
    RiskTierSandboxMapping,
    SandboxBackend,
    SandboxBackendRule,
    SandboxCommandDecision,
    SandboxCommandClassRule,
    SandboxEgressRule,
    SandboxFilesystemScopeRule,
    SandboxPolicyCard,
    SandboxPolicyDecision,
    SandboxPolicyDecisionInput,
    SandboxPolicyViolation,
    SandboxPolicyWarning,
    SandboxValidationIssue,
    SandboxValidationResult,
    compute_sandbox_policy_card_hash,
    create_default_sandbox_policy_card,
    evaluate_sandbox_policy_decision,
    load_sandbox_policy_card_from_dict,
    sandbox_policy_card_to_canonical_dict,
    serialize_sandbox_policy_card_canonical,
    validate_sandbox_policy_card,
    validate_sandbox_policy_card_dict,
)
from .sandbox_schema import (
    REQUIRED_SANDBOX_RISK_TIERS,
    SANDBOX_BACKEND_RULE_REQUIRED_FIELDS,
    SANDBOX_CANONICAL_FIELDS,
    SANDBOX_COMMAND_RULE_REQUIRED_FIELDS,
    SANDBOX_DANGEROUS_FIELD_NAMES,
    SANDBOX_DANGEROUS_METADATA_KEYS,
    SANDBOX_EGRESS_RULE_REQUIRED_FIELDS,
    SANDBOX_FILESYSTEM_RULE_REQUIRED_FIELDS,
    SANDBOX_FORBIDDEN_FIELDS,
    SANDBOX_OPTIONAL_FIELDS,
    SANDBOX_POLICY_CARD_SCHEMA_VERSION,
    SANDBOX_REQUIRED_FIELDS,
    SANDBOX_RISK_TIER_MAPPING_REQUIRED_FIELDS,
    SUPPORTED_SANDBOX_POLICY_CARD_SCHEMA_VERSIONS,
    export_sandbox_policy_schema,
    get_sandbox_policy_schema,
    is_supported_sandbox_policy_schema_version,
    validate_sandbox_policy_schema_version,
)
from .validation import (
    DANGEROUS_METADATA_KEYS,
    DANGEROUS_TOP_LEVEL_FIELDS,
    load_policy_card_from_dict,
    validate_policy_card,
)
from .resolution_context import (
    CONTEXT_DANGEROUS_METADATA_KEYS,
    CONTEXT_KNOWN_FIELDS,
    EnforcementMode,
    PolicyResolutionContext,
    compute_policy_resolution_context_hash,
    load_policy_resolution_context_from_dict,
    policy_resolution_context_to_canonical_dict,
    serialize_policy_resolution_context_canonical,
)
from .resolution_result import (
    FamilyDecision,
    PolicyFamily,
    PolicyFamilyDecision,
    ResolvedPolicySet,
    ShadowAction,
    compute_resolved_policy_set_hash,
    decision_rank,
    decision_to_shadow_action,
    policy_family_decision_to_canonical_dict,
    resolved_policy_set_to_canonical_dict,
    serialize_resolved_policy_set_canonical,
)
from .resolver import (
    PolicyRuntimeResolver,
    aggregate_family_decisions,
    evaluate_data_residency_policy,
    evaluate_human_oversight_policy,
    evaluate_memory_write_policy,
    evaluate_prompt_policy,
    evaluate_risk_tier_policy,
    evaluate_sandbox_policy,
    evaluate_tool_permission_policy,
    resolve_policy_cards,
    resolve_policy_cards_from_registry,
)
from .errors import (
    PolicyCardRegistryError,
    PolicyCardRegistryValidationError,
    PolicyContextBindingError,
    PolicyResolutionAdapterError,
    PolicyResolutionContextError,
    PolicyResolutionError,
    PolicyResolutionSerializationError,
    PolicyResolutionValidationError,
    PolicyRiskMappingError,
    PolicyRuntimeProjectionError,
    PolicyRuntimeSnapshotValidationError,
    PolicyShadowProjectionError,
)
from .risk_mapping import (
    RiskMappingResult,
    map_approval_risk_to_policy_tier,
    map_identity_risk_to_policy_tier,
    map_runtime_risk_to_policy_tier,
    normalize_risk_tier,
)
from .context_binding import (
    BINDING_KNOWN_FIELDS,
    build_policy_resolution_context,
    context_from_command_like,
    context_from_runtime_request_like,
    context_from_tool_invocation_like,
    normalize_resolution_context,
)
from .registry import (
    PolicyCardApplicability,
    PolicyCardRegistry,
)
from .runtime_projection import (
    CustosEffectiveAction,
    PolicyRuntimeAlignment,
    PolicyRuntimeMismatch,
    PolicyShadowProjection,
    RuntimeEffectiveAction,
    RuntimePolicySnapshot,
    compute_policy_shadow_projection_hash,
    compute_runtime_policy_snapshot_hash,
    policy_shadow_projection_to_canonical_dict,
    project_policy_resolution_against_runtime,
    runtime_policy_snapshot_to_canonical_dict,
    serialize_policy_shadow_projection_canonical,
    serialize_runtime_policy_snapshot_canonical,
    shadow_projection_error_payload,
)
from .conflict_algebra import (
    PolicyConflict,
    PolicyConflictResolution,
    PolicyConflictResolutionStrategy,
    PolicyConflictSet,
    PolicyConflictSeverity,
    PolicyConflictType,
    PolicyDecisionRank,
    PolicyPrecedenceRule,
    PolicySpecificityScore,
    StrictestWinsResult,
    classify_policy_conflicts,
    compute_specificity_score,
    normalize_policy_decision_rank,
    resolve_policy_conflicts_strictest_wins,
)

__all__ = [
    # ─ Policy Card models ─
    "PolicyCard",
    "PolicyCardIdentity",
    "PolicyCardKind",
    "PolicyCardStatus",
    "PolicyCardScope",
    "PolicyCardScopeType",
    "PolicyCardRiskBinding",
    "PolicyCardAuthorityBinding",
    "PolicyCardSource",
    "PolicyCardValidationIssue",
    "PolicyCardValidationResult",
    # ─ Policy Card schema ─
    "POLICY_CARD_SCHEMA_VERSION",
    "SUPPORTED_POLICY_CARD_SCHEMA_VERSIONS",
    "POLICY_CARD_REQUIRED_FIELDS",
    "POLICY_CARD_OPTIONAL_FIELDS",
    "POLICY_CARD_FORBIDDEN_FIELDS",
    "POLICY_CARD_CANONICAL_FIELDS",
    "POLICY_CARD_DANGEROUS_METADATA_KEYS",
    "export_policy_card_schema",
    "get_policy_card_schema",
    "is_supported_policy_card_schema_version",
    "validate_policy_card_schema_version",
    # ─ Policy Card validation ─
    "validate_policy_card",
    "load_policy_card_from_dict",
    "DANGEROUS_TOP_LEVEL_FIELDS",
    "DANGEROUS_METADATA_KEYS",
    # ─ Policy Card serialization ─
    "serialize_policy_card_canonical",
    "policy_card_to_canonical_dict",
    # ─ Policy Card hashing ─
    "compute_policy_card_hash",
    # ─ Policy Card errors ─
    "PolicyCardError",
    "PolicyCardValidationError",
    "PolicyCardSerializationError",
    "PolicyCardHashError",
    "PolicyCardUnknownFieldError",
    "PolicyCardUnsafeFieldError",
    # ─ Behavioral Contract enums ─
    "BehavioralContractStatus",
    "BehavioralContractSubjectType",
    "BehavioralContractScopeType",
    "BehavioralContractObligationType",
    "BehavioralContractProhibitionType",
    "BehavioralContractPreconditionType",
    "BehavioralContractPostconditionType",
    "BehavioralContractEvidenceType",
    "BehavioralContractEscalationTrigger",
    "BehavioralContractEscalationAction",
    # ─ Behavioral Contract models ─
    "BehavioralContract",
    "BehavioralContractIdentity",
    "BehavioralContractSubject",
    "BehavioralContractScope",
    "BehavioralContractObligation",
    "BehavioralContractProhibition",
    "BehavioralContractPrecondition",
    "BehavioralContractPostcondition",
    "BehavioralContractEvidenceRequirement",
    "BehavioralContractEscalationRule",
    "BehavioralContractSource",
    "BehavioralContractValidationIssue",
    "BehavioralContractValidationResult",
    # ─ Behavioral Contract schema ─
    "BEHAVIORAL_CONTRACT_SCHEMA_VERSION",
    "SUPPORTED_BEHAVIORAL_CONTRACT_SCHEMA_VERSIONS",
    "BEHAVIORAL_CONTRACT_REQUIRED_FIELDS",
    "BEHAVIORAL_CONTRACT_OPTIONAL_FIELDS",
    "BEHAVIORAL_CONTRACT_FORBIDDEN_FIELDS",
    "BEHAVIORAL_CONTRACT_CANONICAL_FIELDS",
    "BEHAVIORAL_CONTRACT_CONTROL_FIELDS",
    "BEHAVIORAL_CONTRACT_IDENTITY_FIELDS",
    "BEHAVIORAL_CONTRACT_SUBJECT_FIELDS",
    "BEHAVIORAL_CONTRACT_BEHAVIOR_FIELDS",
    "BEHAVIORAL_CONTRACT_EVIDENCE_FIELDS",
    "BEHAVIORAL_CONTRACT_SOURCE_FIELDS",
    "BEHAVIORAL_CONTRACT_DESCRIPTIVE_FIELDS",
    "BEHAVIORAL_CONTRACT_RUNTIME_FUTURE_FIELDS",
    "BEHAVIORAL_CONTRACT_DANGEROUS_FIELD_NAMES",
    "BEHAVIORAL_CONTRACT_DANGEROUS_METADATA_KEYS",
    "export_behavioral_contract_schema",
    "get_behavioral_contract_schema",
    "is_supported_behavioral_contract_schema_version",
    "validate_behavioral_contract_schema_version",
    # ─ Behavioral Contract validation ─
    "validate_behavioral_contract",
    "load_behavioral_contract_from_dict",
    # ─ Behavioral Contract serialization ─
    "serialize_behavioral_contract_canonical",
    "behavioral_contract_to_canonical_dict",
    # ─ Behavioral Contract hashing ─
    "compute_behavioral_contract_hash",
    # ─ Behavioral Contract errors ─
    "BehavioralContractError",
    "BehavioralContractValidationError",
    "BehavioralContractSerializationError",
    "BehavioralContractHashError",
    "BehavioralContractUnknownFieldError",
    "BehavioralContractUnsafeFieldError",
    # - Risk Tier Policy Card enums -
    "RiskTier",
    "ReversibilityLevel",
    "OversightLevel",
    "EvidenceExpectation",
    "RiskActionClass",
    # - Risk Tier Policy Card models -
    "RiskTierDefinition",
    "RiskActionClassMapping",
    "RiskTierPolicyCard",
    "RiskTierValidationIssue",
    "RiskTierValidationResult",
    # - Risk Tier Policy Card schema -
    "RISK_TIER_POLICY_CARD_SCHEMA_VERSION",
    "SUPPORTED_RISK_TIER_POLICY_CARD_SCHEMA_VERSIONS",
    "REQUIRED_RISK_TIERS",
    "RISK_TIER_REQUIRED_FIELDS",
    "RISK_TIER_OPTIONAL_FIELDS",
    "RISK_TIER_FORBIDDEN_FIELDS",
    "RISK_TIER_CANONICAL_FIELDS",
    "RISK_TIER_DEFINITION_REQUIRED_FIELDS",
    "RISK_TIER_ACTION_MAPPING_REQUIRED_FIELDS",
    "RISK_TIER_ACTION_MAPPING_OPTIONAL_FIELDS",
    "RISK_TIER_DANGEROUS_FIELD_NAMES",
    "RISK_TIER_DANGEROUS_METADATA_KEYS",
    "DEFAULT_RISK_TIER_DEFINITIONS",
    "DEFAULT_RISK_ACTION_CLASS_MAPPINGS",
    "export_risk_tier_policy_schema",
    "get_risk_tier_policy_schema",
    "is_supported_risk_tier_policy_schema_version",
    "validate_risk_tier_policy_schema_version",
    # - Risk Tier Policy Card validation -
    "create_default_risk_tier_policy_card",
    "validate_risk_tier_policy_card",
    "validate_risk_tier_policy_card_dict",
    "load_risk_tier_policy_card_from_dict",
    # - Risk Tier Policy Card serialization -
    "risk_tier_policy_card_to_canonical_dict",
    "serialize_risk_tier_policy_card_canonical",
    # - Risk Tier Policy Card hashing -
    "compute_risk_tier_policy_card_hash",
    # - Risk Tier Policy Card errors -
    "RiskTierPolicyCardError",
    "RiskTierPolicyCardValidationError",
    "RiskTierPolicyCardSerializationError",
    "RiskTierPolicyCardHashError",
    "RiskTierPolicyCardUnknownFieldError",
    "RiskTierPolicyCardUnsafeFieldError",
    # - Human Oversight Policy Card enums -
    "HumanOversightLevel",
    "HumanOversightMode",
    "HumanOversightTrigger",
    "HumanOversightAction",
    "OversightEvidenceType",
    # - Human Oversight Policy Card models -
    "ConfirmationRequirement",
    "ReviewerRequirement",
    "OversightEvidenceRequirement",
    "RiskTierOversightMapping",
    "HumanOversightEscalationRule",
    "HumanOversightPolicyCard",
    "HumanOversightValidationIssue",
    "HumanOversightValidationResult",
    # - Human Oversight Policy Card schema -
    "HUMAN_OVERSIGHT_POLICY_CARD_SCHEMA_VERSION",
    "SUPPORTED_HUMAN_OVERSIGHT_POLICY_CARD_SCHEMA_VERSIONS",
    "HUMAN_OVERSIGHT_REQUIRED_FIELDS",
    "HUMAN_OVERSIGHT_OPTIONAL_FIELDS",
    "HUMAN_OVERSIGHT_FORBIDDEN_FIELDS",
    "HUMAN_OVERSIGHT_CANONICAL_FIELDS",
    "HUMAN_OVERSIGHT_MAPPING_REQUIRED_FIELDS",
    "HUMAN_OVERSIGHT_ESCALATION_RULE_REQUIRED_FIELDS",
    "HUMAN_OVERSIGHT_CONFIRMATION_REQUIRED_FIELDS",
    "HUMAN_OVERSIGHT_REVIEWER_REQUIRED_FIELDS",
    "HUMAN_OVERSIGHT_EVIDENCE_REQUIRED_FIELDS",
    "HUMAN_OVERSIGHT_DANGEROUS_FIELD_NAMES",
    "HUMAN_OVERSIGHT_DANGEROUS_METADATA_KEYS",
    "REQUIRED_HUMAN_OVERSIGHT_RISK_TIERS",
    "DEFAULT_RISK_TIER_OVERSIGHT_MAPPINGS",
    "DEFAULT_HUMAN_OVERSIGHT_ESCALATION_RULES",
    "export_human_oversight_policy_schema",
    "get_human_oversight_policy_schema",
    "is_supported_human_oversight_policy_schema_version",
    "validate_human_oversight_policy_schema_version",
    # - Human Oversight Policy Card validation -
    "create_default_human_oversight_policy_card",
    "validate_human_oversight_policy_card",
    "validate_human_oversight_policy_card_dict",
    "load_human_oversight_policy_card_from_dict",
    # - Human Oversight Policy Card serialization -
    "human_oversight_policy_card_to_canonical_dict",
    "serialize_human_oversight_policy_card_canonical",
    # - Human Oversight Policy Card hashing -
    "compute_human_oversight_policy_card_hash",
    # - Human Oversight Policy Card errors -
    "HumanOversightPolicyCardError",
    "HumanOversightPolicyCardValidationError",
    "HumanOversightPolicyCardSerializationError",
    "HumanOversightPolicyCardHashError",
    "HumanOversightPolicyCardUnknownFieldError",
    "HumanOversightPolicyCardUnsafeFieldError",
    # - Data Residency Policy Card enums -
    "DataResidencyZone",
    "DataClass",
    "ProcessingLocation",
    "RedactionRequirementType",
    "StorageRequirementType",
    "DataExposurePermission",
    # - Data Residency Policy Card models -
    "RedactionRequirement",
    "StorageRequirement",
    "DataEgressRule",
    "DataExposureRule",
    "DataResidencyRule",
    "DataResidencyPolicyCard",
    "DataResidencyValidationIssue",
    "DataResidencyValidationResult",
    # - Data Residency Policy Card schema -
    "DATA_RESIDENCY_POLICY_CARD_SCHEMA_VERSION",
    "SUPPORTED_DATA_RESIDENCY_POLICY_CARD_SCHEMA_VERSIONS",
    "REQUIRED_DATA_CLASSES",
    "STRICT_LOCAL_ONLY_DATA_CLASSES",
    "DATA_RESIDENCY_REQUIRED_FIELDS",
    "DATA_RESIDENCY_OPTIONAL_FIELDS",
    "DATA_RESIDENCY_FORBIDDEN_FIELDS",
    "DATA_RESIDENCY_CANONICAL_FIELDS",
    "DATA_RESIDENCY_RULE_REQUIRED_FIELDS",
    "DATA_RESIDENCY_RULE_OPTIONAL_FIELDS",
    "DATA_EGRESS_RULE_REQUIRED_FIELDS",
    "DATA_EGRESS_RULE_OPTIONAL_FIELDS",
    "DATA_EXPOSURE_RULE_REQUIRED_FIELDS",
    "REDACTION_REQUIREMENT_REQUIRED_FIELDS",
    "STORAGE_REQUIREMENT_REQUIRED_FIELDS",
    "DATA_RESIDENCY_DANGEROUS_FIELD_NAMES",
    "DATA_RESIDENCY_DANGEROUS_METADATA_KEYS",
    "export_data_residency_policy_schema",
    "get_data_residency_policy_schema",
    "is_supported_data_residency_policy_schema_version",
    "validate_data_residency_policy_schema_version",
    # - Data Residency Policy Card validation -
    "create_default_data_residency_policy_card",
    "validate_data_residency_policy_card",
    "validate_data_residency_policy_card_dict",
    "load_data_residency_policy_card_from_dict",
    # - Data Residency Policy Card serialization -
    "data_residency_policy_card_to_canonical_dict",
    "serialize_data_residency_policy_card_canonical",
    # - Data Residency Policy Card hashing -
    "compute_data_residency_policy_card_hash",
    # - Data Residency Policy Card errors -
    "DataResidencyPolicyCardError",
    "DataResidencyPolicyCardValidationError",
    "DataResidencyPolicyCardSerializationError",
    "DataResidencyPolicyCardHashError",
    "DataResidencyPolicyCardUnknownFieldError",
    "DataResidencyPolicyCardUnsafeFieldError",
    # - Tool Permission Policy Card enums -
    "ToolCategory",
    "ToolPermissionType",
    "ToolPermissionDecision",
    "ToolScopeType",
    "ToolMatchMode",
    # - Tool Permission Policy Card models -
    "ToolIdentityMatcher",
    "ToolPermissionCondition",
    "ToolPermissionRule",
    "ToolPermissionPolicyCard",
    "ToolPermissionValidationIssue",
    "ToolPermissionValidationResult",
    # - Tool Permission Policy Card schema -
    "TOOL_PERMISSION_POLICY_CARD_SCHEMA_VERSION",
    "SUPPORTED_TOOL_PERMISSION_POLICY_CARD_SCHEMA_VERSIONS",
    "DEFAULT_DENY_TOOL_CATEGORIES",
    "DANGEROUS_TOOL_PERMISSION_TYPES",
    "HIGH_RISK_TOOL_PERMISSION_TYPES",
    "TOOL_PERMISSION_REQUIRED_FIELDS",
    "TOOL_PERMISSION_OPTIONAL_FIELDS",
    "TOOL_PERMISSION_FORBIDDEN_FIELDS",
    "TOOL_PERMISSION_CANONICAL_FIELDS",
    "TOOL_PERMISSION_RULE_REQUIRED_FIELDS",
    "TOOL_PERMISSION_RULE_OPTIONAL_FIELDS",
    "TOOL_IDENTITY_MATCHER_REQUIRED_FIELDS",
    "TOOL_IDENTITY_MATCHER_OPTIONAL_FIELDS",
    "TOOL_PERMISSION_CONDITION_REQUIRED_FIELDS",
    "TOOL_PERMISSION_CONDITION_OPTIONAL_FIELDS",
    "TOOL_PERMISSION_DANGEROUS_FIELD_NAMES",
    "TOOL_PERMISSION_DANGEROUS_METADATA_KEYS",
    "export_tool_permission_policy_schema",
    "get_tool_permission_policy_schema",
    "is_supported_tool_permission_policy_schema_version",
    "validate_tool_permission_policy_schema_version",
    # - Tool Permission Policy Card validation -
    "create_default_tool_permission_policy_card",
    "validate_tool_permission_policy_card",
    "validate_tool_permission_policy_card_dict",
    "load_tool_permission_policy_card_from_dict",
    # - Tool Permission Policy Card serialization -
    "tool_permission_policy_card_to_canonical_dict",
    "serialize_tool_permission_policy_card_canonical",
    # - Tool Permission Policy Card hashing -
    "compute_tool_permission_policy_card_hash",
    # - Tool Permission Policy Card errors -
    "ToolPermissionPolicyCardError",
    "ToolPermissionPolicyCardValidationError",
    "ToolPermissionPolicyCardSerializationError",
    "ToolPermissionPolicyCardHashError",
    "ToolPermissionPolicyCardUnknownFieldError",
    "ToolPermissionPolicyCardUnsafeFieldError",
    # - Memory Write Policy Card enums -
    "MemoryZone",
    "MemoryWriteType",
    "MemoryWriteDecision",
    "MemoryVerificationStatus",
    "MemoryRetentionClass",
    "MemoryWriteRequirementType",
    # - Memory Write Policy Card models -
    "MemoryWriteRequirement",
    "MemoryWriteRule",
    "MemoryWritePolicyCard",
    "MemoryWriteValidationIssue",
    "MemoryWriteValidationResult",
    # - Memory Write Policy Card schema -
    "MEMORY_WRITE_POLICY_CARD_SCHEMA_VERSION",
    "SUPPORTED_MEMORY_WRITE_POLICY_CARD_SCHEMA_VERSIONS",
    "PROTECTED_MEMORY_ZONES",
    "STRICT_MEMORY_DATA_CLASSES",
    "DEFAULT_MEMORY_WRITE_RULES",
    "MEMORY_WRITE_REQUIRED_FIELDS",
    "MEMORY_WRITE_OPTIONAL_FIELDS",
    "MEMORY_WRITE_FORBIDDEN_FIELDS",
    "MEMORY_WRITE_CANONICAL_FIELDS",
    "MEMORY_WRITE_RULE_REQUIRED_FIELDS",
    "MEMORY_WRITE_RULE_OPTIONAL_FIELDS",
    "MEMORY_WRITE_REQUIREMENT_REQUIRED_FIELDS",
    "MEMORY_WRITE_REQUIREMENT_OPTIONAL_FIELDS",
    "MEMORY_WRITE_DANGEROUS_FIELD_NAMES",
    "MEMORY_WRITE_DANGEROUS_METADATA_KEYS",
    "export_memory_write_policy_schema",
    "get_memory_write_policy_schema",
    "is_supported_memory_write_policy_schema_version",
    "validate_memory_write_policy_schema_version",
    # - Memory Write Policy Card validation -
    "create_default_memory_write_policy_card",
    "validate_memory_write_policy_card",
    "validate_memory_write_policy_card_dict",
    "load_memory_write_policy_card_from_dict",
    # - Memory Write Policy Card serialization -
    "memory_write_policy_card_to_canonical_dict",
    "serialize_memory_write_policy_card_canonical",
    # - Memory Write Policy Card hashing -
    "compute_memory_write_policy_card_hash",
    # - Memory Write Policy Card errors -
    "MemoryWritePolicyCardError",
    "MemoryWritePolicyCardValidationError",
    "MemoryWritePolicyCardSerializationError",
    "MemoryWritePolicyCardHashError",
    "MemoryWritePolicyCardUnknownFieldError",
    "MemoryWritePolicyCardUnsafeFieldError",
    # - Prompt Policy Card enums -
    "PromptSourceType",
    "PromptTrustLevel",
    "PromptRole",
    "PromptPolicyDecision",
    "PromptInjectionRisk",
    "PromptInjectionPattern",
    "PromptBoundaryRequirementType",
    # - Prompt Policy Card models -
    "PromptBoundaryRequirement",
    "PromptInjectionSignal",
    "PromptHandlingRule",
    "PromptPolicyCard",
    "PromptPolicyValidationIssue",
    "PromptPolicyValidationResult",
    # - Prompt Policy Card schema -
    "PROMPT_POLICY_CARD_SCHEMA_VERSION",
    "SUPPORTED_PROMPT_POLICY_CARD_SCHEMA_VERSIONS",
    "TRUSTED_PROMPT_SOURCES",
    "UNTRUSTED_PROMPT_SOURCES",
    "EXTERNAL_PROMPT_SOURCES",
    "PROTECTED_PROMPT_SOURCES",
    "DEFAULT_PROMPT_HANDLING_RULES",
    "PROMPT_POLICY_REQUIRED_FIELDS",
    "PROMPT_POLICY_OPTIONAL_FIELDS",
    "PROMPT_POLICY_FORBIDDEN_FIELDS",
    "PROMPT_POLICY_CANONICAL_FIELDS",
    "PROMPT_HANDLING_RULE_REQUIRED_FIELDS",
    "PROMPT_HANDLING_RULE_OPTIONAL_FIELDS",
    "PROMPT_BOUNDARY_REQUIREMENT_REQUIRED_FIELDS",
    "PROMPT_INJECTION_SIGNAL_REQUIRED_FIELDS",
    "PROMPT_POLICY_DANGEROUS_FIELD_NAMES",
    "PROMPT_POLICY_DANGEROUS_METADATA_KEYS",
    "export_prompt_policy_schema",
    "get_prompt_policy_schema",
    "is_supported_prompt_policy_schema_version",
    "validate_prompt_policy_schema_version",
    # - Prompt Policy Card validation -
    "create_default_prompt_policy_card",
    "validate_prompt_policy_card",
    "validate_prompt_policy_card_dict",
    "load_prompt_policy_card_from_dict",
    # - Prompt Policy Card serialization -
    "prompt_policy_card_to_canonical_dict",
    "serialize_prompt_policy_card_canonical",
    # - Prompt Policy Card hashing -
    "compute_prompt_policy_card_hash",
    # - Prompt Policy Card errors -
    "PromptPolicyCardError",
    "PromptPolicyCardValidationError",
    "PromptPolicyCardSerializationError",
    "PromptPolicyCardHashError",
    "PromptPolicyCardUnknownFieldError",
    "PromptPolicyCardUnsafeFieldError",
    # - Sandbox Policy Card enums -
    "SandboxBackend",
    "FilesystemScope",
    "EgressPolicy",
    "CommandClass",
    "SandboxCommandDecision",
    "ApprovalRequirement",
    # - Sandbox Policy Card models -
    "SandboxBackendRule",
    "SandboxFilesystemScopeRule",
    "SandboxEgressRule",
    "SandboxCommandClassRule",
    "RiskTierSandboxMapping",
    "SandboxPolicyViolation",
    "SandboxPolicyWarning",
    "SandboxPolicyDecisionInput",
    "SandboxPolicyCard",
    "SandboxValidationIssue",
    "SandboxValidationResult",
    # - Sandbox Policy Card schema -
    "SANDBOX_POLICY_CARD_SCHEMA_VERSION",
    "SUPPORTED_SANDBOX_POLICY_CARD_SCHEMA_VERSIONS",
    "REQUIRED_SANDBOX_RISK_TIERS",
    "SANDBOX_REQUIRED_FIELDS",
    "SANDBOX_OPTIONAL_FIELDS",
    "SANDBOX_FORBIDDEN_FIELDS",
    "SANDBOX_CANONICAL_FIELDS",
    "SANDBOX_BACKEND_RULE_REQUIRED_FIELDS",
    "SANDBOX_FILESYSTEM_RULE_REQUIRED_FIELDS",
    "SANDBOX_EGRESS_RULE_REQUIRED_FIELDS",
    "SANDBOX_COMMAND_RULE_REQUIRED_FIELDS",
    "SANDBOX_RISK_TIER_MAPPING_REQUIRED_FIELDS",
    "SANDBOX_DANGEROUS_FIELD_NAMES",
    "SANDBOX_DANGEROUS_METADATA_KEYS",
    "DEFAULT_BACKEND_RULES",
    "DEFAULT_FILESYSTEM_RULES",
    "DEFAULT_EGRESS_RULES",
    "DEFAULT_COMMAND_RULES",
    "DEFAULT_RISK_TIER_SANDBOX_MAPPINGS",
    "DEFAULT_APPROVAL_REQUIREMENTS",
    "export_sandbox_policy_schema",
    "get_sandbox_policy_schema",
    "is_supported_sandbox_policy_schema_version",
    "validate_sandbox_policy_schema_version",
    # - Sandbox Policy Card validation -
    "create_default_sandbox_policy_card",
    "validate_sandbox_policy_card",
    "validate_sandbox_policy_card_dict",
    "load_sandbox_policy_card_from_dict",
    # - Sandbox Policy Card serialization -
    "sandbox_policy_card_to_canonical_dict",
    "serialize_sandbox_policy_card_canonical",
    # - Sandbox Policy Card hashing -
    "compute_sandbox_policy_card_hash",
    # - Sandbox Policy Card decision evaluation -
    "evaluate_sandbox_policy_decision",
    # - Sandbox Policy Card errors -
    "SandboxPolicyCardError",
    "SandboxPolicyCardValidationError",
    "SandboxPolicyCardSerializationError",
    "SandboxPolicyCardHashError",
    "SandboxPolicyCardUnknownFieldError",
    "SandboxPolicyCardUnsafeFieldError",
    # - Policy Resolution Registry & Binding (P1.6.11) -
    "RiskMappingResult",
    "normalize_risk_tier",
    "map_runtime_risk_to_policy_tier",
    "map_approval_risk_to_policy_tier",
    "map_identity_risk_to_policy_tier",
    "BINDING_KNOWN_FIELDS",
    "build_policy_resolution_context",
    "normalize_resolution_context",
    "context_from_command_like",
    "context_from_tool_invocation_like",
    "context_from_runtime_request_like",
    "PolicyCardApplicability",
    "PolicyCardRegistry",
    # ─ Custos v0 Policy Runtime Resolver — context (P1.6.10) ─
    "EnforcementMode",
    "PolicyResolutionContext",
    "CONTEXT_KNOWN_FIELDS",
    "CONTEXT_DANGEROUS_METADATA_KEYS",
    "policy_resolution_context_to_canonical_dict",
    "serialize_policy_resolution_context_canonical",
    "compute_policy_resolution_context_hash",
    "load_policy_resolution_context_from_dict",
    # ─ Custos v0 Policy Runtime Resolver — result types ─
    "PolicyFamily",
    "FamilyDecision",
    "ShadowAction",
    "PolicyFamilyDecision",
    "ResolvedPolicySet",
    "decision_rank",
    "decision_to_shadow_action",
    "policy_family_decision_to_canonical_dict",
    "resolved_policy_set_to_canonical_dict",
    "serialize_resolved_policy_set_canonical",
    "compute_resolved_policy_set_hash",
    # ─ Custos v0 Policy Runtime Resolver — resolver ─
    "PolicyRuntimeResolver",
    "resolve_policy_cards",
    "resolve_policy_cards_from_registry",
    "aggregate_family_decisions",
    "evaluate_risk_tier_policy",
    "evaluate_human_oversight_policy",
    "evaluate_data_residency_policy",
    "evaluate_tool_permission_policy",
    "evaluate_memory_write_policy",
    "evaluate_prompt_policy",
    "evaluate_sandbox_policy",
    # ─ Custos v0 Policy Runtime Resolver — errors ─
    "PolicyResolutionError",
    "PolicyResolutionValidationError",
    "PolicyResolutionContextError",
    "PolicyResolutionSerializationError",
    "PolicyResolutionAdapterError",
    "PolicyCardRegistryError",
    "PolicyCardRegistryValidationError",
    "PolicyContextBindingError",
    "PolicyRiskMappingError",
    # - Runtime shadow projection (P1.6.12) -
    "RuntimePolicySnapshot",
    "PolicyShadowProjection",
    "RuntimeEffectiveAction",
    "CustosEffectiveAction",
    "PolicyRuntimeAlignment",
    "PolicyRuntimeMismatch",
    "runtime_policy_snapshot_to_canonical_dict",
    "serialize_runtime_policy_snapshot_canonical",
    "compute_runtime_policy_snapshot_hash",
    "policy_shadow_projection_to_canonical_dict",
    "serialize_policy_shadow_projection_canonical",
    "compute_policy_shadow_projection_hash",
    "project_policy_resolution_against_runtime",
    "shadow_projection_error_payload",
    "PolicyRuntimeProjectionError",
    "PolicyRuntimeSnapshotValidationError",
    "PolicyShadowProjectionError",
    # - Policy Conflict Algebra (P1.6.13) -
    "PolicyDecisionRank",
    "PolicyConflictType",
    "PolicyConflictSeverity",
    "PolicyConflictResolutionStrategy",
    "PolicySpecificityScore",
    "PolicyPrecedenceRule",
    "PolicyConflict",
    "PolicyConflictSet",
    "PolicyConflictResolution",
    "StrictestWinsResult",
    "normalize_policy_decision_rank",
    "compute_specificity_score",
    "classify_policy_conflicts",
    "resolve_policy_conflicts_strictest_wins",
]
